Repository Azure/iotedge, pull requests merged in 2020-07, with the labels that each got.

#3181 [mqtt] Make edgehub authorizer to be aware of edge modules
  mqtt/mqtt-broker-core/src/auth/authentication.rs
  mqtt/mqtt-broker-core/src/auth/mod.rs
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authentication/local.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
Labels: area:mqtt, ready-to-merge

#3188 [mqtt] Ensure module-to-module topics translation and authz
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
Labels: area:mqtt, ready-to-merge

#3179 [k8s] Experimental Service Options
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CombinedKubernetesConfigProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/CreatePodParameters.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesExperimentalCreatePodParameters.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/service/KubernetesServiceMapper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/service/KubernetesServiceOptions.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesExperimentalPodParametersTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
  kubernetes/doc/create-options.md
  kubernetes/doc/edge-deployment-to-k8s-translations.md
Labels: ready-to-merge

#3191 Update the base image for 1.0.9 arm32
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-modules/DirectMethodCloudSender/docker/linux/arm32v7/Dockerfile
  edge-modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  edge-modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  edge-modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  edge-modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  edge-modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  edge-modules/TwinTester/docker/linux/arm32v7/Dockerfile
  edge-modules/load-gen/docker/linux/arm32v7/Dockerfile
Labels: ready-to-merge

#3140 Add watchdog process that will oversee child processes for edgehub and broker
  edge-hub/watchdog/Cargo.lock
  edge-hub/watchdog/Cargo.toml
  edge-hub/watchdog/Makefile
  edge-hub/watchdog/src/child.rs
  edge-hub/watchdog/src/main.rs
Labels: ready-to-merge

#3192 Update base image version to 1.0.5.1
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  scripts/linux/createArmBase.sh
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3199 Update SDK Client 1.27.0
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DeploymentTester/DeploymentTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TestAnalyzer/TestAnalyzer.csproj
  test/modules/TestResultCoordinator/TestResultCoordinator.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#3190 Fix OnBehalfOf auth in EdgeHub
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeCertificateAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeTokenAuthenticatorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
Labels: ready-to-merge

#3203 Update SDK Client 1.27.0
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DeploymentTester/DeploymentTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TestAnalyzer/TestAnalyzer.csproj
  test/modules/TestResultCoordinator/TestResultCoordinator.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#3206 Fix: Edgelet unable to pull using certain passwords.
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
Labels: ready-to-merge

#3204 Fix edgehub container misconfiguration
  edge-hub/watchdog/src/child.rs
  edge-hub/watchdog/src/main.rs
Labels: ready-to-merge

#3173 Fix edge agent connection (#3172)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Labels: 1.0.10, ready-to-merge

#3197 Adding Digest field to modules
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/CombinedDockerConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/CombinedDockerConfigProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerReportedConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/NotaryContentTrust.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/CombinedEdgeletConfigProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/PodExtensions.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerConfigTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerEnvironmentTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerReportedConfigTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/commands/CreateCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/commands/PullCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker.Test/CombinedEdgeletConfigProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/reporters/IoTHubReporterTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/CombinedKubernetesConfigProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs
Labels: ready-to-merge

#3209 Fix: Edgelet unable to pull using certain passwords - cherry-pick into 1.0.9. (#3206)
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
Labels: ready-to-merge

#3189 Enable twin encrypt by default
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/TwinStoreEntity.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/twin/TwinStoreEntityTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/DbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/DbStoreProviderDecorator.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IDbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/InMemoryDbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/StoreProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/EntityStoreTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/TestRocksDbStoreProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.Test/EntityStoreTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.Test/EntityStoreTestBase.cs
Labels: ready-to-merge

#3212 Enable twin encrypt by default (#3189)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/TwinStoreEntity.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/twin/TwinStoreEntityTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/DbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/DbStoreProviderDecorator.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IDbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/IStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/InMemoryDbStoreProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/StoreProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/EntityStoreTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/TestRocksDbStoreProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.Test/EntityStoreTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.Test/EntityStoreTestBase.cs
Labels: 1.0.10, ready-to-merge

#3200 Add watchdog to checkin and consolidate replicated files
  builds/checkin/edgelet.yaml
  builds/checkin/libiothsm.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/watchdog.yaml
  builds/ci/edgelet.yaml
  builds/ci/libiothsm.yaml
  builds/ci/mqtt.yaml
  builds/misc/images-release.yaml
  builds/misc/templates/image-linux-rust-jobs.yaml
  edge-hub/watchdog/build/clippy.sh
  edge-hub/watchdog/rust.toolchain
  edgelet/build/linux/build.sh
  edgelet/build/linux/format.sh
  edgelet/build/linux/install.sh
  scripts/linux/generic-rust/build.sh
  scripts/linux/generic-rust/format.sh
  scripts/linux/generic-rust/install.sh
Labels: ready-to-merge

#3214 Get cloud connection if adding device with subscriptions (#3201)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
Labels: 1.0.9

#3215 Get cloud connection if adding device with subscriptions (#3201)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/SessionStatePersistenceProvider.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
Labels: 1.0.10

#3133 Introduce CentOs7 to the new E2E test framework
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-clean-directory.yaml
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/IOsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/windows/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/BaseFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/DeviceProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
Labels: ready-to-merge

#3222 Introduce CentOs7 to the new E2E test framework
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-clean-directory.yaml
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/IOsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/windows/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/BaseFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/DeviceProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
Labels: ready-to-merge

#3218 [mqtt] Load server certificate on start in edgehub mode
  mqtt/Cargo.lock
  mqtt/mqtt-broker-core/src/auth/authorization.rs
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/config/default.json
  mqtt/mqtt-broker/config/with_tls.json
  mqtt/mqtt-broker/src/auth.rs
  mqtt/mqtt-broker/src/configuration/mod.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-broker/tests/common.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/edgelet/connect.rs
  mqtt/mqtt-edgehub/src/edgelet/mod.rs
  mqtt/mqtt-edgehub/src/edgelet/workload/client.rs
  mqtt/mqtt-edgehub/src/edgelet/workload/mod.rs
  mqtt/mqtt-edgehub/src/edgelet/workload/models.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-edgehub/src/tls.rs
  mqtt/mqtt-edgehub/test/tls/cert.pem
  mqtt/mqtt-edgehub/test/tls/pkey.pem
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
  mqtt/mqttd/src/broker/bootstrap/mod.rs
  mqtt/mqttd/src/broker/mod.rs
  mqtt/mqttd/src/broker/shutdown.rs
  mqtt/mqttd/src/broker/snapshot.rs
  mqtt/mqttd/src/lib.rs
  mqtt/mqttd/src/main.rs
Labels: area:mqtt, ready-to-merge

#3228 [mqtt] Remove reqwest dependency in favor of hyper
  mqtt/Cargo.lock
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/edgelet/mod.rs
  mqtt/mqtt-edgehub/src/edgelet/workload/client.rs
Labels: area:mqtt, ready-to-merge

#3216 [PnP] Add ModelIdStore for EdgeHub to store modelId per device identity
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ClientProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ClientTokenCloudConnection.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnection.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ConnectivityAwareClientProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/IClientProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/IModelIdStore.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ModelIdStore.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceIdentityProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ModelIdStoreTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/DeviceIdentityProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/IdentityTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/MqttWebSocketListenerTest.cs
Labels: ready-to-merge

#3210 Added bridge functionality to connect edgeHub and MQTT Broker
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IConnectionManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessorBase.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IConnectionRegistry.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IMessageConsumer.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IMessageProducer.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/ISystemComponentIdProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/MqttBridgeEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/MqttPublishInfo.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/SubscriptionPattern.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/SystemComponentIdProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentConstants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHeadConfig.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentStartup.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthRequest.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IComponentDiscovery.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerProtocolHeadConfig.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Cloud2DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/DirectMethodHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Interfaces/ICloud2DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Interfaces/IDirectMethodHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Interfaces/IModuleToModuleMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Interfaces/ISubscriptionChangeHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/Interfaces/ITwinHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/MessageConfirmingHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ModuleToModuleMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TelemetryHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TwinHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/MqttComponentDiscovery.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/AuthModule.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/SubscriptionProcessorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/Cloud2DeviceMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DeviceProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DirectMethodHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MessageConfirmingBase.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerProtocolHeadTests.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/SubscriptionChangeHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TelemetryHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TwinHandlerTest.cs
  mqtt/mqtt-edgehub/src/topic/translation.rs
Labels: ready-to-merge

#3231 [mqtt] Disable hyperlocal on windows
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/edgelet/connect.rs
  mqtt/mqtt-edgehub/src/edgelet/mod.rs
Labels: area:mqtt, ready-to-merge

#3238 [mqtt] Upgrade for rust 1.45
  mqtt/mqtt-broker/src/configuration.rs
  mqtt/mqtt-broker/tests/common.rs
  mqtt/rust-toolchain
Labels: area:mqtt, ready-to-merge

#3236 [mqtt]Add code for to renew expired cert in edgehub mode
  mqtt/mqtt-broker/config/with_tls.json
  mqtt/mqtt-edgehub/src/tls.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
  mqtt/mqttd/src/broker/bootstrap/mod.rs
  mqtt/mqttd/src/broker/mod.rs
Labels: area:mqtt, ready-to-merge

#3245 Prepare release1.0.9.4 (Update edgelet version)
  edgelet/version.txt
Labels: ready-to-merge

#3249 Broker workload client fixes
  mqtt/mqtt-edgehub/src/edgelet/workload/client.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: ready-to-merge

#3247 [k8s] Map docker "IpcMode" to k8s "HostIPC"
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/HostConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  kubernetes/doc/edge-deployment-to-k8s-translations.md
Labels: ready-to-merge

#3243 [mqtt] Make server certificate optional in config
  mqtt/Cargo.lock
  mqtt/mqtt-broker/src/configuration/mod.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/tls.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
Labels: area:mqtt, ready-to-merge

#3255 Fixing the port 443 on Connectivity, Stress, and Long Haul
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/stress_deployment.template.json
  e2e_deployment_files/stress_deployment.template.windows.json
Labels: ready-to-merge

#3262 Fix Rust Toolchain Version
  edgelet/rust-toolchain
Labels: ready-to-merge

#3239 make the broker send the current subscription list when a client connects
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/tests/translation.rs
Labels: area:edgehub, area:mqtt, ready-to-merge

#3202 Base image update for ARM32 and ARM64 platforms for security vulnerability [USN-4377-1]
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  scripts/linux/createArmBase.sh
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3244 Agent reported state as "406" when modules are in backoff.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
Labels: ready-to-merge

#3267 Unmap port 443 for Long Haul and Stress Tests
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/stress_deployment.template.json
  e2e_deployment_files/stress_deployment.template.windows.json
Labels: ready-to-merge

#3268 Fix clippy 1.45 suggestions for edgelet
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-core/src/watchdog.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-http-mgmt/src/client/module.rs
  edgelet/hsm-rs/src/crypto.rs
  edgelet/iotedge-proxy/src/routine.rs
  edgelet/iotedged/src/lib.rs
  edgelet/kube-client/src/client.rs
  edgelet/systemd/src/linux.rs
Labels: area:iotedged, ready-to-merge

#3266 Agent reported state as "406" when modules are in backoff. (#3244)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
Labels: 1.0.10, ready-to-merge

#3269 - Better exception handling if protocol heads cannot start
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
Labels: area:edgehub, area:mqtt, ready-to-merge

#3275 Allow features in rust checkin build script
  scripts/linux/generic-rust/build.sh
Labels: area:build, area:mqtt, ready-to-merge

#3276 [mqtt] Switch to openssl from native_tls
  mqtt/Cargo.lock
  mqtt/mqtt-broker-core/src/auth/authentication.rs
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/src/connection.rs
  mqtt/mqtt-broker/src/error.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/tls.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-broker/test/tls/cert.pem
  mqtt/mqtt-broker/test/tls/pkey.pem
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
Labels: area:mqtt, ready-to-merge

#3235 EdgeHub Build Fixes
  builds/misc/templates/consolidate-edgehub-artifacts.yaml
  edge-hub/docker/linux/amd64/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/watchdog/src/main.rs
  mqtt/contrib/edgehub/broker.json
  mqtt/mqtt-broker/config/production.json
Labels: ready-to-merge

#3281 Fix uri decoding in token authentication
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
Labels: ready-to-merge

#3286 changing authentication endpoint so it can accept pem encoded certificates
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
Labels: ready-to-merge

#3288 [mqtt] Read settings from ENV
  mqtt/contrib/edgehub/broker.json
  mqtt/mqtt-broker/src/tls.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-generic/src/settings.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
  scripts/linux/generic-rust/build.sh
Labels: area:mqtt, ready-to-merge

#3289 Update proj references for new NestedEdge SDK packages
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DeploymentTester/DeploymentTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TestAnalyzer/TestAnalyzer.csproj
  test/modules/TestResultCoordinator/TestResultCoordinator.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#3296 Disable schedule
  builds/misc/mqtt-perf.yaml
Labels: area:mqtt, ready-to-merge

#3237 Don't stage deployments
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeModule.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
Labels: ready-to-merge

#3297 MQTT Perf tests: Added missing -topics param for subscribers
  builds/misc/templates/mqtt-perf-test-case.yaml
Labels: area:mqtt, ready-to-merge

#3293 Refresh identities cache if edgeAgent/edgeHub has empty auth-type
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/DeviceScopeController.cs
Labels: ready-to-merge

#3294 Disable connection reauthenticator
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
Labels: area:edgehub, ready-to-merge

#3300 [mqtt] Fix broker server tracing span
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/connection.rs
  mqtt/mqtt-broker/src/persist.rs
  mqtt/mqtt-broker/src/server.rs
Labels: area:mqtt, ready-to-merge

#3301 [mqtt] Log message which was dropped due to queue limits
  mqtt/mqtt-broker/src/session/state/mod.rs
  mqtt/mqtt-broker/src/session/state/queue.rs
  mqtt/mqtt3/examples/publisher.rs
Labels: area:mqtt, ready-to-merge

#3304 fix subscription
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs
Labels: ready-to-merge

#3310 Fix sysinfo CPU issue
  edgelet/Cargo.lock
  edgelet/edgelet-docker/Cargo.toml
  edgelet/iotedge/Cargo.toml
Labels: ready-to-merge

#3299 Stop existing modules when iotedged starts
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-http-mgmt/src/client/module.rs
  edgelet/edgelet-kube/src/runtime.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedged/src/error.rs
  edgelet/iotedged/src/lib.rs
Labels: ready-to-merge

#3307 Ordered start for authentication and mqtt bridge
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/OrderedProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
Labels: area:mqtt, ready-to-merge

#3311 Fix DeviceScope API AuthN
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/DeviceScopeController.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
Labels: ready-to-merge

#3316 [PnP] ModuleClient test
  builds/e2e/templates/e2e-run.yaml
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceIdentityProvider.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
  test/connectivity/modules/NetworkController/Program.cs
  test/modules/DirectMethodReceiver/src/DirectMethodReceiver.cs
  test/modules/DirectMethodSender/DirectMethodLocalSender.cs
  test/modules/DirectMethodSender/ReporterClients/EventReporterClient.cs
  test/modules/EdgeHubRestartTester/src/Program.cs
  test/modules/MetricsValidator/src/Program.cs
  test/modules/ModuleLib/ModuleUtil.cs
  test/modules/Relayer/Program.cs
  test/modules/TemperatureFilter/Program.cs
  test/modules/TwinTester/Program.cs
  test/modules/load-gen/Program.cs
  test/modules/load-gen/Settings.cs
Labels: ready-to-merge

#3314 [mqtt] Refactor topic translation and remove mqtt-broker-core crate
  mqtt/Cargo.lock
  mqtt/Cargo.toml
  mqtt/mqtt-broker-core/Cargo.toml
  mqtt/mqtt-broker-core/src/lib.rs
  mqtt/mqtt-broker-tests-util/Cargo.toml
  mqtt/mqtt-broker-tests-util/src/lib.rs
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/benches/dispatch_messages.rs
  mqtt/mqtt-broker/benches/persist_broker_state.rs
  mqtt/mqtt-broker/src/auth/authentication.rs
  mqtt/mqtt-broker/src/auth/authorization.rs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/connection/mod.rs
  mqtt/mqtt-broker/src/connection/packet.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/session/connected.rs
  mqtt/mqtt-broker/src/session/disconnecting.rs
  mqtt/mqtt-broker/src/session/mod.rs
  mqtt/mqtt-broker/src/session/state/mod.rs
  mqtt/mqtt-broker/src/session/state/queue.rs
  mqtt/mqtt-broker/src/settings/mod.rs
  mqtt/mqtt-broker/src/settings/size.rs
  mqtt/mqtt-broker/src/snapshot.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-broker/tests/broker_model.rs
  mqtt/mqtt-broker/tests/persist_failpoints.rs
  mqtt/mqtt-broker/tests/smoke.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authentication/local.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authorization/local.rs
  mqtt/mqtt-edgehub/src/connection.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
  mqtt/mqtt-edgehub/tests/translation.rs
  mqtt/mqtt-generic/Cargo.toml
  mqtt/mqtt-generic/src/settings.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
Labels: area:mqtt, ready-to-merge

#3319 [mqtt] Add retry policy to authenticate client
  mqtt/Cargo.lock
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3274 Rename reboot order from `priority` to be `startupOrder`
  doc/ModuleStartupOrder.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/UnknownModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/RestartPlanner.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/ModuleSetTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/configsources/FileConfigSourceTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/planners/HealthRestartPlannerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerEnvironmentTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeHubDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/test-configs/module-priority-test-config.json
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/reporters/IoTHubReporterTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/planners/KubernetesPlannerTest.cs
Labels: ready-to-merge

#3333 Fix processed message priority for metrics (#3330)
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs
Labels: ready-to-merge

#3334 Fix triggers for iiot branches
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/libiothsm.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/watchdog.yaml
  builds/ci/dotnet.yaml
  builds/ci/edgelet.yaml
  builds/ci/libiothsm.yaml
  builds/ci/mqtt.yaml
  builds/e2e/e2e.yaml
  builds/misc/images-mqtt.yaml
  builds/misc/images.yaml
  builds/misc/packages.yaml
Labels: ready-to-merge
