Repository Azure/iotedge, pull requests merged in 2020-09, with the labels that each got.

#3462 Prepare E2E pipeline for ARM64 job
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
Labels: ready-to-merge

#3456 Update ARM32 & ARM64 base images to 3.1.7-bionic
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3476 Add sign method to mqtt edgelet client
  mqtt/edgelet-client/src/lib.rs
  mqtt/edgelet-client/src/workload/client.rs
  mqtt/edgelet-client/src/workload/models/mod.rs
  mqtt/edgelet-client/src/workload/models/sign_request.rs
Labels: area:mqtt

#3478 Update ARM32 base image to 2.1.21-bionic-arm32v7
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-modules/DirectMethodCloudSender/docker/linux/arm32v7/Dockerfile
  edge-modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  edge-modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  edge-modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  edge-modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  edge-modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  edge-modules/TwinTester/docker/linux/arm32v7/Dockerfile
  edge-modules/TwinTester/docker/linux/arm64v8/Dockerfile
  edge-modules/load-gen/docker/linux/arm32v7/Dockerfile
Labels: ready-to-merge

#3469 [mqtt] Improve sidecar startup and command handler error handling
  mqtt/mqtt-bridge/src/controller.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/command.rs
  mqtt/mqtt-edgehub/tests/command.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: ready-to-merge

#3490 Api proxy
  edge-modules/api-proxy-module/Cargo.toml
  edge-modules/api-proxy-module/build.sh
  edge-modules/api-proxy-module/docker/linux/aarch64/Dockerfile
  edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
  edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
  edge-modules/api-proxy-module/images/api-proxy-create-options.png
  edge-modules/api-proxy-module/images/api_proxy_module_design.png
  edge-modules/api-proxy-module/images/component_diagram_architecture_proposal.wsd
  edge-modules/api-proxy-module/images/concept.png
  edge-modules/api-proxy-module/images/set_env_var_local_registry.png
  edge-modules/api-proxy-module/images/set_env_var_no_local_registry.png
  edge-modules/api-proxy-module/makefile
  edge-modules/api-proxy-module/readme.md
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/Cargo.toml
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/LICENSE
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/README.md
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/device.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/io.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/iotedge_client.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/lib.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/module.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/system_properties.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/twin_state/desired.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/twin_state/mod.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/twin_state/reported.rs
  edge-modules/api-proxy-module/rust-sdk/hyper-uds/Cargo.toml
  edge-modules/api-proxy-module/rust-sdk/hyper-uds/LICENSE
  edge-modules/api-proxy-module/rust-sdk/hyper-uds/README.md
  edge-modules/api-proxy-module/rust-sdk/hyper-uds/src/lib.rs
  edge-modules/api-proxy-module/src/lib.rs
  edge-modules/api-proxy-module/src/main.rs
  edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
  edge-modules/api-proxy-module/src/monitors/config_monitor.rs
  edge-modules/api-proxy-module/src/monitors/file.rs
  edge-modules/api-proxy-module/src/monitors/mod.rs
  edge-modules/api-proxy-module/src/monitors/shutdown_handle.rs
  edge-modules/api-proxy-module/src/signals/mod.rs
  edge-modules/api-proxy-module/src/signals/shutdown.rs
  edge-modules/api-proxy-module/templates/nginx_default_config.conf
Labels: ready-to-merge

#3440 Update mqtt bridge to use common structs for upstream and remotes
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/config/default.json
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/controller.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/config.json
Labels: ready-to-merge

#3445 Histogram MaxAge is configurable and change default quantiles and only collect p90
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricTransformer.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/MetricsModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/MetricsConfig.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsHistogram.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsProvider.cs
Labels: ready-to-merge

#3486 Increase long haul log size for edgeAgent and edgeHub
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
Labels: ready-to-merge

#3501 Increase long haul log size for edgeAgent and edgeHub (#3486)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
Labels: ready-to-merge

#3502 Removed iotedge-diagnostics package (fix bad master merge)
  builds/checkin/edgelet.yaml
  builds/ci/edgelet.yaml
  edgelet/edgelet-http/src/authentication.rs
  edgelet/iotedge/src/check/checks/container_connect_iothub.rs
  edgelet/iotedge/src/check/checks/host_connect_iothub.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/mod.rs
Labels: ready-to-merge

#3500 Enable perf tests schedule back.
  builds/misc/mqtt-perf.yaml
Labels: ready-to-merge

#3503 [mqtt] CI fix
  builds/ci/mqtt.yaml
  scripts/linux/generic-rust/build.sh
Labels: ready-to-merge

#3504 Fix clean-up condition
  scripts/linux/runE2ETest.sh
Labels: ready-to-merge

#3495 Remove module user from diagnostics dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3508 Run some proptests only on 64bit platform.
  mqtt/mqtt-broker/src/settings/size.rs
Labels: ready-to-merge

#3509 One more quick fix for arm32 tests
  mqtt/mqtt-broker/src/settings/size.rs
Labels: ready-to-merge

#3507 Allow release image pipeline to use a custom CR
  builds/misc/images-release.yaml
Labels: ready-to-merge

#3512 Fixed merge conflicts
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  mqtt/Cargo.lock
Labels: ready-to-merge

#3515 ScopeIdentitiesHandler refactor
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
Labels: ready-to-merge

#3475 Policy engine core
  mqtt/Cargo.lock
  mqtt/Cargo.toml
  mqtt/policy/Cargo.toml
  mqtt/policy/examples/evaluate.rs
  mqtt/policy/src/core/builder.rs
  mqtt/policy/src/core/mod.rs
  mqtt/policy/src/errors.rs
  mqtt/policy/src/lib.rs
  mqtt/policy/src/matcher.rs
  mqtt/policy/src/substituter.rs
  mqtt/policy/src/validator.rs
Labels: area:mqtt, ready-to-merge

#3484 Prepare for release 1.0.9.5
  CHANGELOG.md
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#3474 Refactor Command handler and add handle_authorized_identities event
  mqtt/mqtt-broker/src/auth/authorization.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/command.rs
  mqtt/mqtt-edgehub/src/command_handler.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-edgehub/tests/command.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: ready-to-merge

#3523 [mqtt] Mitigate bad startup order
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: ready-to-merge

#3521 [mqtt] CI fix (#3503)
  builds/ci/mqtt.yaml
  edge-hub/watchdog/rust-toolchain
  edgelet/rust-toolchain
  mqtt/rust-toolchain
  scripts/linux/generic-rust/build.sh
Labels: ready-to-merge

#3482 Aggregate metrics before upload
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Metric.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/MetricTransformer.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/AggregationMetric.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/AggregationTemplate.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/Aggregators.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/IAggregator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/MetricAggregator.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/MetricsAggregatorTest.cs
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/DefaultDictionary.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/CollectionExTest.cs
  netstandardVersion.props
Labels: ready-to-merge

#3525 Update Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj config attribute
  doc/images/nugetIcon.png
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
Labels: ready-to-merge

#3531 Run some proptests only on 64bit platform
  mqtt/mqtt-broker/src/settings/size.rs
Labels: ready-to-merge

#3536 Handle Close requests for clients and send disconnect signal to broker
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IConnectionRegistry.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionHandlerTests.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DeviceProxyTest.cs
  mqtt/mqtt-edgehub/src/command.rs
Labels: ready-to-merge

#3537 fixed recognizing system components to ignore their messages
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/ISystemComponentIdProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/SystemComponentIdProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
Labels: ready-to-merge

#3513 [mqtt] Make external transport to await until broker is ready to serve clients
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-broker/src/error.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/tls.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
Labels: area:mqtt, ready-to-merge

#3435 Add `always_reprovision_on_startup` setting to DPS provisioning configuration
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/windows/config.yaml
  edgelet/edgelet-core/src/settings.rs
  edgelet/iotedged/src/lib.rs
  edgelet/provisioning/src/provisioning.rs
  scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Labels: ready-to-merge

#3541 Policy engine enhancements
  mqtt/policy/src/core/builder.rs
  mqtt/policy/src/core/mod.rs
  mqtt/policy/src/lib.rs
  mqtt/policy/src/matcher.rs
  mqtt/policy/src/substituter.rs
  mqtt/policy/src/validator.rs
Labels: area:mqtt, ready-to-merge

#3405 Fix edgeHub restart by supporting version
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeAgentDockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerRuntimeModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeHubDockerRuntimeModuleTest.cs
Labels: ready-to-merge

#3542 [mqtt] Refactor command handler
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-broker/src/auth/authentication.rs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-broker/src/connection/mod.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authentication/local.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authorization/mod.rs
  mqtt/mqtt-edgehub/src/auth/mod.rs
  mqtt/mqtt-edgehub/src/command.rs
  mqtt/mqtt-edgehub/src/command/authorized_identities.rs
  mqtt/mqtt-edgehub/src/command/disconnect.rs
  mqtt/mqtt-edgehub/src/command/handler.rs
  mqtt/mqtt-edgehub/src/command/mod.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-edgehub/tests/command.rs
  mqtt/mqtt-edgehub/tests/translation.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
Labels: area:mqtt, ready-to-merge

#3548 Not exposing Version in JSON
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeAgentDockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerRuntimeModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeHubDockerRuntimeModuleTest.cs
Labels: ready-to-merge

#3544 Add `always_reprovision_on_startup` setting to DPS provisioning configuration
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/windows/config.yaml
  edgelet/edgelet-core/src/settings.rs
  edgelet/iotedged/src/lib.rs
  edgelet/provisioning/src/provisioning.rs
  scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Labels: ready-to-merge

#3554 Remove `version` from GetHash for EdgeAgentDockerModule
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeAgentDockerModule.cs
Labels: ready-to-merge

#3556 Fix edgeHub stuck in a restart loop when `version` is specified
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeAgentDockerModule.cs
Labels: ready-to-merge

#3226 Content Trust via Notary
  doc/NotaryContentTrust.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/CombinedDockerConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerEnvironmentTest.cs
  edgelet/Cargo.lock
  edgelet/contrib/config/linux/config.yaml
  edgelet/edgelet-docker/Cargo.toml
  edgelet/edgelet-docker/src/config.rs
  edgelet/edgelet-docker/src/error.rs
  edgelet/edgelet-docker/src/lib.rs
  edgelet/edgelet-docker/src/module.rs
  edgelet/edgelet-docker/src/notary.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-docker/test/linux/bad_settings_content_trust.yaml
  edgelet/edgelet-docker/test/linux/sample_settings_content_trust.yaml
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-kube/src/convert/to_docker.rs
  edgelet/edgelet-kube/src/convert/to_k8s.rs
  edgelet/edgelet-kube/src/module/create.rs
  edgelet/edgelet-kube/src/registry/pull.rs
  edgelet/iotedged/src/lib.rs
Labels: ready-to-merge

#3558 Remove potentially non-useful metrics from RQT
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/SystemResourcesMetrics.cs
Labels: ready-to-merge

#3546 Restore CentOS7 E2E Tests
  builds/e2e/e2e.yaml
Labels: ready-to-merge

#3543 Report provisioning type in metrics
  doc/BuiltInMetrics.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/ProvisioningInfo.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/SystemInfo.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs
  edgelet/api/managementVersion_2020_07_07.yaml
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-kube/src/runtime.rs
  edgelet/edgelet-test-utils/src/module.rs
Labels: ready-to-merge

#3559 Enable connectivity test for nested edge scenario
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/Quickstart.cs
  smoke/IotEdgeQuickstart/details/Details.cs
  smoke/IotEdgeQuickstart/details/IBootstrapper.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#3565 Update connectivity test for nested edge
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#3568 Add edgeHub moduleId to RoutingEdgeHub to fix message source bug
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingEdgeHubTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
Labels: ready-to-merge

#3534 Batch rqt upload
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/publisher/EdgeRuntimeDiagnosticsUpload.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/IEdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/IModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/ISdkModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/publisher/EdgeRuntimeDiagnosticsUploadTest.cs
Labels: ready-to-merge

#3574 Fix for wsl2
  scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Labels: ready-to-merge

#3540 mqtt bridge connect to local broker and upstream to receive messages
  mqtt/Cargo.lock
  mqtt/edgelet-client/Cargo.toml
  mqtt/edgelet-client/src/lib.rs
  mqtt/edgelet-client/src/workload/client.rs
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/controller.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/persist/memory/loader.rs
  mqtt/mqtt-bridge/src/persist/memory/mod.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/src/token_source.rs
  mqtt/mqtt-bridge/tests/config.json
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt

#3580 Expanding the Prometheus metric parser
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/PrometheusMetricsParser.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/PrometheousMetricsParserTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/PrometheusMetricsParserTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/TimeSeriesHelperTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/Metrics.cs
Labels: ready-to-merge

#3584 Expanding the Prometheus metric parser (#3580)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsScraper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/PrometheusMetricsParser.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/PrometheousMetricsParserTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/PrometheusMetricsParserTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/TimeSeriesHelperTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/Metrics.cs
Labels: ready-to-merge

#3591 Connectivity test in Nested Edge Environment
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/Quickstart.cs
  smoke/IotEdgeQuickstart/details/Details.cs
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#3587 Histogram MaxAge is configurable and change default quantiles and onl…
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricTransformer.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/MetricsModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/MetricsConfig.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsHistogram.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsProvider.cs
Labels: ready-to-merge

#3586 Some enhancements to the validation errors
  mqtt/Cargo.lock
  mqtt/policy/src/core/builder.rs
  mqtt/policy/src/errors.rs
  mqtt/policy/src/matcher.rs
  mqtt/policy/src/validator.rs
Labels: area:mqtt, ready-to-merge

#3588 Remove module user from diagnostics dockerfile (#3495)
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3582 Setup Nested Edge E2E Test pipline
  builds/e2e/nested-e2e.yaml
Labels: ready-to-merge

#3589 Aggregate metrics before upload (#3482)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Metric.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/MetricTransformer.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/AggregationMetric.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/AggregationTemplate.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/Aggregators.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/IAggregator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/util/aggregation/MetricAggregator.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/util/MetricsAggregatorTest.cs
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/DefaultDictionary.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/CollectionExTest.cs
  netstandardVersion.props
Labels: ready-to-merge

#3590 Batch rqt upload (#3534)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/publisher/EdgeRuntimeDiagnosticsUpload.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/IEdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/IModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/ISdkModuleClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/sdkClient/WrappingSdkModuleClient.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/publisher/EdgeRuntimeDiagnosticsUploadTest.cs
Labels: ready-to-merge

#3583 Fix check in support bundle
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#3593 Added mqtt-policy crate
  mqtt/Cargo.lock
  mqtt/Cargo.toml
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/src/auth/authorization.rs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-policy/Cargo.toml
  mqtt/mqtt-policy/src/errors.rs
  mqtt/mqtt-policy/src/lib.rs
  mqtt/mqtt-policy/src/matcher.rs
  mqtt/mqtt-policy/src/substituter.rs
  mqtt/mqtt-policy/src/validator.rs
Labels: area:mqtt, ready-to-merge

#3603 Fix test device parent scopes
  smoke/IotEdgeQuickstart/details/Details.cs
Labels: ready-to-merge

#3609 Fixing CI SchemaVersion
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Labels: ready-to-merge

#3561 Put limits on rqt data upload
  CodeCoverage.runsettings
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/DiagnosticConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/storage/MetricsStorage.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/DiagnosticsModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
Labels: ready-to-merge

#3605 [mqtt] Publication delivery confirmation topic for M2M messages
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-broker/src/auth/authentication.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/connection/mod.rs
  mqtt/mqtt-broker/src/connection/packet.rs
  mqtt/mqtt-broker/src/error.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/command/disconnect.rs
  mqtt/mqtt-edgehub/src/connection.rs
  mqtt/mqtt-edgehub/src/connection/delivery.rs
  mqtt/mqtt-edgehub/src/connection/mod.rs
  mqtt/mqtt-edgehub/src/connection/translate.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
  mqtt/mqtt-edgehub/tests/delivery.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3549 [mqtt] RocksDB Persistence
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/memory/mod.rs
  mqtt/mqtt-bridge/src/persist/memory/waking_map.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/persist/publication_store.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory.rs
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/rocksdb.rs
Labels: area:mqtt

#3572 [1.0.10] Set up edgeAgent container to run agent as non-root.
  edge-agent/docker/linux/amd64/Dockerfile
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-agent/docker/windows/amd64/Dockerfile
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Microsoft.Azure.Devices.Edge.Agent.Service.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/agentStart.sh
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/MetricsListenerConfig.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/prometheus.net/MetricsListener.cs
Labels: 1.0.10, area:edgeagent, ready-to-merge

#3631 Revert "[mqtt] RocksDB Persistence (#3549)"
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/persist/memory/loader.rs
  mqtt/mqtt-bridge/src/persist/memory/mod.rs
  mqtt/mqtt-bridge/src/persist/memory/waking_map.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/persist/publication_store.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory.rs
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/rocksdb.rs
Labels: ready-to-merge

#3630 Put limits on rqt data upload (#3561)
  CodeCoverage.runsettings
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/DiagnosticConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/storage/MetricsStorage.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/DiagnosticsModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
Labels: ready-to-merge

#3629 Check DPS provisioning gets hubname (#3432)
  edgelet/Cargo.lock
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/check/checks/well_formed_connection_string.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/provisioning/src/lib.rs
  edgelet/provisioning/src/provisioning.rs
Labels: ready-to-merge

#3633 Fix for wsl2 (#3574)
  scripts/windows/setup/IotEdgeSecurityDaemon.ps1
Labels: ready-to-merge

#3597 Mqtt bridge upstream connection
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/config/default.json
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/controller.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/src/token_source.rs
  mqtt/mqtt-bridge/tests/config.json
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/command/handler.rs
  mqtt/mqtt3/src/client/mod.rs
  mqtt/mqtt3/src/client/subscriptions.rs
  mqtt/mqtt3/tests/subscriptions.rs
Labels: area:mqtt, ready-to-merge

#3625 Using self-host Windows Agent for E2E test framework
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
Labels: ready-to-merge

#3614 Integrate policy engine into MQTT Broker
  mqtt/Cargo.lock
  mqtt/mqtt-broker/src/auth/authorization.rs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/proptest.rs
  mqtt/mqtt-broker/src/subscription.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/auth/authentication/local.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/auth/authorization/local.rs
  mqtt/mqtt-edgehub/src/auth/authorization/mod.rs
  mqtt/mqtt-edgehub/src/auth/authorization/policy.rs
  mqtt/mqtt-edgehub/src/auth/mod.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: ready-to-merge

#3628 Fix check in support bundle (#3583)
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge
