Repository Azure/iotedge, pull requests merged in 2020-11, with the labels that each got.

#3868 Test e2e fix (#3785)
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/README.md
Labels: ready-to-merge

#3865 Fix subscription issues
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
Labels: area:mqtt

#3871 Fix iotedge check for http endpoints
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
Labels: ready-to-merge

#3870 [mqtt] Make rpc local handler to process rpc topic subscription update
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
Labels: area:mqtt, ready-to-merge

#3872 Fix subscription issues (#3865)
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
Labels: ready-to-merge

#3876 fix: don't delete indirect client connections on broker connected events
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/IDeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
Labels: ready-to-merge

#3877 [mqtt] Make rpc local handler to process rpc topic subscription update (#3870)
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
Labels: area:mqtt, ready-to-merge

#3874 Fixed on-behalf-of authorization
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3879 Fixed on-behalf-of authorization (#3874)
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3873 Fix MQTT broker feature flags for ARM
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/watchdog/src/main.rs
Labels: ready-to-merge

#3875 Check fix 110
  edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
Labels: ready-to-merge

#3878 remove early break from subscription processing
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
Labels: ready-to-merge

#3880 Fix MQTT broker feature flags for ARM (#3873)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/watchdog/src/main.rs
Labels: ready-to-merge

#3862 [mqtt] App bootstrap and sidecars
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/controller/mod.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
  mqtt/mqtt-bridge/src/pump/ingress.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/sidecar.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-edgehub/src/command/bridge_update.rs
  mqtt/mqtt-edgehub/src/command/handler.rs
  mqtt/mqtt-edgehub/tests/common/mod.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/app/generic.rs
  mqtt/mqttd/src/app/mod.rs
  mqtt/mqttd/src/app/shutdown.rs
  mqtt/mqttd/src/app/snapshot.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
  mqtt/mqttd/src/broker/bootstrap/mod.rs
  mqtt/mqttd/src/broker/bootstrap/server.rs
  mqtt/mqttd/src/broker/mod.rs
  mqtt/mqttd/src/lib.rs
  mqtt/mqttd/src/main.rs
Labels: area:mqtt, ready-to-merge

#3883 [mqtt] App bootstrap and sidecars (#3862)
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/controller/mod.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
  mqtt/mqtt-bridge/src/pump/ingress.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/sidecar.rs
  mqtt/mqtt-broker/src/transport.rs
  mqtt/mqtt-edgehub/src/command/bridge_update.rs
  mqtt/mqtt-edgehub/src/command/handler.rs
  mqtt/mqtt-edgehub/tests/common/mod.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/app/generic.rs
  mqtt/mqttd/src/app/mod.rs
  mqtt/mqttd/src/app/shutdown.rs
  mqtt/mqttd/src/app/snapshot.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
  mqtt/mqttd/src/broker/bootstrap/generic.rs
  mqtt/mqttd/src/broker/bootstrap/mod.rs
  mqtt/mqttd/src/broker/bootstrap/server.rs
  mqtt/mqttd/src/broker/mod.rs
  mqtt/mqttd/src/lib.rs
  mqtt/mqttd/src/main.rs
Labels: area:mqtt, ready-to-merge

#3809 Fix first test intermittent failure on Pi
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test/helpers/BaseFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/CustomCertificatesFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
Labels: ready-to-merge

#3882 fix: subscriptions get ignored and deleting indirect connections
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/IDeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
Labels: ready-to-merge

#3884 Cherry pick from master to release 1.2
  edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
  edge-modules/api-proxy-module/readme.md
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/device.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/module.rs
  edge-modules/api-proxy-module/src/main.rs
  edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
  edge-modules/api-proxy-module/src/monitors/config_monitor.rs
  edge-modules/api-proxy-module/templates/nginx_default_config.conf
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_connect_upstream.rs
  edgelet/iotedge/src/check/checks/container_local_time.rs
  edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
  edgelet/iotedge/src/check/checks/host_connect_upstream.rs
  edgelet/iotedge/src/check/checks/pull_agent_from_upstream.rs
Labels: ready-to-merge

#3887 Broker config must be sent as a retained message.
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/BrokerConfigUpdateHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/Cloud2DeviceMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionHandlerTests.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DirectMethodHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MessageConfirmingBase.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TwinHandlerTest.cs
  mqtt/mqtt-edgehub/tests/authorization.rs
Labels: ready-to-merge

#3890 Broker config must be sent as a retained message. (#3887)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/BrokerConfigUpdateHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/Cloud2DeviceMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionHandlerTests.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/DirectMethodHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MessageConfirmingBase.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/TwinHandlerTest.cs
  mqtt/mqtt-edgehub/tests/authorization.rs
Labels: ready-to-merge

#3893 bridge topics fix when inPrefix or outPrefix are empty
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/config.json
Labels: ready-to-merge

#3891 Send subscriptions updates (#3869)
  mqtt/mqtt3/src/client/subscriptions.rs
  mqtt/mqtt3/tests/subscriptions.rs
Labels: ready-to-merge

#3892 Construct valid auth-chains for children for non-nested mode
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
Labels: ready-to-merge

#3894 fixed direct method calls for modules
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
Labels: ready-to-merge

#3895 Construct valid auth-chains for children for non-nested mode (#3892)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
Labels: ready-to-merge

#3896 Fixed direct methods for modules
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
Labels: ready-to-merge

#3897 [mqtt] Fix certificate renewal timer
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/lib.rs
  mqtt/mqttd/src/time.rs
Labels: area:mqtt, ready-to-merge

#3899 [mqtt] Fix certificate renewal timer (#3897)
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/lib.rs
  mqtt/mqttd/src/time.rs
Labels: area:mqtt, ready-to-merge

#3842 Arm32/64 base image update for security vulnerability
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3859 1.0.10: Arm32/Arm64 base image update
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3901 Fix first test intermittent failure on Pi
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test/helpers/BaseFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/CustomCertificatesFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
Labels: ready-to-merge

#3902 Added more EdgeHubAuthorizer tests.
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3905 Speedup persist proptest
  mqtt/mqtt-broker/src/persist.rs
  mqtt/mqtt-broker/src/proptest.rs
  mqtt/mqtt-broker/src/session/identifiers.rs
Labels: area:mqtt, ready-to-merge

#3910 bridge topics fix when inPrefix or outPrefix are empty (#3893)
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/config.json
Labels: ready-to-merge

#3917 Fix CHANGELOG formatting error
  CHANGELOG.md
Labels: ready-to-merge

#3918 Minor logging improvements for auth and identities cache (#3913)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Labels: ready-to-merge

#3916 mqtt broker align env variables
  mqtt/mqtt-edgehub/src/settings.rs
Labels: ready-to-merge

#3922 mqtt broker align env variables (#3916)
  mqtt/mqtt-edgehub/src/settings.rs
Labels: ready-to-merge

#3920 Prepare for 1.2.0-rc1 release
  CHANGELOG.md
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#3789 Added policy e2e tests.
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BrokerProperties.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
Labels: ready-to-merge

#3925 Remove module SAS keys from RegistryController logs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
Labels: ready-to-merge

#3931 Remove module SAS keys from RegistryController logs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
Labels: ready-to-merge

#3860 Guidance for base image updates
  scripts/linux/createArmBase.sh
Labels: ready-to-merge

#3938 Fixed an issue where not all variable rules are evaluated
  mqtt/policy/src/core/mod.rs
Labels: area:mqtt, ready-to-merge

#3945 MQTT: Use FQN for the authenticated identity
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqttd/src/app/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3944 Fixing edgeAgent_created_pids_total for ValidateMetric
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#3950 Fix Linux Check
  edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
Labels: ready-to-merge

#3951 Fix TestUpload* E2E tests
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/README.md
Labels: ready-to-merge

#3953 Fixing edgeAgent_created_pids_total for ValidateMetric (#3944)
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#3954 Fixing edgeAgent_created_pids_total for ValidateMetric (#3944)
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#3834 Recognize the new DPS registration substatus that indicates cloud identity did not change.
  edgelet/dps/src/dps.rs
  edgelet/dps/src/lib.rs
  edgelet/dps/src/registration.rs
  edgelet/provisioning/src/provisioning.rs
Labels: ready-to-merge

#3831 Update deployment manifests
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/nested_connectivity_deployment.template.json
  e2e_deployment_files/nested_long_haul_deployment.template.json
  test/modules/EdgeHubRestartTester/docker/linux/amd64/Dockerfile
Labels: ready-to-merge

#3955 Prepare for release 1.0.10.2
  CHANGELOG.md
  edgelet/version.txt
Labels: ready-to-merge

#3952 Auto trigger api-proxy Checkin
  builds/checkin/api-proxy.yaml
Labels: ready-to-merge

#3946 Remove "precondition" task in checkin pipelines in favor of native filter
  builds/checkin/api-proxy.yaml
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/libiothsm.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/watchdog.yaml
Labels: ready-to-merge

#3958 Revert "Remove "precondition" task in checkin pipelines in favor of native filter (#3946)"
  builds/checkin/api-proxy.yaml
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/libiothsm.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/watchdog.yaml
Labels: ready-to-merge

#3961 Enable topic translation tests
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/tests/translation.rs
Labels: area:mqtt, ready-to-merge

#3960 Improving M2M feedback handling
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/ModuleToModuleResponseTimeout.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ModuleToModuleMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/connection/delivery.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqtt-edgehub/tests/delivery.rs
Labels: ready-to-merge

#3964 Improving M2M feedback handling (#3960)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/ModuleToModuleResponseTimeout.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ModuleToModuleMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ModuleToModuleMessageHandlerTest.cs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/src/connection/delivery.rs
  mqtt/mqtt-edgehub/src/topic/translation.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqtt-edgehub/tests/delivery.rs
Labels: ready-to-merge

#3962 Fixed an issue where not all variable rules are evaluated (#3938)
  mqtt/policy/src/core/mod.rs
Labels: area:mqtt, ready-to-merge

#3963 Added more EdgeHubAuthorizer tests. (#3902)
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3966 Enable topic translation tests (#3961)
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/tests/translation.rs
Labels: area:mqtt, ready-to-merge

#3967 Fixed m2m authz tests
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3968 Fixed m2m authz tests (#3967)
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3970 Fixed e2e tests after recent changes
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
Labels: ready-to-merge

#3971 MQTT: Use FQN for the authenticated identity (#3945)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentController.cs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-edgehub/src/auth/authorization/edgehub.rs
  mqtt/mqtt-edgehub/tests/authorization.rs
  mqtt/mqttd/src/app/edgehub.rs
Labels: ready-to-merge

#3975 Arm32/64 base image update for security vulnerability (#3842)
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3972 Added Publish Test Results task to MQTT Pipelines + other pipeline improvements
  builds/checkin/mqtt.yaml
  builds/ci/mqtt.yaml
  mqtt/build/linux/test.sh
Labels: area:mqtt, ready-to-merge

#3978 Update ARM base images to 3.1.10-bionic
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3979 Update ARM base image to 3.1.10-bionic
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3977 Update ARM base images to 3.1.10-bionic
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3969 Added policy authorizer integration tests
  mqtt/mqtt-edgehub/src/auth/authorization/policy.rs
  mqtt/mqtt-edgehub/src/command/mod.rs
  mqtt/mqtt-edgehub/src/command/policy_update.rs
  mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs
  mqtt/mqtt-edgehub/tests/policy_authorizer.rs
Labels: area:mqtt, ready-to-merge

#3908 GetModuleLogs works with http endpoints
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
Labels: ready-to-merge

#3983 MQTT Authz: Reduce test flakiness
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-edgehub/tests/common/mod.rs
  mqtt/mqtt-edgehub/tests/edgehub_authorizer.rs
  mqtt/mqtt-edgehub/tests/policy_authorizer.rs
Labels: area:mqtt, ready-to-merge

#3987 Prepare for release 1.0.10.3
  CHANGELOG.md
  versionInfo.json
Labels: ready-to-merge

#3984 Disable e2e tests
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Labels: ready-to-merge

#3988 Try to stabilize policy engine e2e tests.
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
Labels: ready-to-merge

#3985 Policy engine proptests
  mqtt/Cargo.lock
  mqtt/policy/Cargo.toml
  mqtt/policy/src/core/builder.rs
  mqtt/policy/src/core/mod.rs
  mqtt/policy/src/lib.rs
Labels: area:mqtt, ready-to-merge

#3997 [mqtt] make clippy happy after rust 1.48 release
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-bridge/src/upstream/rpc/mod.rs
  mqtt/mqtt-broker/src/auth/mod.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/error.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/settings/size.rs
  mqtt/mqtt-broker/src/snapshot.rs
  mqtt/mqtt3/src/lib.rs
Labels: area:mqtt, ready-to-merge

#3992 Policy engine: getting rid of EffectImpl
  mqtt/policy/src/core/builder.rs
  mqtt/policy/src/core/mod.rs
Labels: area:mqtt, ready-to-merge

#3995 Try to stabilize policy e2e tests.
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
Labels: ready-to-merge

#3996 Add CredScan suppressions
  .config/CredScanSuppressions.json
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/ImagePullSecretTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
Labels: ready-to-merge

#3999 Reduce mutability in the broker
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/connection/mod.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/session/connected.rs
  mqtt/mqtt-broker/src/session/disconnecting.rs
  mqtt/mqtt-broker/src/session/mod.rs
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/app/snapshot.rs
Labels: area:mqtt, ready-to-merge

#4002 Pin Rust version to 1.47.0
  edgelet/rust-toolchain
Labels: ready-to-merge

#4001 Pin Rust version to 1.47.0
  edgelet/rust-toolchain
Labels: ready-to-merge

#4014 Prevent stackflow when syncing circularly nested hierarchies
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Labels: ready-to-merge

#4006 Drop session on re-authorize
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/tests/compliance.rs
  mqtt/mqtt-broker/tests/integration.rs
Labels: area:mqtt, ready-to-merge

#3990 GetModuleLogs works with http endpoints (#3908)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
Labels: ready-to-merge

#4029 Fixing ValidateMetrics E2E (#3767)
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#3998 Extract client io object creation from bridge into mqtt-util crate
  mqtt/Cargo.lock
  mqtt/Cargo.toml
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/controller/bridges.rs
  mqtt/mqtt-bridge/src/controller/mod.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/src/token_source.rs
  mqtt/mqtt-util/Cargo.toml
  mqtt/mqtt-util/src/client_io.rs
  mqtt/mqtt-util/src/lib.rs
Labels: area:mqtt

#3991 outPrefix and inPrefix None when empty string
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
Labels: ready-to-merge

#4008 Re-enable non-flaky tests
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
Labels: ready-to-merge

#4019 Session cleanup for expired offline sessions
  mqtt/Cargo.lock
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/persist.rs
  mqtt/mqtt-broker/src/proptest.rs
  mqtt/mqtt-broker/src/session/connected.rs
  mqtt/mqtt-broker/src/session/mod.rs
  mqtt/mqtt-broker/src/session/offline.rs
  mqtt/mqtt-broker/src/session/state/mod.rs
  mqtt/mqtt-broker/src/settings/mod.rs
  mqtt/mqtt-broker/src/snapshot.rs
  mqtt/mqtt-broker/src/state_change.rs
  mqtt/mqtt-broker/tests/broker_model.rs
  mqtt/mqtt-broker/tests/integration.rs
  mqtt/mqtt-edgehub/config/default.json
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-generic/config/default.json
  mqtt/mqtt-generic/src/settings.rs
  mqtt/mqttd/src/app/cleanup.rs
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/app/generic.rs
  mqtt/mqttd/src/app/mod.rs
  mqtt/mqttd/src/app/snapshot.rs
Labels: area:mqtt, ready-to-merge
