Repository Azure/iotedge, pull requests merged in 2020-02, with the labels that each got.

#2444 Cherrypick metrics fixes for rc5
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/MetricsCommandFactory.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/models/DockerStats.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/SystemResourcesMetrics.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ModuleMessageLinkHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/MessageHelper.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MessagingServiceClient.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyUnitTest.cs
  edgelet/edgelet-docker/src/runtime.rs
Labels: 1.0.9

#2454 Update SDK on 1.0.9 branch
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/DirectMethodCloudSender/DirectMethodCloudSender.csproj
  edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  edge-modules/DirectMethodSender/DirectMethodSender.csproj
  edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  edge-modules/ModuleRestarter/ModuleRestarter.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/TemperatureFilter/TemperatureFilter.csproj
  edge-modules/TestAnalyzer/TestAnalyzer.csproj
  edge-modules/TwinTester/TwinTester.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-modules/load-gen/load-gen.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
Labels: 1.0.9

#2456 Big numbers make Helm convert to scientific notation,
  kubernetes/charts/edge-kubernetes/templates/_helpers.tpl
Labels: ready-to-merge

#2457 [k8s][Helm] Big numbers make Helm convert to scientific notation, (#2456)
  kubernetes/charts/edge-kubernetes/templates/_helpers.tpl
Labels: ready-to-merge

#2451 Validate used RAM metric
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/MetricsCommandFactory.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/DurationMeasurer.cs
  test/modules/MetricsValidator/src/Program.cs
  test/modules/MetricsValidator/src/TestReporter.cs
  test/modules/MetricsValidator/src/tests/ValidateHostRanges.cs
Labels: ready-to-merge

#2462 troubleshooting connectivity test
  builds/e2e/connectivity.yaml
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#2430 Metrics Collector: Use iot hub rather than event hub for enum uploadTarget
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/publisher/IotHubMetricsUpload.cs
  edge-modules/MetricsCollector/Program.cs
  edge-modules/MetricsCollector/Settings.cs
  edge-modules/MetricsCollector/config/settings.json
Labels: ready-to-merge

#2461 Added config variable to turn on AMQP heartbeat in Agent to mitigate reconnect time
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleClientProviderTest.cs
Labels: ready-to-merge

#2465 Added AMQP idle timeout to EdgeHub to mitigate reconnection time
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
Labels: ready-to-merge

#2448 E2E: Support windows arm32
  scripts/linux/runE2ETest.sh
  scripts/windows/test/Run-E2ETest.ps1
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/Quickstart.cs
  smoke/IotEdgeQuickstart/details/Details.cs
  smoke/IotEdgeQuickstart/details/IBootstrapper.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
Labels: ready-to-merge

#2466 Remove old "CodeCoverage" boilerplate from csproj files
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
Labels: ready-to-merge

#2473 AMQP heartbeat feature for EdgeHub
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
Labels: ready-to-merge

#2475 AMQP heartbeat feature for EdgeAgent
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/EdgeletModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleClientProviderTest.cs
Labels: ready-to-merge

#2413 EdgeHub Restart Tester (Sender)
  Microsoft.Azure.Devices.Edge.sln
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  builds/misc/images.yaml
  e2e_deployment_files/edgehub_restart_deployment.template.json
  scripts/linux/buildBranch.sh
  scripts/windows/build/Publish-Branch.ps1
  test/connectivity/scripts/connectivityTest.sh
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/EdgeHubRestartTester/config/settings.json
  test/modules/EdgeHubRestartTester/docker/linux/amd64/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/windows/amd64/Dockerfile
  test/modules/EdgeHubRestartTester/docker/windows/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/src/DirectMethodEdgeHubConnector.cs
  test/modules/EdgeHubRestartTester/src/IEdgeHubConnector.cs
  test/modules/EdgeHubRestartTester/src/MessageEdgeHubConnector.cs
  test/modules/EdgeHubRestartTester/src/Program.cs
  test/modules/EdgeHubRestartTester/src/Settings.cs
  test/modules/ModuleLib/ModuleUtil.cs
  test/modules/ModuleLib/TestOperationResultType.cs
  test/modules/ModuleLib/TestResults/DirectMethodTestResult.cs
  test/modules/ModuleLib/TestResults/EdgeHubRestartDirectMethodResult.cs
  test/modules/ModuleLib/TestResults/EdgeHubRestartMessageResult.cs
  test/modules/ModuleLib/TestResults/MessageTestResult.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/DirectMethodReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/TestReportType.cs
  test/modules/TestResultCoordinator/Settings.cs
Labels: ready-to-merge

#2350 Azure/iotedge issue #2306 - cleanup /var/lib/iotedge
  edgelet/contrib/debian/dirs
  edgelet/contrib/debian/postinst
  edgelet/contrib/debian/postrm
  edgelet/contrib/debian8/postinst
  edgelet/contrib/debian8/postrm
Labels: ready-to-merge

#2428 Update edgelet devguide.
  edgelet/doc/devguide.md
Labels: ready-to-merge

#2484 fixed mqtt/amqp transport setting mismatch for agent
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
Labels: ready-to-merge

#2485 fixed amqp/mqtt transport settings mismatch
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
Labels: ready-to-merge

#2487 `Iotedge check` - Time drift overreporting fix
  edgelet/iotedge/src/check/checks/container_local_time.rs
Labels: ready-to-merge

#2463 Fixing c2d amqp receiver
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs
Labels: ready-to-merge

#2483 Support custom edge runtime in connectivity test
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#2491 Exclude new test module from code coverage
  CodeCoverage.runsettings
Labels: ready-to-merge

#2493 Fix exit code
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#2477 Update IotEdgeSecurityDaemon.ps1
  smoke/IotEdgeQuickstart/details/Process.cs
  smoke/LeafDevice/details/Process.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/Process.cs
Labels: ready-to-merge

#2502 Kodiak: disable automerge without ready-to-merge label
  .github/.kodiak.toml
Labels: ready-to-merge

#2501 Change DPS provisioning check error to warning
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
  edgelet/iotedge/src/check/checks/well_formed_connection_string.rs
  edgelet/iotedge/src/check/mod.rs
Labels: ready-to-merge

#2503 Fix formatting in proxy.md
  builds/e2e/proxy.md
Labels: ready-to-merge

#2508 Getting rid of unused property in NetworkController
  test/connectivity/modules/NetworkController/Program.cs
  test/connectivity/modules/NetworkController/Settings.cs
Labels: ready-to-merge

#2499 Make logs upload method since take relative times
  doc/built-in-logs-pull.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesRuntimeInfoProviderTest.cs
  edgelet/Cargo.lock
  edgelet/api/managementVersion_2019_11_05.yaml
  edgelet/edgelet-core/Cargo.toml
  edgelet/edgelet-core/src/error.rs
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/parse_since.rs
  edgelet/edgelet-http-mgmt/src/server/module/logs.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#2505 Add build number in test summary
  e2e_deployment_files/connectivity_deployment.template.json
  test/connectivity/scripts/connectivityTest.sh
  test/modules/TestResultCoordinator/Reports/TestSummary.cs
  test/modules/TestResultCoordinator/Services/TestResultReportingService.cs
  test/modules/TestResultCoordinator/Settings.cs
Labels: ready-to-merge

#2517 [k8s] Better PVC story for iotedged.
  kubernetes/charts/edge-kubernetes/templates/iotedged-pvc.yaml
  kubernetes/charts/edge-kubernetes/values.yaml
Labels: ready-to-merge

#2519 Removing unused property ConnectionIdleTimeout
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
Labels: 1.0.9

#2489 Updating tolerance period for DirectMethod connectivity tests
  e2e_deployment_files/connectivity_deployment.template.json
Labels: ready-to-merge

#2523 [k8s] Fix RequestType display implementation that lead to crash with stack overflow
  edgelet/kube-client/src/error.rs
Labels: ready-to-merge

#2507 [k8s] kube-client should choose which requests should log trace
  edgelet/kube-client/src/client.rs
  kubernetes/charts/edge-kubernetes/templates/iotedged-deployment.yaml
Labels: ready-to-merge

#2527 [k8s] Fix RequestType display implementation that lead to crash with …
  edgelet/kube-client/src/error.rs
Labels: ready-to-merge

#2522 Updating SDK service 1.22.0 to 1.23.0 and client 1.18.4 to 1.19.0
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/DirectMethodCloudSender/DirectMethodCloudSender.csproj
  edge-modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  edge-modules/DirectMethodSender/DirectMethodSender.csproj
  edge-modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  edge-modules/ModuleRestarter/ModuleRestarter.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/TemperatureFilter/TemperatureFilter.csproj
  edge-modules/TestAnalyzer/TestAnalyzer.csproj
  edge-modules/TwinTester/TwinTester.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/load-gen/load-gen.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
Labels: 1.0.9

#2498 [k8s] Make Docker volume declarations work as anticipated
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentController.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcByValueEqualityComparer.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcByValueComparerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
  kubernetes/doc/edge-deployment-to-k8s-translations.md
Labels: ready-to-merge

#2529 [k8s] Report CRD installation or missing error msg when edge operator charts are installed first
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentCommand.cs
  edgecontroller_integration_tests
Labels: ready-to-merge

#2492 EdgeHub Restart Tester (Test Verification)
  builds/e2e/connectivity.yaml
  e2e_deployment_files/edgehub_restart_deployment.template.json
  test/modules/EdgeHubRestartTester/src/DirectMethodEdgeHubConnectorTest.cs
  test/modules/EdgeHubRestartTester/src/IEdgeHubConnector.cs
  test/modules/EdgeHubRestartTester/src/MessageEdgeHubConnectorTest.cs
  test/modules/EdgeHubRestartTester/src/Program.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartDirectMethodReport.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartDirectMethodReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartDirectMethodReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartMessageReport.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartMessageReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartMessageReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/EdgeHubRestartTest/EdgeHubRestartStatistics.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Settings.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#2524 Import VSTS pipeline status
  tools/IoTEdgeDevOps/DemoApp/DemoApp.csproj
  tools/IoTEdgeDevOps/DemoApp/Program.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/DevOpsAccessSetting.cs
  tools/IoTEdgeDevOps/DevOpsLib/DevOpsLib.csproj
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildManagementTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/DevOpsLibTest.csproj
  tools/IoTEdgeDevOps/DevOpsLibTest/ReleaseManagementTest.cs
  tools/IoTEdgeDevOps/IoTEdgeDashboard/Controllers/HomeController.cs
  tools/IoTEdgeDevOps/IoTEdgeDashboard/IoTEdgeDashboard.csproj
  tools/IoTEdgeDevOps/IoTEdgeDashboard/Startup.cs
  tools/IoTEdgeDevOps/IoTEdgeDevOps.sln
  tools/IoTEdgeDevOps/VstsPipelineSync/DictionaryExtension.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/Program.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsPipelineSync.csproj
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
Labels: ready-to-merge

#2530 Incorrect metrics timespan config doesn't crash
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/DiagnosticConfig.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/ConfigurationEx.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/ConfigurationExTest.cs
Labels: ready-to-merge

#2550 [k8s] Helm chart crd installation error msg cherry pick for public preview branch
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentCommand.cs
Labels: ready-to-merge

#2547 import vsts build data for test dashboard
  tools/IoTEdgeDevOps/DemoApp/Program.cs
  tools/IoTEdgeDevOps/DevOpsLib/AgentDemandSet.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeAgent.cs
  tools/IoTEdgeDevOps/DevOpsLib/ValidationUtil.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildManagementTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/ValidationUtilTest.cs
  tools/IoTEdgeDevOps/IoTEdgeDashboard/Controllers/HomeController.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/Program.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
Labels: ready-to-merge

#2554 Update `make dist` to vendor rust dependencies
  edgelet/.gitignore
  edgelet/LICENSE
  edgelet/Makefile
  edgelet/THIRDPARTYNOTICES
  edgelet/build/linux/package.sh
Labels: ready-to-merge

#2513 Update Connectivity Test Readme
  test/connectivity/README.md
  test/connectivity/images/ConnectivityTest_C2D_Message.png
  test/connectivity/images/ConnectivityTest_C2M_DirectMethod.png
  test/connectivity/images/ConnectivityTest_EdgeHubRestart_DirectMethod.png
  test/connectivity/images/ConnectivityTest_EdgeHubRestart_Message.png
  test/connectivity/images/ConnectivityTest_EdgeHubRestart_Timeline.png
  test/connectivity/images/ConnectivityTest_Ping_DirectMethod.png
Labels: ready-to-merge

#2562 Introduce MQTT EdgeHub Restart Tester to connectivity deployment file
  e2e_deployment_files/edgehub_restart_deployment.template.json
  test/modules/EdgeHubRestartTester/src/DirectMethodEdgeHubConnectorTest.cs
  test/modules/EdgeHubRestartTester/src/EdgeHubConnectorConfig.cs
  test/modules/EdgeHubRestartTester/src/MessageEdgeHubConnectorTest.cs
  test/modules/EdgeHubRestartTester/src/Program.cs
  test/modules/EdgeHubRestartTester/src/Settings.cs
Labels: ready-to-merge

#2563 Support bundle can output to console
  edgelet/iotedge/src/lib.rs
  edgelet/iotedge/src/logs.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/support_bundle.rs
Labels: ready-to-merge

#2552 [1.0.9] Use LogLevel to limit RocksDB LOG file size
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-modules/TestAnalyzer/TestStatusStorage.cs
  edge-modules/TwinTester/TwinEventStorage.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbOptionsProvider.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/StorageLogLevel.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/DbStoreProviderTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RockDbWrapperTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RocksDbOptionsProviderTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/TestRocksDbStoreProvider.cs
Labels: 1.0.9

#2567 Fix staged deployment in end-to-end tests
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/AgentModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/Constants.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge

#2543 Import VSTS Release data for test dashboard
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeRelease.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeReleaseEnvironment.cs
  tools/IoTEdgeDevOps/DevOpsLib/ReleaseEnvironment.cs
  tools/IoTEdgeDevOps/DevOpsLib/ReleaseExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/ReleaseManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsRelease.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseEnvironment.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseStatus.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseEnvironmentTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/ReleaseManagementTest.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsRelease.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseEnvironment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsRelease.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseEnvironment.sql
Labels: ready-to-merge

#2564 Pass test info to long haul and stress test
  builds/e2e/longhaul.yaml
  builds/e2e/stresstest.yaml
  builds/e2e/templates/deploy-iotuap.yaml
  builds/e2e/templates/longhaul-deploy-windows.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  builds/e2e/templates/stresstest-deploy-windows.yaml
  builds/e2e/templates/stresstest-deploy.yaml
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/stress_deployment.template.json
  e2e_deployment_files/stress_deployment.template.windows.json
  scripts/linux/runE2ETest.sh
  scripts/windows/test/Run-E2ETest.ps1
  test/modules/TestAnalyzer/Settings.cs
Labels: ready-to-merge

#1692 Fix typo in passing metrics enabled flag
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
Labels: ready-to-merge

#2569 Fix agent matrix
  tools/IoTEdgeDevOps/DevOpsLib/AgentCapability.cs
  tools/IoTEdgeDevOps/DevOpsLib/AgentMatrix.cs
  tools/IoTEdgeDevOps/IoTEdgeDashboard/.config/dotnet-tools.json
Labels: ready-to-merge

#2452 Test edge hub metrics
  doc/BuiltInMetrics.md
  test/Microsoft.Azure.Devices.Edge.Test.Common/IotHub.cs
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/MetricsValidator/src/Program.cs
  test/modules/MetricsValidator/src/TestBase.cs
  test/modules/MetricsValidator/src/TestReporter.cs
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
  test/modules/MetricsValidator/src/tests/ValidateHostRanges.cs
  test/modules/MetricsValidator/src/tests/ValidateMessages.cs
  test/modules/MetricsValidator/src/tests/ValidateNumberOfMessagesSent.cs
  test/modules/MetricsValidator/src/util/HistogramQuartiles.cs
  test/modules/MetricsValidator/src/util/HostMetricUtil.cs
Labels: ready-to-merge

#2571 Add test info in LH and Stress reports
  test/modules/TestAnalyzer/AggregateCloudOperationReport.cs
  test/modules/TestAnalyzer/ModuleMessagesReport.cs
  test/modules/TestAnalyzer/Settings.cs
  test/modules/TestAnalyzer/TestResultReporter.cs
Labels: ready-to-merge

#2570 Check the wait in EdgeHub restarter to not run into a negative number
  test/modules/EdgeHubRestartTester/src/Program.cs
Labels: ready-to-merge

#2577 Fix load-gen to not increase sequence number when it fails to send
  edge-modules/load-gen/Program.cs
Labels: ready-to-merge

#2558 Update network test info reporting
  test/connectivity/modules/NetworkController/Program.cs
Labels: ready-to-merge

#2575 DevOpsLib: Ingest connectivity, longhaul, stress data into database for test dashboard
  tools/IoTEdgeDevOps/DevOpsLib/BuildDefinitionId.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
Labels: ready-to-merge

#2585 Fix missing testInfo in analyzer report for twins/direct-methods
  test/modules/TestAnalyzer/AggregateCloudOperationReport.cs
Labels: ready-to-merge

#2581 Improve staged deployments in end-to-end tests
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfiguration.cs
Labels: ready-to-merge

#2586 Import more data for test dashboard
  tools/IoTEdgeDevOps/DevOpsLib/AgentMatrix.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgePipelineTask.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeReleaseDeployment.cs
  tools/IoTEdgeDevOps/DevOpsLib/IoTEdgeReleaseEnvironment.cs
  tools/IoTEdgeDevOps/DevOpsLib/ReleaseManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsDeploymentStatus.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsPipelineTask.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseDeployment.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsReleaseEnvironment.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/AgentCapabilityTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/AgentMatrixTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseEnvironmentTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/IoTEdgeReleaseTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/ReleaseManagementTest.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/TestUtil.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseDeployment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseTask.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseDeployment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseEnvironment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseTask.sql
Labels: ready-to-merge

#2574 Longhaul/Stress: Eliminate pipeline parameter logType and logAnalyticsEnabled
  builds/e2e/longhaul.yaml
  builds/e2e/stresstest.yaml
  builds/e2e/templates/longhaul-deploy-windows.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  builds/e2e/templates/stresstest-deploy-windows.yaml
  builds/e2e/templates/stresstest-deploy.yaml
  scripts/linux/runE2ETest.sh
  scripts/windows/test/Run-E2ETest.ps1
  test/modules/TestAnalyzer/Controllers/ReportController.cs
  test/modules/TestAnalyzer/Settings.cs
Labels: ready-to-merge

#2598 Longhaul / Stress: Fix isPassed for twins/dm
  test/modules/TestAnalyzer/AggregateCloudOperationReport.cs
Labels: ready-to-merge

#2599 Longhaul/Stress: Fix naming of build definitions
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
Labels: ready-to-merge

#2595 Longhaul/Stress: Add test name when reporting to log analytics
  builds/e2e/templates/deploy-iotuap.yaml
  builds/e2e/templates/longhaul-deploy-windows.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  builds/e2e/templates/stresstest-deploy-windows.yaml
  builds/e2e/templates/stresstest-deploy.yaml
Labels: ready-to-merge

#2594 Support custom edge agent/hub image for connectivity test
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#2593 Update vsts batch import
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
Labels: ready-to-merge

#2600 [1.0.9] Improve config.yaml instructions for using DPS + Edge
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
Labels: ready-to-merge

#2602 [1.0.9] Fix inconsistent place-holder text
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
Labels: 1.0.9, ready-to-merge

#2603 Port fixes for config files
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
Labels: 1.0.9

#2607 Specify version for additional moby network configuration
  doc/networking.md
Labels: ready-to-merge

#2615 Update Metrics Doc
  doc/BuiltInMetrics.md
Labels: ready-to-merge

#2597 Update the DirectMethod test in the Old E2E test to have a retry logic
  smoke/LeafDevice/details/Details.cs
Labels: ready-to-merge
