Repository Azure/iotedge, pull requests merged in 2020-08, with the labels that each got.

#3339 [mqtt] Fix flaky edgehub authentication test
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
Labels: ready-to-merge

#3303 Test Modules: Fix module-base-full base images to specify moduleuser in dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3347 Test Modules: Fix module-base-full base images to specify moduleuser …
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3328 [mqtt] Add get trust bundle call for workload client
  mqtt/Cargo.lock
  mqtt/Cargo.toml
  mqtt/edgelet-client/Cargo.toml
  mqtt/edgelet-client/src/connect.rs
  mqtt/edgelet-client/src/lib.rs
  mqtt/edgelet-client/src/workload/client.rs
  mqtt/edgelet-client/src/workload/mod.rs
  mqtt/edgelet-client/src/workload/models/mod.rs
  mqtt/edgelet-client/src/workload/models/server_cert.rs
  mqtt/edgelet-client/src/workload/models/trust_bundle.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3351 SendRuntimeQualityTelemetry defaults to true
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
Labels: ready-to-merge

#3313 Add more EA metrics
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/SystemInfo.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/IDeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/MetadataMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/RequestHandlerBase.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/FileConfigSourceModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/MetricsModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/metrics/AvaliabilityMetricsTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/AgentTestsBase.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/edged/ApiVersion.cs
  edgelet/api/managementVersion_2020_07_07.yaml
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-http-mgmt/src/server/system_info/get.rs
  edgelet/edgelet-http/src/version.rs
  edgelet/edgelet-kube/src/runtime.rs
  edgelet/edgelet-test-utils/src/module.rs
Labels: ready-to-merge

#3350 update moby win
  edgelet/build/windows/package.ps1
Labels: ready-to-merge

#3337 [mqtt] Make transport enabled/disabled from ENV
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/src/settings/mod.rs
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-generic/src/settings.rs
Labels: area:mqtt, ready-to-merge

#3340 Update Moby version check in iotedge-check for new Moby version scheme.
  edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
  edgelet/iotedge/src/check/mod.rs
Labels: ready-to-merge

#3341 Update Moby version check in iotedge-check for new Moby version scheme.
  edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
  edgelet/iotedge/src/check/mod.rs
Labels: 1.0.9, ready-to-merge

#3342 Update Moby version check in iotedge-check for new Moby version scheme.
  edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
  edgelet/iotedge/src/check/mod.rs
Labels: 1.0.10, ready-to-merge

#3343 Disable nested edge in tests
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/dm_module_to_module_deployment.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/module_to_functions_deployment.template.json
  e2e_deployment_files/module_to_module_deployment.template.json
  e2e_deployment_files/quickstart_deployment.template.json
  e2e_deployment_files/runtime_only_deployment.template.json
  e2e_deployment_files/stress_deployment.template.json
  e2e_deployment_files/stress_deployment.template.windows.json
  smoke/IotEdgeQuickstart/details/Details.cs
Labels: ready-to-merge

#3357 update moby win (#3350)
  edgelet/build/windows/package.ps1
Labels: ready-to-merge

#3366 Fix new warnings-as-errors reported by gcc 10.
  edgelet/hsm-sys/azure-iot-hsm-c/tests/hsm_client_tpm_ut/hsm_client_tpm_ut.c
Labels: ready-to-merge

#3367 Generate reduced output when ValidateMetrics fails
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
Labels: ready-to-merge

#3365 [PnP] Fixing bug that broke integ tests
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionMetadata.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
Labels: ready-to-merge

#3356 Support bundle upload
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogsUploader.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/IRequestsUploader.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsRequest.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsRequestHandler.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsResponse.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsUploadRequest.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsUploadRequestHandler.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequest.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequestHandler.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2018_06_28/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_10_22/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlob.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobRequestsUploader.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/IAzureBlob.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/ExperimentalFeatures.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/blob/AzureBlobLogsUploaderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
  edgelet/Cargo.lock
  edgelet/Cargo.toml
  edgelet/api/managementVersion_2020_07_07.yaml
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-http-mgmt/Cargo.toml
  edgelet/edgelet-http-mgmt/src/error.rs
  edgelet/edgelet-http-mgmt/src/server/mod.rs
  edgelet/edgelet-http-mgmt/src/server/system_info/mod.rs
  edgelet/edgelet-http-mgmt/src/server/system_info/support_bundle.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/lib.rs
  edgelet/iotedge/src/logs.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/support_bundle.rs
  edgelet/support-bundle/Cargo.toml
  edgelet/support-bundle/src/error.rs
  edgelet/support-bundle/src/lib.rs
  edgelet/support-bundle/src/logs.rs
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#3354 Add test for close on remove all links
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/ConnectionHandlerTest.cs
Labels: ready-to-merge

#3378 Generate reduced output when ValidateMetrics fails
  test/Microsoft.Azure.Devices.Edge.Test/Metrics.cs
Labels: ready-to-merge

#3377 Stop existing modules when iotedged starts
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-http-mgmt/src/client/module.rs
  edgelet/edgelet-kube/src/runtime.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedged/src/error.rs
  edgelet/iotedged/src/lib.rs
Labels: ready-to-merge

#3381 Add edgeHub metrics for process time, retry and ttl cleanup (#3256)
  doc/BuiltInMetrics.md
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ModuleMessageLinkHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudProxy.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/DeviceConnectivityManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Authenticator.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeMessage.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/IMessage.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/MessageHelper.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/cloud/RetryingCloudProxy.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/EdgeHubRoutingUserMetricLogger.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/AuthenticationMiddleware.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttFeedbackMessage.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Dispatcher.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/IRoutingUserMetricLogger.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/NullRoutingUserMetricLogger.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/checkpointers/Checkpointer.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/statemachine/EndpointExecutorFsm.cs
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/messageSources/ModuleMessageSource.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/MqttFeedbackMessageTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Routing.Core.Test/perfcounters/NullRoutingUserMetricLogger.cs
Labels: 1.0.10, ready-to-merge

#3360 Fix startupOrder deserialization
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/UnknownModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerDesiredModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DeploymentConfigInfoTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DeploymentConfigTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DiffTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/ModuleSetTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/OrderedPlanRunnerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/GroupCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/LoggingCommandFactoryTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/NullCommandFactoryTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/ParallelGroupCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/configsources/DeploymentFileBackupTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/configsources/FileConfigSourceTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/metrics/AvaliabilityMetricsTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/planners/HealthRestartPlannerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/planners/RestartPlannerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerEnvironmentTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeHubDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/commands/CreateCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/reporters/IoTHubReporterTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/EdgeDeploymentControllerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/DeploymentSecretBackupTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceAccountMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/planners/KubernetesPlannerTest.cs
Labels: ready-to-merge

#3362 Trigger E2E on edgelet changes
  builds/e2e/e2e.yaml
Labels: ready-to-merge

#3379 Add until to log and support bundle upload
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsRequestHandler.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequest.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/SupportBundleRequestHandler.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2018_06_28/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_01_30/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_10_22/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2019_11_05/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/generatedCode/EdgeletHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
  edgelet/docker-rs/src/apis/container_api.rs
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-http-mgmt/src/server/module/logs.rs
  edgelet/edgelet-http-mgmt/src/server/system_info/support_bundle.rs
  edgelet/iotedge/src/main.rs
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#3384 Startup 'priority' rename to `startupOrder`
  doc/ModuleStartupOrder.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/UnknownModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/RestartPlanner.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerDesiredModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/DockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/EdgeHubDockerRuntimeModule.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironment.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DeploymentConfigInfoTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DeploymentConfigTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/DiffTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/ModuleSetTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/OrderedPlanRunnerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/TestRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/GroupCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/LoggingCommandFactoryTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/NullCommandFactoryTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/commands/ParallelGroupCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/configsources/DeploymentFileBackupTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/configsources/FileConfigSourceTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/metrics/AvaliabilityMetricsTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/planners/HealthRestartPlannerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/planners/RestartPlannerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/AgentTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerEnvironmentTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/DockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeAgentDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/EdgeHubDockerRuntimeModuleTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/commands/CreateCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/test-configs/module-priority-test-config.json
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/reporters/IoTHubReporterTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/EdgeDeploymentControllerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/DeploymentSecretBackupTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesModuleIdentityLifecycleManagerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceAccountMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/planners/KubernetesPlannerTest.cs
Labels: ready-to-merge

#3355 SendRuntimeQualityTelemetry defaults to true
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
Labels: ready-to-merge

#3369 EdgeHub-Bridge code review feedbacks from earlier
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IMessageConsumer.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/DirectMethodHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/MessageConfirmingHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TelemetryHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TwinHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/MqttBridgeComponentDiscovery.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/concurrency/AtomicLong.cs
Labels: ready-to-merge

#3389 Document support bundle upload and new metrics
  doc/BuiltInMetrics.md
  doc/built-in-logs-pull.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/ExperimentalFeatures.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
Labels: ready-to-merge

#3392 Document support bundle upload and new metrics
  doc/BuiltInMetrics.md
  doc/built-in-logs-pull.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/ExperimentalFeatures.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
Labels: ready-to-merge

#3323 Adding modelId to IoTHub device authentication flow
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/EdgeSaslPlainAuthenticator.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/EdgeX509Principal.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/IAmqpAuthenticator.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/SaslPrincipal.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/LinkHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/PersistedTokenCredentialsCache.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/ClientCredentialsFactory.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IClientCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IClientCredentialsFactory.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IotEdgedCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/SharedKeyCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/TokenCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/X509CertCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/AuthenticationMiddleware.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceIdentityProvider.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/CbsNodeTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/DeviceBoundLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EdgeSaslPlainAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EdgeX509PrincipalTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EventsLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/ReceivingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/SendingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/TwinReceivingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudTokenAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/TokenCacheAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/IdentityFactoryTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/PersistedTokenCredentialsCacheTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
Labels: ready-to-merge

#3391 Proxy Support for `iotedge check`
  THIRDPARTYNOTICES
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/templates/image-linux-rust-jobs.yaml
  edge-modules/iotedge-diagnostics-dotnet/IotedgeDiagnosticsDotnet.csproj
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/manifest.yaml.template
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
  edgelet/Cargo.lock
  edgelet/Cargo.toml
  edgelet/build/linux/build.sh
  edgelet/build/windows/build-diagnostics.ps1
  edgelet/iotedge-diagnostics/Cargo.toml
  edgelet/iotedge-diagnostics/docker/linux/amd64/Dockerfile
  edgelet/iotedge-diagnostics/docker/linux/arm32v7/Dockerfile
  edgelet/iotedge-diagnostics/docker/linux/arm64v8/Dockerfile
  edgelet/iotedge-diagnostics/docker/windows/amd64/Dockerfile
  edgelet/iotedge-diagnostics/docker/windows/arm32v7/Dockerfile
  edgelet/iotedge-diagnostics/src/main.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/check/checker.rs
  edgelet/iotedge/src/check/checks/certificates_quickstart.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_connect_iothub.rs
  edgelet/iotedge/src/check/checks/container_engine_dns.rs
  edgelet/iotedge/src/check/checks/container_engine_installed.rs
  edgelet/iotedge/src/check/checks/container_engine_ipv6.rs
  edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
  edgelet/iotedge/src/check/checks/container_engine_logrotate.rs
  edgelet/iotedge/src/check/checks/container_local_time.rs
  edgelet/iotedge/src/check/checks/host_connect_dps_endpoint.rs
  edgelet/iotedge/src/check/checks/host_connect_iothub.rs
  edgelet/iotedge/src/check/checks/host_local_time.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/identity_certificate_expiry.rs
  edgelet/iotedge/src/check/checks/iotedged_version.rs
  edgelet/iotedge/src/check/checks/storage_mounted_from_host.rs
  edgelet/iotedge/src/check/checks/well_formed_config.rs
  edgelet/iotedge/src/check/checks/well_formed_connection_string.rs
  edgelet/iotedge/src/check/checks/windows_host_version.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/main.rs
  scripts/linux/buildBranch.sh
  scripts/windows/build/Publish-Branch.ps1
Labels: ready-to-merge

#3396 Proxy Support for `iotedge check`
  THIRDPARTYNOTICES
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/templates/image-linux-rust-jobs.yaml
  edge-modules/iotedge-diagnostics-dotnet/IotedgeDiagnosticsDotnet.csproj
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/manifest.yaml.template
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/src/GetSocket.cs
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
  edgelet/Cargo.lock
  edgelet/Cargo.toml
  edgelet/build/linux/build.sh
  edgelet/build/windows/build-diagnostics.ps1
  edgelet/iotedge-diagnostics/Cargo.toml
  edgelet/iotedge-diagnostics/docker/linux/amd64/Dockerfile
  edgelet/iotedge-diagnostics/docker/linux/arm32v7/Dockerfile
  edgelet/iotedge-diagnostics/docker/linux/arm64v8/Dockerfile
  edgelet/iotedge-diagnostics/docker/windows/amd64/Dockerfile
  edgelet/iotedge-diagnostics/docker/windows/arm32v7/Dockerfile
  edgelet/iotedge-diagnostics/src/main.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/check/checker.rs
  edgelet/iotedge/src/check/checks/certificates_quickstart.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_connect_iothub.rs
  edgelet/iotedge/src/check/checks/container_engine_dns.rs
  edgelet/iotedge/src/check/checks/container_engine_installed.rs
  edgelet/iotedge/src/check/checks/container_engine_ipv6.rs
  edgelet/iotedge/src/check/checks/container_engine_is_moby.rs
  edgelet/iotedge/src/check/checks/container_engine_logrotate.rs
  edgelet/iotedge/src/check/checks/container_local_time.rs
  edgelet/iotedge/src/check/checks/host_connect_dps_endpoint.rs
  edgelet/iotedge/src/check/checks/host_connect_iothub.rs
  edgelet/iotedge/src/check/checks/host_local_time.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/identity_certificate_expiry.rs
  edgelet/iotedge/src/check/checks/iotedged_version.rs
  edgelet/iotedge/src/check/checks/storage_mounted_from_host.rs
  edgelet/iotedge/src/check/checks/well_formed_config.rs
  edgelet/iotedge/src/check/checks/well_formed_connection_string.rs
  edgelet/iotedge/src/check/checks/windows_host_version.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/main.rs
  scripts/linux/buildBranch.sh
  scripts/windows/build/Publish-Branch.ps1
Labels: ready-to-merge

#3398 removed error log for a valid subscription change message
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
Labels: ready-to-merge

#3399 [PnP] Adding modelId to IoTHub device authentication flow
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/EdgeSaslPlainAuthenticator.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/EdgeX509Principal.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/IAmqpAuthenticator.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/SaslPrincipal.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/LinkHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/PersistedTokenCredentialsCache.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/ClientCredentialsFactory.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IClientCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IClientCredentialsFactory.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/IotEdgedCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/SharedKeyCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/TokenCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/X509CertCredentials.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/AuthenticationMiddleware.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceIdentityProvider.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/CbsNodeTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/DeviceBoundLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EdgeSaslPlainAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EdgeX509PrincipalTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EventsLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/ReceivingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/SendingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/TwinReceivingLinkHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudTokenAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/TokenCacheAuthenticatorTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionProviderTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/IdentityFactoryTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/PersistedTokenCredentialsCacheTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
Labels: ready-to-merge

#3400 [mqtt] Fix flaky tests when re-write env
  mqtt/Cargo.lock
  mqtt/mqtt-broker-tests-util/src/client.rs
  mqtt/mqtt-broker-tests-util/src/env.rs
  mqtt/mqtt-broker-tests-util/src/lib.rs
  mqtt/mqtt-broker-tests-util/src/packet_stream.rs
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-broker/tests/smoke.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/settings.rs
Labels: ready-to-merge

#3397 [mqtt] Update mqtt dependecies and fix tracing error
  mqtt/Cargo.lock
  mqtt/mqtt-broker/src/connection/mod.rs
Labels: area:mqtt, ready-to-merge

#3390 Fix Subscription Processing Workaround
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs
Labels: ready-to-merge

#3409 Fix Subscription Processing Workaround (#3390)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs
Labels: ready-to-merge

#3270 Update dockerfiles to only pull image from docker hub
  edge-agent/docker/windows/arm32v7/Dockerfile
  edge-hub/docker/windows/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/windows/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/Dockerfile
  scripts/linux/createArmBase.sh
  scripts/windows/build/Publish-DockerImage.ps1
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/windows/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/windows/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/windows/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/windows/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/windows/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/windows/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/windows/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/windows/arm32v7/Dockerfile
  test/modules/Relayer/docker/windows/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/windows/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TestResultCoordinator/docker/windows/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/windows/arm32v7/Dockerfile
  test/modules/load-gen/docker/windows/arm32v7/Dockerfile
  tools/snitch/snitcher/docker/linux/arm32v7/Dockerfile
  tools/snitch/snitcher/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3410 Auto labeling github issues
  .github/ISSUE_TEMPLATE/issue-label-list.yml
  .github/workflows/issue-labeler.yml
Labels: ready-to-merge

#3412 Added enable-versioned-regex to github labeling
  .github/workflows/issue-labeler.yml
Labels: ready-to-merge

#3395 Mqtt Bridge Connector tests
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerProtocolHeadTest.cs
Labels: ready-to-merge

#3415 Update regex syntax for github labeller
  .github/ISSUE_TEMPLATE/issue-label-list.yml
Labels: ready-to-merge

#3408 Subscription Processing fix refactor
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SubscriptionProcessor.cs
Labels: ready-to-merge

#3424 Removed message handling race-conditions and allowing empty subscription change message
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IMessageConsumer.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/DirectMethodHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/MessageConfirmingHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TelemetryHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/TwinHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/MqttBridgeComponentDiscovery.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttBrokerModule.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/concurrency/AtomicLong.cs
Labels: ready-to-merge

#3422 ECC fix
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/certificate/CertificateHelperTest.cs
  samples/dotnet/EdgeX509AuthDownstreamDevice/Program.cs
Labels: ready-to-merge

#3425 Adding documentation for passing criteria for DM connectivity tests
  test/connectivity/README.md
Labels: ready-to-merge

#3428 ECC fix
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/certificate/CertificateHelperTest.cs
  samples/dotnet/EdgeX509AuthDownstreamDevice/Program.cs
Labels: ready-to-merge

#3431 Added PEM frame to test certificates so it can be parsed on Linux
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
Labels: ready-to-merge

#3433 Update SDK version to Microsoft.Azure.Devices.Client.1.28.0
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#3437 Update SDK version to Microsoft.Azure.Devices.Client.1.28.0 (#3433)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#3434 Add ServiceIdentitiesUpdated event to DeviceScopeIdentitiesCache
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IDeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/NullDeviceScopeIdentitiesCache.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeTokenAuthenticatorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
Labels: ready-to-merge

#3421 Add option to bypass Edge installation for E2E tests (Linux)
  scripts/linux/runE2ETest.sh
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Labels: ready-to-merge

#3442 Hash all instances of module ids in device telemetry
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
Labels: ready-to-merge

#3450 Hash all instances of module ids in device telemetry
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/MetricsWorker.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.Test/MetricsWorkerTest.cs
Labels: ready-to-merge

#3448 [mqtt] Test fixes
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-edgehub/tests/command.rs
Labels: area:mqtt, ready-to-merge

#3447 fix missed rename for upload logs
  doc/built-in-logs-pull.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsRequestHandler.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#3453 Remove await from support bundle autofac construction
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
Labels: ready-to-merge

#3454 Remove await from support bundle autofac construction (#3453)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/TwinConfigSourceModule.cs
Labels: ready-to-merge

#3452 fix missed rename for upload logs (#3447)
  doc/built-in-logs-pull.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/ModuleLogsRequestHandler.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#3449 [mqtt] Cleanup client disconnect and add logging
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/src/command.rs
  mqtt/mqttd/src/broker/bootstrap/edgehub.rs
Labels: area:mqtt, ready-to-merge

#3455 Update ARM32 & ARM64 base images to 3.1.7-bionic
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm32v7/base/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-agent/docker/linux/arm64v8/base/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm32v7/base/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm64v8/base/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/base/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/base/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/base/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/base/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#3457 [mqtt] Fix clippy warnings for mqtt-bridge
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/controller.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/settings.rs
Labels: area:mqtt, ready-to-merge

#3165 [mqtt] Unbounded messages channel + separate acks channel
  mqtt/Cargo.lock
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqtt-broker/benches/dispatch_messages.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/connection/mod.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-broker/src/server.rs
  mqtt/mqtt-broker/src/stream.rs
  mqtt/mqtt-broker/tests/broker_model.rs
  mqtt/mqtt-edgehub/src/command.rs
  mqtt/mqttd/src/broker/mod.rs
  mqtt/mqttd/src/broker/snapshot.rs
Labels: area:mqtt, ready-to-merge

#3463 Fixed potentialy zombie task in TestClient.
  mqtt/Cargo.lock
  mqtt/mqtt-broker-tests-util/Cargo.toml
  mqtt/mqtt-broker-tests-util/src/client.rs
Labels: area:mqtt, ready-to-merge

#3466 Change back to oneshot for TestClient shutdown
  mqtt/mqtt-broker-tests-util/src/client.rs
Labels: area:mqtt, ready-to-merge

#3439 Adding AuthorizedScopesHandler to Publish Authorized Identities From EdgeHub to Broker
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IDeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/NullDeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/BrokerServiceIdentity.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/IMqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ScopeIdentitiesHandler.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ServiceIdentityTreeTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ScopeIdentitiesHandlerTest.cs
Labels: area:edgehub

#3465 Fix issues due to update to rust 1.46.0
  edgelet/edgelet-http/src/authentication.rs
Labels: ready-to-merge

#3460 Expose unix domain sockets as parameters
  scripts/linux/runE2ETest.sh
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  smoke/IotEdgeQuickstart/details/UriSocks.cs
Labels: ready-to-merge

#3441 Add "RocksDB_MaxOpenFiles" to options we can pass to Agent and Hub.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/AgentModule.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/RocksDbOptionsProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/DbStoreProviderTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RockDbWrapperTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/RocksDbOptionsProviderTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Storage.RocksDb.Test/TestRocksDbStoreProvider.cs
  test/modules/TestAnalyzer/TestStatusStorage.cs
  test/modules/TestResultCoordinator/Startup.cs
  test/modules/TwinTester/TwinEventStorage.cs
Labels: ready-to-merge

#3472 Add parent hostname for E2E tests
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/README.md
Labels: ready-to-merge
