Repository Azure/iotedge, pull requests merged in 2021-01, with the labels that each got.

#4162 remove metrics v0 doc
  doc/[Old]Metrics.md
Labels: ready-to-merge

#4142 Remove metrics v0 (#4109)
  doc/[Old]Metrics.md
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nested_connectivity_deployment.template.json
  e2e_deployment_files/nested_long_haul_deployment.template.json
  e2e_deployment_files/stress_deployment.template.json
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/CloudEndpoint.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/core/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/MetricsV0.cs
Labels: ready-to-merge

#4143 Remove metrics v0 (#4109)
  doc/[Old]Metrics.md
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/stress_deployment.template.json
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/CloudEndpoint.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/endpoints/StoringAsyncEndpointExecutor.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage.RocksDb/ColumnFamilyDbStore.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/MetricsV0.cs
Labels: 1.0.10

#4155 Set default auth mode to Scope (#4095)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  scripts/linux/runE2ETest.sh
  smoke/LeafDevice/details/Details.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
Labels: ready-to-merge

#4163 Rust clippy fix
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-broker/src/persist.rs
  mqtt/mqtt3/src/proto/packet.rs
Labels: ready-to-merge

#4126 Generic Mqtt Test Module: TRC HTTP Client
  .gitignore
  test/modules/GenericMqttTester/Cargo.lock
  test/modules/GenericMqttTester/Cargo.toml
  test/modules/GenericMqttTester/config/default.json
  test/modules/GenericMqttTester/src/message_channel.rs
  test/modules/GenericMqttTester/src/settings.rs
  test/modules/GenericMqttTester/src/tester.rs
  test/rust-test-util/TestResultReportingClient/Cargo.lock
  test/rust-test-util/TestResultReportingClient/Cargo.toml
  test/rust-test-util/TestResultReportingClient/src/client.rs
  test/rust-test-util/TestResultReportingClient/src/lib.rs
  test/rust-test-util/TestResultReportingClient/src/models/message_result.rs
  test/rust-test-util/TestResultReportingClient/src/models/mod.rs
  test/rust-test-util/TestResultReportingClient/src/models/test_result_dto.rs
Labels: ready-to-merge

#4158 Rust test module checkin
  builds/checkin/rust-test-modules.yaml
  builds/checkin/watchdog.yaml
  scripts/linux/generic-rust/clippy.sh
  test/modules/GenericMqttTester/rust-toolchain
Labels: ready-to-merge

#4170 Fix E2E test pipelines for latest iot-identity-service
  builds/e2e/connectivity.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/IOsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/OsPlatform.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4179 Use native precondition for MQTT CI
  builds/ci/mqtt.yaml
Labels: area:mqtt, ready-to-merge

#4182 Remove conflicting packages left by iiot runs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4183 Remove conflicting packages left by iiot runs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4160 ARM Base Image Update Pipeline
  builds/misc/base-images-publish.yaml
  builds/misc/templates/base-image-publish/base-image-build-and-publish.yaml
  builds/misc/templates/base-image-publish/base-image-clear-docker-cache.yaml
  builds/misc/templates/base-image-publish/base-image-docker-login.yaml
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#4181 Remove conflicting packages left by iiot runs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4186 ARM Base Image Update Pipeline
  builds/misc/base-images-publish.yaml
  builds/misc/templates/base-image-publish/base-image-build-and-publish.yaml
  builds/misc/templates/base-image-publish/base-image-clear-docker-cache.yaml
  builds/misc/templates/base-image-publish/base-image-docker-login.yaml
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#4191 Add Cargo.lock to api-proxy-module bin
  edge-modules/api-proxy-module/Cargo.lock
Labels: ready-to-merge

#4192 Add Cargo.lock to api-proxy-module bin (#4191)
  edge-modules/api-proxy-module/Cargo.lock
Labels: ready-to-merge

#4188 ARM Base Image Update Pipeline (#4160)
  builds/misc/base-images-publish.yaml
  builds/misc/templates/base-image-publish/base-image-build-and-publish.yaml
  builds/misc/templates/base-image-publish/base-image-clear-docker-cache.yaml
  builds/misc/templates/base-image-publish/base-image-docker-login.yaml
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#4195 Move 'Download aziot-identity-service' to separate file
  builds/e2e/templates/e2e-setup.yaml
  scripts/local/test/DownloadIdentityService.ps1
Labels: ready-to-merge

#3949 Enable package builds for Mariner
  builds/mariner/SPECS/azure-iotedge/azure-iotedge.signatures.json
  builds/mariner/SPECS/azure-iotedge/azure-iotedge.spec
  builds/mariner/SPECS/libiothsm-std/libiothsm-std.signatures.json
  builds/mariner/SPECS/libiothsm-std/libiothsm-std.spec
  builds/mariner/SPECS/rust/rust.signatures.json
  builds/mariner/SPECS/rust/rust.spec
  builds/misc/packages.yaml
  edgelet/build/linux/package-mariner.sh
Labels: ready-to-merge

#4165 EFLOW on E2E test
  builds/e2e/e2e.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
Labels: ready-to-merge

#4198 Use native precondition for MQTT CI (#4179)
  builds/ci/mqtt.yaml
Labels: ready-to-merge

#4196 Added timeout sending messages to MQTT broker to prevent infinite waiting
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/MqttBrokerConnectorTest.cs
Labels: ready-to-merge

#4184 Fix CI tests after default authentication mode changed to Scope
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/ProtocolHeadFixture.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/RegistryManagerHelper.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs
  test/modules/CloudToDeviceMessageTester/Settings.cs
Labels: ready-to-merge

#4197 Refactor Connectivity test pipeline scripts for aziot-edge
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  test/connectivity/scripts/connectivityTest.sh
  test/connectivity/scripts/testHelper.sh
Labels: ready-to-merge

#4213 Fix Clippy for release 1.1
  edgelet/dps/src/registration.rs
  edgelet/edgelet-core/src/logs.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-core/src/watchdog.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-hsm/tests/test_utils/mod.rs
  edgelet/edgelet-http-mgmt/src/client/module.rs
  edgelet/edgelet-http/src/pid.rs
  edgelet/edgelet-http/src/util/hyperwrap.rs
  edgelet/edgelet-iothub/src/lib.rs
  edgelet/edgelet-kube/src/module/create.rs
  edgelet/edgelet-kube/src/module/trust_bundle.rs
  edgelet/edgelet-utils/src/lib.rs
  edgelet/external-provisioning/src/apis/external_provisioning_api.rs
  edgelet/hsm-rs/src/crypto.rs
  edgelet/hsm-sys/build.rs
  edgelet/iotedge-proxy/src/routine.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedged/src/lib.rs
  edgelet/kube-client/src/client.rs
  edgelet/systemd/src/linux.rs
  edgelet/workload/src/apis/workload_api.rs
Labels: ready-to-merge

#4202 Update Mariner RPM version numbers automatically during build
  builds/mariner/SPECS/azure-iotedge/azure-iotedge.signatures.json
  builds/mariner/SPECS/azure-iotedge/azure-iotedge.spec
  builds/mariner/SPECS/libiothsm-std/libiothsm-std.signatures.json
  builds/mariner/SPECS/libiothsm-std/libiothsm-std.spec
  edgelet/build/linux/package-mariner.sh
Labels: ready-to-merge

#4222 Fix SDL pipeline
  .config/CredScanSuppressions.json
Labels: ready-to-merge

#4220 Fix E2E test module test flakiness from moby issue
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4209 Update current config when plan is empty (#4166)
  doc/BuiltInMetrics.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Agent.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/AgentTests.cs
Labels: 1.1, ready-to-merge

#4230 Fix Add-ons pipeline
  builds/misc/addons-release.yaml
Labels: ready-to-merge

#4233 Make ARM32 Base Image Publication Pipeline Timeout to be 2hr
  builds/misc/base-images-publish.yaml
Labels: ready-to-merge

#4218 Set default auth mode to Scope
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/appsettings_hub.json
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeToDeviceMethodTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/ProtocolHeadFixture.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/RegistryManagerHelper.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
  scripts/linux/runE2ETest.sh
  smoke/LeafDevice/details/Details.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageReceiver.cs
  test/modules/CloudToDeviceMessageTester/Settings.cs
Labels: 1.1, ready-to-merge

#4236 Make ARM32 Base Image Publication Pipeline Timeout to be 2hr (#4233)
  builds/misc/base-images-publish.yaml
Labels: ready-to-merge

#4237 Make ARM32 Base Image Publication Pipeline Timeout to be 2hr (#4233)
  builds/misc/base-images-publish.yaml
Labels: ready-to-merge

#4235 Update base image pipe timeout
  builds/misc/base-images-publish.yaml
Labels: ready-to-merge

#4242 Update long haul deployment to use TRC
  builds/e2e/connectivity.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  scripts/linux/runE2ETest.sh
  scripts/linux/trcE2ETest.sh
  test/connectivity/README.md
Labels: ready-to-merge

#4240 Retry getting device information on startup
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
Labels: ready-to-merge

#4225 Upgrade Ubuntu hosted agents
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/libiothsm.yaml
  builds/checkin/mqtt.yaml
  builds/ci/dotnet.yaml
  builds/ci/edgelet.yaml
  builds/ci/libiothsm.yaml
  builds/ci/mqtt.yaml
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/packages.yaml
  builds/misc/templates/image-linux-rust-jobs.yaml
  builds/service/service-deployment.yaml
  edgelet/build/linux/install.sh
  mqtt/build/linux/install.sh
Labels: ready-to-merge

#4227 Generic mqtt test module trc integration
  test/modules/GenericMqttTester/Cargo.lock
  test/modules/GenericMqttTester/Cargo.toml
  test/modules/GenericMqttTester/config/default.json
  test/modules/GenericMqttTester/src/lib.rs
  test/modules/GenericMqttTester/src/main.rs
  test/modules/GenericMqttTester/src/message_channel.rs
  test/modules/GenericMqttTester/src/message_initiator.rs
  test/modules/GenericMqttTester/src/settings.rs
  test/modules/GenericMqttTester/src/tester.rs
  test/rust-test-util/TestResultReportingClient/Cargo.lock
  test/rust-test-util/TestResultReportingClient/Cargo.toml
  test/rust-test-util/TestResultReportingClient/src/client.rs
  test/rust-test-util/TestResultReportingClient/src/lib.rs
  test/rust-test-util/TestResultReportingClient/src/models/test_result_dto.rs
Labels: ready-to-merge

#4249 [mqtt] Retry non-iothub subscription when rejected by server
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/pump/builder.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
  mqtt/mqtt-bridge/src/upstream/rpc/remote.rs
  mqtt/mqtt-edgehub/src/command/handler.rs
  mqtt/mqtt3/src/client/mod.rs
  mqtt/mqtt3/src/client/subscriptions.rs
  mqtt/mqtt3/tests/subscriptions.rs
Labels: area:mqtt, ready-to-merge

#4257 Update IotEdgeQuickstart for new packages
  scripts/linux/nested-edge-deploy-agent.sh
  scripts/linux/trcE2ETest.sh
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/IotEdgeQuickstart/Program.cs
  smoke/IotEdgeQuickstart/Quickstart.cs
  smoke/IotEdgeQuickstart/details/Details.cs
  smoke/IotEdgeQuickstart/details/IBootstrapper.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  smoke/IotEdgeQuickstart/details/IotedgedWindows.cs
  smoke/IotEdgeQuickstart/details/UriSocks.cs
  smoke/IotEdgeQuickstart/details/YamlDocument.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4258 Generic mqtt test module: Rename folders to follow rust patterns
  builds/checkin/rust-test-modules.yaml
  builds/e2e/nested-edge-longhaul.yaml
  test/modules/generic-mqtt-tester/Cargo.lock
  test/modules/generic-mqtt-tester/Cargo.toml
  test/modules/generic-mqtt-tester/README.md
  test/modules/generic-mqtt-tester/config/default.json
  test/modules/generic-mqtt-tester/docker/amd64/Dockerfile
  test/modules/generic-mqtt-tester/rust-toolchain
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/main.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
  test/rust-test-util/test-result-reporting-client/Cargo.lock
  test/rust-test-util/test-result-reporting-client/Cargo.toml
  test/rust-test-util/test-result-reporting-client/src/client.rs
  test/rust-test-util/test-result-reporting-client/src/lib.rs
  test/rust-test-util/test-result-reporting-client/src/models/message_result.rs
  test/rust-test-util/test-result-reporting-client/src/models/mod.rs
  test/rust-test-util/test-result-reporting-client/src/models/test_result_dto.rs
Labels: ready-to-merge

#4265 EFLOW on E2E test (#4165)
  builds/e2e/e2e.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
Labels: ready-to-merge

#4268 Don't use http proxy for Amqp/Mqtt over TCP
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleClientProvider.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleClientProviderTest.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
Labels: ready-to-merge

#4270 Added checking for null values in arrays
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/twin/ReportedPropertiesValidator.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/twin/ReportedPropertiesValidatorTest.cs
Labels: ready-to-merge

#4238 upstream/downstream messages
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/integration.rs
  mqtt/mqtt-bridge/tests/tls/cert.pem
  mqtt/mqtt-bridge/tests/tls/pkey.pem
  mqtt/mqtt-broker-tests-util/src/server.rs
  mqtt/mqtt-broker/src/lib.rs
  mqtt/mqtt-util/src/client_io.rs
Labels: ready-to-merge

#4234 Add TestMode to TestResultCoordinator and make it able to run without test duration
  builds/e2e/longhaul.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  scripts/linux/trcE2ETest.sh
  test/modules/TestResultCoordinator/Services/TestResultReportingService.cs
  test/modules/TestResultCoordinator/Settings.cs
  test/modules/TestResultCoordinator/TestMode.cs
Labels: ready-to-merge

#4271 message store cleanup catch exception when message is updated
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/storage/MessageStoreTest.cs
Labels: ready-to-merge

#4273 message store cleanup catch exception when message is updated (#4271)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/storage/MessageStore.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/storage/MessageStoreTest.cs
Labels: ready-to-merge

#4264 Generate certificates in connectivity tests
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
  scripts/linux/trcE2ETest.sh
  smoke/IotEdgeQuickstart/details/Details.cs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Labels: ready-to-merge

#4280 Suppress bridge test certificate warning.
  .config/CredScanSuppressions.json
  mqtt/mqtt-bridge/tests/integration.rs
Labels: ready-to-merge

#4287 Suppress bridge test certificate warning.
  .config/CredScanSuppressions.json
  mqtt/mqtt-broker/src/tls.rs
  mqtt/mqtt-broker/tests/tls/cert.pem
  mqtt/mqtt-broker/tests/tls/pkey.pem
Labels: ready-to-merge

#4288 Fixes for long haul pipeline
  scripts/linux/runE2ETest.sh
  scripts/linux/trcE2ETest.sh
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
Labels: ready-to-merge

#4286 Drop Ubuntu 16.04, add 18.04
  .github/ISSUE_TEMPLATE/bug_report.md
  builds/e2e/connectivity.yaml
  builds/e2e/e2e.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/stresstest.yaml
  builds/misc/packages.slow.yaml
  builds/misc/packages.yaml
  doc/EdgeRuntimeConfigSpec.md
  edgelet/build/linux/docker/cross-compile/Dockerfile.ubuntu16.04.aarch64-unknown-linux-gnu
  edgelet/build/linux/docker/cross-compile/README.md
  edgelet/build/linux/docker/cross-compile/ubuntu16.04/build_arm64_toolchain_container.sh
  edgelet/build/linux/docker/cross-compile/ubuntu16.04/openssl.sh
  edgelet/build/linux/package.sh
  edgelet/doc/devguide.md
  edgelet/docker-rs/docker-swagger.yaml
  edgelet/docker-rs/src/models/system_info.rs
  edgelet/edgelet-kube/src/runtime.rs
  scripts/docker-build/README.md
  scripts/docker-build/linux/amd64/Dockerfile
  scripts/linux/runE2ETest.sh
  test/connectivity/scripts/testHelper.sh
Labels: ready-to-merge

#4245 Add DirectMethodLongHaulReport and separate DM reports
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nested_connectivity_deployment.template.json
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportDataWithSenderAndReceiverSource.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportDataWithSenderSourceOnly.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodConnectivityReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/MockNetworkStatusTimeline.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/NetworkStatusTimelineTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReport.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/NetworkStatusTimeline.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Reports/TestReportType.cs
  test/modules/TestResultCoordinator/Settings.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#4290 Adding checkout repo to longHaul instead of artifacts
  builds/e2e/longhaul.yaml
  builds/e2e/templates/longhaul-deploy.yaml
Labels: ready-to-merge

#4244 Config changes for content trust with cert service
  doc/NotaryContentTrust.md
  edgelet/Cargo.lock
  edgelet/edgelet-docker/Cargo.toml
  edgelet/edgelet-docker/src/error.rs
  edgelet/edgelet-docker/src/notary.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-docker/test/linux/bad_settings_content_trust.yaml
  edgelet/edgelet-docker/test/linux/sample_settings_content_trust.yaml
  edgelet/edgelet-http/src/error.rs
  edgelet/edgelet-http/src/util/connector.rs
  edgelet/iotedge/src/init/import/mod.rs
  edgelet/iotedge/test-files/init/import/moby-runtime-content-trust/certd.toml
  edgelet/iotedge/test-files/init/import/moby-runtime-content-trust/edged.yaml
Labels: ready-to-merge

#4298 Cert fixes for test pipelines
  builds/e2e/e2e.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/templates/e2e-setup.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/IConfigDocument.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/TomlDocument.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/YamlDocument.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/certs/FixedPaths.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
Labels: ready-to-merge

#4277 Generic mqtt test module: Add config for topic, message size, frequency
  test/modules/generic-mqtt-tester/config/default.json
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/main.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4299 Automate Vm Creation for Nested E2E
  tools/TestAgents/CreateAzureVmForE2e.ps1
  tools/TestAgents/e2eOneTimeDependencySetup.sh
Labels: ready-to-merge

#4152 [k8s] ensure agent shuts down on critical watch failures.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/IKubernetesOperator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironmentOperator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentOperator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/KubernetesEnvironmentOperatorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesEnvironmentOperatorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/EdgeDeploymentOperatorTest.cs
Labels: ready-to-merge

#4302 Ensure E2E tests start with clean config
  scripts/linux/nested-edge-deploy-agent.sh
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/IEdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/LeafDevice.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/certs/CaCertificates.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/certs/FixedPaths.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4208 [k8s] Allow non standard ports for container registry.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/ImagePullSecretName.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/ImagePullSecretNameTest.cs
  edgelet/edgelet-kube/src/registry/image_pull_secret.rs
Labels: ready-to-merge

#4254 [k8s] Allow alphanumerics to start K8s object names.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubeUtils.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/EdgeDeploymentControllerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubeUtilsTest.cs
  edgelet/edgelet-kube/src/convert/mod.rs
  edgelet/edgelet-kube/src/convert/to_k8s.rs
  edgelet/edgelet-utils/src/lib.rs
Labels: ready-to-merge

#4305 [k8s] Update Helm charts and version for beta13
  .github/ISSUE_TEMPLATE/bug_report.md
  builds/e2e/connectivity.yaml
  builds/e2e/e2e.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/stresstest.yaml
  builds/misc/packages.slow.yaml
  builds/misc/packages.yaml
  doc/EdgeRuntimeConfigSpec.md
  edgelet/build/linux/docker/cross-compile/Dockerfile.ubuntu16.04.aarch64-unknown-linux-gnu
  edgelet/build/linux/docker/cross-compile/README.md
  edgelet/build/linux/docker/cross-compile/ubuntu16.04/build_arm64_toolchain_container.sh
  edgelet/build/linux/docker/cross-compile/ubuntu16.04/openssl.sh
  edgelet/build/linux/package.sh
  edgelet/doc/devguide.md
  edgelet/docker-rs/docker-swagger.yaml
  edgelet/docker-rs/src/models/system_info.rs
  edgelet/edgelet-kube/src/runtime.rs
  kubernetes/charts/edge-kubernetes-crd/Chart.yaml
  kubernetes/charts/edge-kubernetes/Chart.yaml
  kubernetes/charts/edge-kubernetes/values.yaml
  scripts/docker-build/README.md
  scripts/docker-build/linux/amd64/Dockerfile
  scripts/linux/runE2ETest.sh
  test/connectivity/scripts/testHelper.sh
  versionInfo.json
Labels: ready-to-merge

#4269 Add twin legacy result to TestResultCoordinator
  builds/e2e/templates/longhaul-deploy.yaml
  e2e_deployment_files/long_haul_deployment.template.json
  scripts/linux/runE2ETest.sh
  scripts/linux/trcE2ETest.sh
  test/modules/ModuleLib/TestResults/LegacyTwinTestResult.cs
  test/modules/TestResultCoordinator/Reports/LegacyTwin/LegacyTwinReport.cs
  test/modules/TestResultCoordinator/Reports/LegacyTwin/LegacyTwinReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/LegacyTwin/LegacyTwinReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Reports/TestReportType.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
  test/modules/TwinTester/TwinAllOperationsResultHandler.cs
Labels: ready-to-merge

#4293 Fix GetModules call error using RFC3339 DateTime format.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/requests/RequestHandlerBase.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Storage/SerDeExtensions.cs
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Labels: ready-to-merge
