Repository Azure/iotedge, pull requests merged in 2021-06, with the labels that each got.

#5058 Fix provisioning behavior when DPS changes
  edgelet/Cargo.lock
  edgelet/aziot-edged/src/lib.rs
  edgelet/identity-client/src/client.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#5057 Add "dist" target to supply Yocto builds with release.
  builds/misc/packages.yaml
  edgelet/build/linux/package.sh
Labels: 1.1, ready-to-merge

#4929 fix: in case of error, propagate back error code of edgeHub
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxyDispatcher.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokeredCloudProxyDispatcherTest.cs
Labels: ready-to-merge

#5084 Fix user configuration
  edge-modules/api-proxy-module/templates/nginx_default_config.conf
Labels: ready-to-merge

#5059 Update functions to 3.0 (#4910)
  CodeCoverage.runsettings
  builds/checkin/dotnet.yaml
  builds/ci/dotnet.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/templates/install-dotnet2.yaml
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-modules/functions/samples/README.md
  edge-modules/functions/samples/docker/linux/amd64/Dockerfile
  edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
  edge-modules/functions/samples/docker/windows/amd64/Dockerfile
  scripts/linux/buildBranch.sh
  scripts/linux/runTests.sh
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: 1.2

#5074 Limit sysinfo crate FDs usage. (#5055)
  edgelet/edgelet-docker/src/runtime.rs
Labels: ready-to-merge

#4849 Manifest trust metrics.
  doc/BuiltInMetrics.md
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/DeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/metrics/IDeploymentMetrics.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/TwinConfigSource.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/metrics/PresenceGauge.cs
Labels: ready-to-merge

#5054 Nested Longhaul Tests: Port #5047 and #5052
  builds/e2e/templates/nested-longhaul-deploy.yaml
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
Labels: ready-to-merge

#5077 handling Not found error for manifest trust bundle
  edgelet/edgelet-http-workload/src/server/manifest_trust_bundle.rs
Labels: ready-to-merge

#5044 Properly dispose UDS for Workload Client. (#5035)
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpChunkedStreamReader.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
Labels: ready-to-merge

#5096 Skip the "twin signing" metrics for E2E tests
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#5097 Don't dispose stream too early.
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
Labels: ready-to-merge

#5100 Don't dispose stream too early. (#5097)
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/uds/HttpUdsMessageHandler.cs
Labels: ready-to-merge

#5094 Enable aziot-edged in CentOS package
  edgelet/Makefile
  edgelet/contrib/centos/00-aziot-edged.preset
  edgelet/contrib/centos/aziot-edge.spec
Labels: ready-to-merge

#5099 Enable aziot-edged in CentOS package
  edgelet/Cargo.lock
  edgelet/Makefile
  edgelet/contrib/centos/00-aziot-edged.preset
  edgelet/contrib/centos/aziot-edge.spec
Labels: ready-to-merge

#5040 Update base image update script to not include `generic-mqtt-tester`
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#5098 Builds: Eliminate insecure docker login
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/misc/addons-publish.yaml
  builds/misc/addons-release.yaml
  builds/misc/images-mqtt.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/templates/image-linux.yaml
  builds/templates/install-dotnet2.yaml
  scripts/linux/buildImage.sh
  scripts/linux/buildManifest.sh
Labels: ready-to-merge

#5111 Docker login: Removing typo and not-needed script help
  builds/misc/addons-publish.yaml
  builds/misc/addons-release.yaml
  builds/misc/images-release.yaml
  scripts/linux/buildImage.sh
  scripts/linux/buildManifest.sh
Labels: ready-to-merge

#5073 TestResultCoordinator: List specific test events for counting report type
  test/modules/DirectMethodSender/DirectMethodSenderBase.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Settings.cs
Labels: ready-to-merge

#5109 Builds: Eliminate insecure docker login (#5098)
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/misc/addons-publish.yaml
  builds/misc/addons-release.yaml
  builds/misc/images-mqtt.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/templates/image-linux.yaml
  builds/templates/install-dotnet2.yaml
  scripts/linux/buildImage.sh
  scripts/linux/buildManifest.sh
Labels: ready-to-merge

#5091 Fixed exception type in BrokerConnection::SendAsync,
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerConnector.cs
Labels: ready-to-merge

#5112 Longhaul Test Documentation: Refactor docs and add longhaul doc
  test/doc/connectivity.md
  test/doc/e2e.md
  test/doc/images/ConnectivityTestDiagram.png
  test/doc/images/ConnectivityTest_C2D_Message.png
  test/doc/images/ConnectivityTest_C2M_DirectMethod.png
  test/doc/images/ConnectivityTest_DeploymentUpdate.png
  test/doc/images/ConnectivityTest_EdgeHubRestart_DirectMethod.png
  test/doc/images/ConnectivityTest_EdgeHubRestart_Message.png
  test/doc/images/ConnectivityTest_EdgeHubRestart_Timeline.png
  test/doc/images/ConnectivityTest_Messaging.png
  test/doc/images/ConnectivityTest_Ping_DirectMethod.png
  test/doc/images/LonghaulTest_All.png
  test/doc/images/LonghaulTest_DirectMethod.png
  test/doc/images/LonghaulTest_General.png
  test/doc/images/LonghaulTest_Messaging.png
  test/doc/images/LonghaulTest_TwinDesiredProperty.png
  test/doc/images/LonghaulTest_TwinReportedProperty.png
  test/doc/longhaul.md
Labels: ready-to-merge

#5105 Mark tests as failed on failure.
  builds/e2e/templates/e2e-run.yaml
Labels: ready-to-merge

#5120 Mark tests as failed on failure. (#5105)
  builds/e2e/templates/e2e-run.yaml
Labels: ready-to-merge

#5110 Builds: Eliminate insecure docker login (#5098)
  builds/e2e/templates/e2e-clear-docker-cached-images.yaml
  builds/misc/images-mqtt.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/metrics-collector-images-publish.yaml
  builds/misc/metrics-collector-images-release.yaml
  builds/misc/templates/image-linux-rust-jobs.yaml
  builds/misc/templates/image-linux-rust.yaml
  builds/misc/templates/image-linux.yaml
  scripts/linux/buildImage.sh
  scripts/linux/buildManifest.sh
  tools/snitch/scripts/buildImage.sh
Labels: ready-to-merge

#5107 Fix DPS E2E tests
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
Labels: ready-to-merge

#5127 Update cargo dependency
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
Labels: ready-to-merge

#5128 Prepare for Release 1.2.2
  CHANGELOG.md
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/control
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#5122 Devops Sync Job: Refactor to facilitate incoming bug opening automation changes
  tools/IoTEdgeDevOps/DevOpsLib/BugQueryGenerator.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
Labels: ready-to-merge

#5046 cloudproxy tests - add events at retry
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
Labels: ready-to-merge

#5134 E2E: Skipped `edgeAgent_created_pids_total` metric for ARM32
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#5126 Device config has allow_privileged flag
  edgelet/contrib/config/linux/template.toml
  edgelet/docker-rs/src/models/host_config.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/test-files/config/ca-certs-est/edged.toml
  edgelet/iotedge/test-files/config/ca-certs-local-ca/edged.toml
  edgelet/iotedge/test-files/config/ca-certs/edged.toml
  edgelet/iotedge/test-files/config/ca-quickstart-custom/edged.toml
  edgelet/iotedge/test-files/config/ca-quickstart/edged.toml
  edgelet/iotedge/test-files/config/complex-agent-spec/edged.toml
  edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/edged.toml
  edgelet/iotedge/test-files/config/dps-symmetric-key/edged.toml
  edgelet/iotedge/test-files/config/dps-tpm/edged.toml
  edgelet/iotedge/test-files/config/dps-x509/edged.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/edged.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/edged.toml
  edgelet/iotedge/test-files/config/manual-connection-string-2/edged.toml
  edgelet/iotedge/test-files/config/manual-connection-string/edged.toml
  edgelet/iotedge/test-files/config/manual-x509/edged.toml
  edgelet/iotedge/test-files/config/moby-runtime-content-trust/edged.toml
  edgelet/iotedge/test-files/config/moby-runtime-network-2/edged.toml
  edgelet/iotedge/test-files/config/moby-runtime-network/edged.toml
  edgelet/iotedge/test-files/config/nested-edge/edged.toml
  edgelet/iotedge/test-files/config/not-socket-activated-both-custom/edged.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varlib/edged.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varrun/edged.toml
  edgelet/iotedge/test-files/config/socket-activated-one-custom/edged.toml
Labels: ready-to-merge

#5142 Prepare for Release 1.2.2 (pt2)
  CHANGELOG.md
Labels: ready-to-merge

#5133 Devops Sync Job: Add WasScheduled field to database of builds
  tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
Labels: ready-to-merge

#5136 Improve log message for container state
  edgelet/iotedge/src/check/checks/storage_mounted_from_host.rs
Labels: ready-to-merge

#5145 Send connection device Id information on twin change notifications #4…
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpMessageConverter.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Constants.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/IEdgeHub.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/SystemProperties.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/AmqpMessageConverterTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/ProtocolGatewayMessageConverterTest.cs
Labels: 1.1, ready-to-merge

#5150 Update Azure CLI command in ISA95 pipeline
  builds/e2e/templates/nested-create-identity.yaml
Labels: ready-to-merge

#5143 Testing: Apply tls 1.2 settings for all tests
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/dm_module_to_module_deployment.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/module_to_functions_deployment.template.json
  e2e_deployment_files/module_to_module_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  e2e_deployment_files/quickstart_deployment.template.json
  e2e_deployment_files/runtime_only_deployment.template.json
  e2e_deployment_files/stress_deployment.template.json
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
Labels: ready-to-merge

#5132 Devops: Fix triggers for connectivity and e2e
  builds/e2e/connectivity.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
Labels: ready-to-merge

#5115 Longhaul Tests: Shard arm longhaul load among agents
  builds/e2e/longhaul.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  builds/e2e/templates/longhaul-setup.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment_constrained.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  scripts/linux/trcE2ETest.sh
Labels: ready-to-merge

#5163 E2E: Skipped `edgeAgent_created_pids_total` metric for ARM32 (#5134)
  test/modules/MetricsValidator/src/tests/ValidateDocumentedMetrics.cs
Labels: ready-to-merge

#5168 Fix Nested E2E stuck on Edgelet installation
  builds/e2e/templates/nested-agent-deploy.yaml
  builds/misc/packages.yaml
Labels: ready-to-merge

#5169 No need for the capability anymore
  builds/e2e/nested-e2e.yaml
Labels: ready-to-merge

#5162 Update Azure CLI command in Nested pipelines (#5150)
  builds/e2e/templates/nested-create-identity.yaml
Labels: ready-to-merge

#5167 Use Docker Timestamp When Log Timestamp is not Available in JSON log (#4981)
  builds/checkin/dotnet.yaml
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogMessageParser.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogMessageParser.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobRequestsUploader.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Labels: ready-to-merge

#5165 Introduce `Timestamps` Option via mgmt.sock (#4970)
  edgelet/api/README.md
  edgelet/api/managementVersion_2021_05_11.yaml
  edgelet/doc/devguide.md
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-http-mgmt/src/client/module.rs
  edgelet/edgelet-http-mgmt/src/server/module/logs.rs
  edgelet/management/docs/Identity.md
  edgelet/management/docs/IdentityApi.md
  edgelet/management/docs/IdentitySpec.md
  edgelet/management/docs/ModuleApi.md
  edgelet/management/docs/ModuleSpec.md
  edgelet/management/docs/SystemInfo.md
  edgelet/management/docs/SystemInformationApi.md
  edgelet/management/src/apis/module_api.rs
Labels: ready-to-merge

#5148 Fix: Delay frequent twin pulls on reconnect
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/EdgeAgentConnection.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/EdgeAgentConnectionTest.cs
Labels: ready-to-merge

#5170 Testing: Sync state of tests on release/1.2 with master branch
  builds/checkin/api-proxy.yaml
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/rust-test-modules.yaml
  builds/e2e/connectivity.yaml
  builds/e2e/e2e.yaml
  builds/e2e/isa-95-smoke-test.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
  builds/e2e/templates/longhaul-deploy.yaml
  builds/e2e/templates/longhaul-setup.yaml
  builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm32.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm64.yaml
  builds/e2e/templates/nested-longhaul-deploy.yaml
  builds/misc/images.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/dm_module_to_module_deployment.json
  e2e_deployment_files/edgehub_restart_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment_constrained.template.json
  e2e_deployment_files/module_to_functions_deployment.template.json
  e2e_deployment_files/module_to_module_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  e2e_deployment_files/quickstart_deployment.template.json
  e2e_deployment_files/runtime_only_deployment.template.json
  e2e_deployment_files/stress_deployment.template.json
  scripts/linux/trcE2ETest.sh
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
  test/modules/DirectMethodSender/DirectMethodSenderBase.cs
  test/modules/DirectMethodSender/Program.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/Connectivity/DirectMethodConnectivityReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Services/TestResultReportingService.cs
  test/modules/TestResultCoordinator/Settings.cs
  test/modules/TestResultCoordinator/TestReportUtil.cs
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/load-gen/DefaultMessageSender.cs
Labels: ready-to-merge

#5060 Update functions to 3.0 (#4910)
  CodeCoverage.runsettings
  builds/checkin/dotnet.yaml
  builds/ci/dotnet.yaml
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-modules/functions/samples/README.md
  edge-modules/functions/samples/docker/linux/amd64/Dockerfile
  edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
  edge-modules/functions/samples/docker/windows/amd64/Dockerfile
  scripts/linux/buildBranch.sh
  scripts/linux/runTests.sh
  scripts/windows/build/Publish-Branch.ps1
Labels: 1.1

#5149 DevOps: Add bug creation logic to ADO sync job
  tools/IoTEdgeDevOps/DevOpsLib/BugManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/BugWiqlManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/BugWiqlQuery.cs
  tools/IoTEdgeDevOps/DevOpsLib/BugWiqlQueryGenerator.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildDefinitionId.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/Program.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.QueryVstsBugsForMatchingBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBug.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBugCount.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsRelease.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseDeployment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseEnvironment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsReleaseTask.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBug.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBugCounts.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsRelease.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseDeployment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseEnvironment.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsReleaseTask.sql
Labels: ready-to-merge

#5180 Fix Privileged Flag
  edgelet/Cargo.lock
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/control
  edgelet/docker-rs/src/models/host_config.rs
  edgelet/edgelet-docker/src/runtime.rs
Labels: ready-to-merge

#5182 DevOps Triggers: Fix trigger setting for branch to be "master"
  builds/e2e/connectivity.yaml
  builds/e2e/e2e.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
Labels: ready-to-merge

#5181 DevOps Sync Job: Improve and clean up filters, improve logging
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/docker/linux-amd64/Dockerfile
Labels: ready-to-merge

#5173 Use Docker Timestamp When Log Timestamp is not Available in JSON log.
  builds/checkin/dotnet.yaml
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/IRuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ILogMessageParser.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogMessageParser.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/LogsProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/logs/ModuleLogFilter.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/IModuleManager.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/ModuleManagementHttpClient.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/RuntimeInfoProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/versioning/ModuleManagementHttpClientVersioned.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/blob/AzureBlobRequestsUploader.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesRuntimeInfoProvider.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProcessorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/logs/LogsRequestToOptionsMapperTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsRequestHandlerTests.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Core.Test/requests/LogsUploadRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/ModuleManagementHttpClientTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/RuntimeInfoProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/stream/LogsStreamRequestHandlerTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/DummyModuleManager.cs
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
Labels: ready-to-merge

#5117 multiple workload sockets
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker/CombinedEdgeletConfigProvider.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/commands/CreateOrUpdateCommand.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker.Test/CombinedEdgeletConfigProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Test/commands/CreateOrUpdateCommandTest.cs
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/src/workload_manager.rs
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-docker/src/error.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-docker/tests/runtime.rs
  edgelet/edgelet-http-mgmt/src/server/module/create.rs
  edgelet/edgelet-http-mgmt/src/server/module/delete.rs
  edgelet/edgelet-http-mgmt/src/server/module/list.rs
  edgelet/edgelet-http-mgmt/src/server/module/logs.rs
  edgelet/edgelet-http-mgmt/src/server/module/prepare_update.rs
  edgelet/edgelet-http-mgmt/src/server/module/restart.rs
  edgelet/edgelet-http-mgmt/src/server/module/start.rs
  edgelet/edgelet-http-mgmt/src/server/module/stop.rs
  edgelet/edgelet-http-mgmt/src/server/module/update.rs
  edgelet/edgelet-http-mgmt/src/server/system_info/get.rs
  edgelet/edgelet-http/examples/identities.rs
  edgelet/edgelet-http/src/lib.rs
  edgelet/edgelet-http/src/unix.rs
  edgelet/edgelet-http/tests/systemd.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#5147 Add prometheus mode to obsagent-client test module
  builds/checkin/rust-test-modules.yaml
  builds/misc/images.yaml
  builds/misc/templates/rust-test-module-build.yaml
  test/modules/obsagent-client/Cargo.lock
  test/modules/obsagent-client/Cargo.toml
  test/modules/obsagent-client/src/config.rs
  test/modules/obsagent-client/src/lib.rs
  test/modules/obsagent-client/src/main.rs
  test/modules/obsagent-client/src/otel_client.rs
  test/modules/obsagent-client/src/prometheus_endpoint.rs
Labels: ready-to-merge

#5192 Prepare for release 1.2.3
  CHANGELOG.md
  edgelet/Cargo.lock
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/control
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge
