Repository Azure/iotedge, pull requests merged in 2021-08, with the labels that each got.

#5305 Add timestamp to the default support-bundle filename
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#5320 RUSTSEC Security/release 1.2
  edge-modules/edge-dashboard/Cargo.lock
  edge-modules/edge-dashboard/Cargo.toml
  edge-modules/edge-dashboard/src/error.rs
  edge-modules/edge-dashboard/src/health.rs
  edge-modules/edge-dashboard/src/lib.rs
  edge-modules/edge-dashboard/src/main.rs
  edge-modules/edge-dashboard/src/modules.rs
  edge-modules/edge-dashboard/src/settings.rs
  edge-modules/edge-dashboard/src/state.rs
  edge-modules/edge-dashboard/src/status.rs
  edge-modules/edgehub-proxy/Cargo.lock
  edge-modules/edgehub-proxy/Cargo.toml
  edgelet/edgelet-core/Cargo.toml
  edgelet/edgelet-core/src/parse_since.rs
Labels: ready-to-merge

#5321 Update packages for Component Governance
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edgelet/Cargo.lock
  tools/check_submodules/Cargo.lock
  tools/snitch/Cargo.lock
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#5323 E2E: Stabilize Priority Queue Tests
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
  test/connectivity/modules/NetworkController/Program.cs
Labels: ready-to-merge

#5324 RUSTSEC fixes
  edge-modules/edgehub-proxy/Cargo.lock
Labels: ready-to-merge

#5325 RUSTSEC fixes
  edge-modules/edgehub-proxy/Cargo.lock
Labels: ready-to-merge

#5322 Update packages for Component Governance
  tools/check_submodules/Cargo.lock
  tools/snitch/Cargo.lock
  tools/snitch/snitcher/Cargo.toml
  tools/snitch/snitcher/src/lib.rs
Labels: ready-to-merge

#5319 RUSTSEC Fix security vulnerabilities
  edge-modules/edge-dashboard/Cargo.lock
  edge-modules/edge-dashboard/Cargo.toml
  edge-modules/edge-dashboard/src/error.rs
  edge-modules/edge-dashboard/src/health.rs
  edge-modules/edge-dashboard/src/lib.rs
  edge-modules/edge-dashboard/src/main.rs
  edge-modules/edge-dashboard/src/modules.rs
  edge-modules/edge-dashboard/src/settings.rs
  edge-modules/edge-dashboard/src/state.rs
  edge-modules/edge-dashboard/src/status.rs
  edge-modules/edgehub-proxy/Cargo.lock
  edgelet/Cargo.lock
  edgelet/edgelet-core/Cargo.toml
  edgelet/edgelet-core/src/parse_since.rs
  mqtt/Cargo.lock
Labels: ready-to-merge

#5313 Remove redundant tests and wait for device to be disconnected (#5244)
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
Labels: ready-to-merge, 1.2

#5326 fix various RUSTSEC
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.csproj
  edgelet/Cargo.lock
  mqtt/Cargo.lock
  test/modules/obsagent-client/Cargo.lock
  tools/check_submodules/Cargo.lock
  tools/snitch/Cargo.lock
Labels: ready-to-merge

#5331 RUSTSEC: Update smallvec for component governance
  mqtt/Cargo.lock
  mqtt/mqtt-broker-tests-util/Cargo.toml
  mqtt/mqtt-broker/Cargo.toml
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/tracing/edgehub.rs
  mqtt/mqttd/src/tracing/format.rs
  mqtt/mqttd/src/tracing/generic.rs
Labels: ready-to-merge

#5301 Connectivity / Longhaul Tests: Custom mqtt test improvements
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#5311 Update functions packages (#5239)
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
Labels: ready-to-merge, 1.2

#5316 [1.2][k8s] update k8s client. (#5210) (#5250)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.csproj
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker.Test/CombinedEdgeletConfigProviderTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/DeploymentSecretBackupTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/EdgeDeploymentCommandTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesServiceMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/EdgeDeploymentOperatorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/service/KubernetesServiceMapperTest.cs
Labels: ready-to-merge

#5342 Connectivity Test in 1ES hosted pool
  builds/e2e/connectivity.yaml
  builds/e2e/templates/connectivity-deploy.yaml
Labels: ready-to-merge

#5327 Update various RUSTSEC vulnerabilities
  edgelet/Cargo.lock
  edgelet/edgelet-core/Cargo.toml
  mqtt/Cargo.lock
  tools/snitch/Cargo.lock
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#5332 Fix: edgeAgent creates rogue ModuleClients in case of error
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/ModuleConnection.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.IoTHub.Test/ModuleConnectionTest.cs
Labels: ready-to-merge

#5312 Update functions packages (#5239)
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
Labels: ready-to-merge, 1.1

#5353 SDK version from 1.28.0 to 1.28.2
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Microsoft.Azure.Devices.Edge.Agent.Core.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Docker/Microsoft.Azure.Devices.Edge.Agent.Docker.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/Microsoft.Azure.Devices.Edge.Agent.Edgelet.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Microsoft.Azure.Devices.Edge.Agent.Service.csproj
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test/Microsoft.Azure.Devices.Edge.Agent.Docker.E2E.Test.csproj
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test/Microsoft.Azure.Devices.Edge.Agent.Integration.Test.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/Microsoft.Azure.Devices.Edge.Hub.Mqtt.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Microsoft.Azure.Devices.Edge.Hub.Service.csproj
  edge-hub/src/Microsoft.Azure.Devices.Routing.Core/Microsoft.Azure.Devices.Routing.Core.csproj
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/Microsoft.Azure.Devices.Edge.Test/Microsoft.Azure.Devices.Edge.Test.csproj
  test/connectivity/modules/NetworkController/NetworkController.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DeploymentTester/DeploymentTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TestAnalyzer/TestAnalyzer.csproj
  test/modules/TestResultCoordinator/TestResultCoordinator.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#5357 RUSTSEC updates for crossbeam
  edge-modules/edgehub-proxy/Cargo.lock
  edgelet/Cargo.lock
  tools/snitch/Cargo.lock
Labels: ready-to-merge

#5358 using pooled buffers has its own switch instread of 'optimizeForPerformance'
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/MqttModule.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
Labels: ready-to-merge

#5365 Devops Scheduled Test Triggers: Decrease frequency of triggers
  builds/e2e/connectivity.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
Labels: ready-to-merge

#5367 Nested Tests: Convert to staged builds
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
  builds/e2e/nested-longhaul.yaml
  builds/e2e/templates/lock-test-agent.yaml
  builds/e2e/templates/lock-test-agents.yaml
  builds/e2e/templates/nested-deploy-config.yaml
  builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm32.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm64.yaml
  builds/e2e/templates/nested-longhaul-deploy.yaml
  builds/e2e/templates/nested-parent-vm-setup.yaml
  builds/e2e/templates/unlock-test-agent.yaml
  builds/e2e/templates/unlock-test-agents.yaml
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_connectivity_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json
  e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json
  scripts/linux/nested-edge-deploy-agent.sh
  scripts/linux/nestedAgentLock.sh
  scripts/linux/trcE2ETest.sh
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#5334 Devops Service: Auto assign bugs to owners
  tools/IoTEdgeDevOps/DevOpsLib/AgentManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/BugManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/BugWiqlManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildDefinitionId.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/CommitManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/DevOpsAccessSetting.cs
  tools/IoTEdgeDevOps/DevOpsLib/DevOpsLib.csproj
  tools/IoTEdgeDevOps/DevOpsLib/ReleaseManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/UserManagement.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsBuild.cs
  tools/IoTEdgeDevOps/DevOpsLib/VstsModels/VstsUser.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/Program.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/VstsBuildBatchUpdate.cs
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.UpsertVstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/db/dbo.VstsBuild.sql
  tools/IoTEdgeDevOps/VstsPipelineSync/docker/linux-amd64/Dockerfile
Labels: ready-to-merge

#5376 Fix API proxy cache
  edge-modules/api-proxy-module/docker/linux/amd64/Dockerfile
Labels: ready-to-merge

#5381 Create identities for leaf
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
Labels: ready-to-merge

#5389 E2E Tests: Remove legacy method of running specific build
  builds/e2e/templates/e2e-setup.yaml
Labels: ready-to-merge

#5378 Remove rust rpm when building IoTEdge for Mariner
  builds/mariner/SPECS/rust/rust.signatures.json
  builds/mariner/SPECS/rust/rust.spec
  builds/misc/packages.yaml
  edgelet/build/linux/package-mariner.sh
Labels: ready-to-merge

#5393 Test Metrics Collector: Use aspnet base image
  edge-modules/MetricsCollector/docker/linux/amd64/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/MetricsCollector/docker/windows/amd64/Dockerfile
Labels: ready-to-merge

#5392 E2E Tests: Remove legacy method of running specific build (#5389)
  builds/e2e/templates/e2e-setup.yaml
Labels: ready-to-merge

#5333 Update System.Text.Encodings.Web
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
Labels: ready-to-merge

#5314 Remove redundant tests and wait for device to be disconnected (#5244)
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/Cloud2DeviceTest.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/TwinDiffE2ETest.cs
Labels: ready-to-merge

#5400 Fix LongHaul capabilities from accidentally picking up the EFLOW agent
  builds/e2e/longhaul.yaml
Labels: ready-to-merge

#5362 Custom Mqtt Tests: Better support multi-child/single-parent scenario
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json
  mqtt/Cargo.lock
  test/modules/generic-mqtt-tester/Cargo.lock
  test/modules/generic-mqtt-tester/README.md
  test/modules/generic-mqtt-tester/config/default.json
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#5415 Update logging for connectivity test output
  test/connectivity/scripts/connectivityTest.sh
Labels: ready-to-merge

#5430 Nested Tests: Use tls 1.2 for api proxy
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_connectivity_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json
  e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Labels: ready-to-merge

#5434 Nested Tests: Use tls 1.2 for api proxy (#5430)
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_connectivity_mqtt.json
  e2e_deployment_files/nestededge_middleLayer_e2e_amqp.json
  e2e_deployment_files/nestededge_middleLayer_long_haul_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Labels: ready-to-merge

#5390 Fix find_first_block seek logic (#5158)
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge
