Repository Azure/iotedge, pull requests merged in 2021-03, with the labels that each got.

#4516 fix broken links
  kubernetes/doc/create-options.md
Labels: ready-to-merge

#4519 Cherry pick api proxy fix
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/io.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/iotedge_client.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/lib.rs
Labels: ready-to-merge

#4520 Remove references to iiot branches
  builds/checkin/api-proxy.yaml
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/mqtt.yaml
  builds/ci/dotnet.yaml
  builds/ci/edgelet.yaml
  builds/misc/images.yaml
  builds/misc/packages.yaml
  edge-modules/api-proxy-module/build.sh
  scripts/linux/buildAPIProxy.sh
Labels: ready-to-merge

#4521 Temporarily raise quickstart EdgeCA cert's expiry to 30 days.
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
  edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
  edgelet/iotedge/test-files/config/dps-tpm/certd.toml
  edgelet/iotedge/test-files/config/dps-x509/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
  edgelet/iotedge/test-files/config/manual-x509/certd.toml
  edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
  edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
Labels: ready-to-merge

#4518 Fix wrap-around bug
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4523 Fix wrap-around bug (#4518)
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4517 Increase the single node E2E pipeline timeout
  builds/e2e/e2e.yaml
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
Labels: ready-to-merge

#4526 Fix license type in aziot-edge.spec
  edgelet/contrib/centos/aziot-edge.spec
Labels: ready-to-merge

#4528 Enable the Dps Tests
  builds/e2e/e2e.yaml
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
Labels: ready-to-merge

#4534 Revert "use from_state when creating client with clean_session false …
  mqtt/mqtt-bridge/src/client.rs
Labels: ready-to-merge

#4530 Fixing arm64 image
  edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#4527 MQTT Perf Tests improvements.
  builds/misc/mqtt-perf.yaml
  builds/misc/templates/mqtt-perf-setup.yaml
  builds/misc/templates/mqtt-perf-test-case.yaml
Labels: ready-to-merge

#4513 Nested E2E - send message from L3 -> L4
  builds/e2e/templates/e2e-run.yaml
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/modules/Relayer/Program.cs
  test/modules/Relayer/Settings.cs
Labels: ready-to-merge

#4541 Remove unnecessary (IMHO) clippy allowance
  mqtt/edgelet-client/src/lib.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/flush.rs
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
  mqtt/mqtt-broker-tests-util/src/lib.rs
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-generic/src/lib.rs
  mqtt/mqtt-policy/src/lib.rs
  mqtt/mqtt-util/src/lib.rs
  mqtt/mqttd/src/lib.rs
  mqtt/policy/src/lib.rs
Labels: ready-to-merge

#4544 Add an IoT Edge focused doc on packaging changes and the refactoring
  doc/packaging.md
Labels: ready-to-merge

#4365 Update pipeline triggers for release/1.1
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/packages.slow.yaml
  builds/misc/packages.yaml
Labels: ready-to-merge

#4537 Move NestedEdgeEnabled out of experimental features. (#4467)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeCertificateAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ServiceProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
Labels: ready-to-merge

#4547 Fixing E2E test timing out
  edgelet/Cargo.lock
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Labels: ready-to-merge

#4548 Update the "Packaging" link in changelog
  CHANGELOG.md
Labels: ready-to-merge

#4543 Fixing custom image issue
  builds/e2e/templates/e2e-setup.yaml
Labels: ready-to-merge

#4533 Update postrm to delete iotedge user on purge
  edgelet/Cargo.lock
  edgelet/contrib/debian/postrm
  edgelet/contrib/debian/preinst
Labels: ready-to-merge

#4550 Update postrm to delete iotedge user on purge (#4533)
  edgelet/Cargo.lock
  edgelet/contrib/debian/postrm
  edgelet/contrib/debian/preinst
Labels: ready-to-merge

#4539 Fix flaky proptest
  mqtt/mqtt-broker/src/settings/size.rs
Labels: ready-to-merge

#4546 Fix: CloudConnection did not forward close() call to cloud proxy
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/MqttBridgeEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokeredCloudConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/NestedConnectionTrackingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/PrivateAccessor.cs
Labels: ready-to-merge

#4554 Fix DownloadIdentityService for iot-identity-service branches
  scripts/local/test/DownloadIdentityService.ps1
Labels: ready-to-merge

#4555 Fix DownloadIdentityService for iot-identity-service branches
  scripts/local/test/DownloadIdentityService.ps1
Labels: ready-to-merge

#4549 Changing nginx from alpine to ubuntu bionic
  edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
  scripts/linux/buildAPIProxy.sh
Labels: ready-to-merge

#4557 Cherrypick 4530 4543 4549
  builds/e2e/templates/e2e-setup.yaml
  edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
  edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
  scripts/linux/buildAPIProxy.sh
Labels: ready-to-merge

#4542 Make comments in the config.yaml for provisioning and certificates clearer.
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
Labels: ready-to-merge

#4562 Remove unnecessary (IMHO) clippy allowance (#4541)
  mqtt/edgelet-client/src/lib.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/flush.rs
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
  mqtt/mqtt-broker-tests-util/src/lib.rs
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt-edgehub/src/lib.rs
  mqtt/mqtt-generic/src/lib.rs
  mqtt/mqtt-policy/src/lib.rs
  mqtt/mqtt-util/src/lib.rs
  mqtt/mqttd/src/lib.rs
  mqtt/policy/src/lib.rs
Labels: ready-to-merge

#4561 Fix flaky proptest (#4539)
  mqtt/mqtt-broker/src/settings/size.rs
Labels: ready-to-merge

#4575 Remove obsolete DPS CN limitation in README
  tools/CACertificates/README.md
Labels: ready-to-merge

#4569 Fix package purge when aziot-edged is running
  edgelet/contrib/debian/postrm
Labels: ready-to-merge

#4570 Fix package purge when aziot-edged is running
  edgelet/contrib/debian/postrm
Labels: ready-to-merge

#4574 Fix clippy errors in mqtt-broker-tests-util
  builds/checkin/rust-test-modules.yaml
  mqtt/mqtt-broker-tests-util/src/client.rs
Labels: ready-to-merge

#4585 Prepare for Release 1.1.1
  CHANGELOG.md
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#4588 Fix NugetSecurity warning for Long Haul pipeline
  builds/e2e/longhaul.yaml
Labels: ready-to-merge

#4590 Add optional proxy argument to iotedge
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4592 Test dashboard: Don't report multiple nested longhaul pipelines
  tools/IoTEdgeDevOps/DevOpsLib/BuildDefinitionId.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
Labels: ready-to-merge

#4560 Move NestedEdgeEnabled out of experimental features. (#4467) (#4537)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeCertificateAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/authenticators/DeviceScopeTokenAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/ExperimentalFeatures.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ServiceProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeRuntime.cs
Labels: ready-to-merge

#4594 Fix: don't unsubscribe when there is no subscription registered
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
Labels: ready-to-merge

#4595 Add optional proxy argument to iotedge (#4590)
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4599 Bump aziot version
  edgelet/Cargo.lock
Labels: ready-to-merge

#4601 Bump aziot version (#4599)
  edgelet/Cargo.lock
Labels: ready-to-merge

#4598 Add `iotedge config mp` to create a super-config with a manual-provisioning connection string.
  edgelet/Makefile
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/config/linux/template.toml
  edgelet/contrib/debian/postinst
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/iotedge/src/config/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4612 Fix typo in `always_reprovision_on_startup` config.yaml docs.
  edgelet/contrib/config/linux/config.yaml
  edgelet/contrib/config/linux/debian/config.yaml
  edgelet/contrib/config/windows/config.yaml
Labels: ready-to-merge

#4596 Add check up_to_date_config
  edgelet/Cargo.lock
  edgelet/edgelet-core/src/error.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/checks/up_to_date_config.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/error.rs
  edgelet/iotedge/src/main.rs
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#4614 Fix clippy errors in mqtt-broker-tests-util (#4574)
  builds/checkin/rust-test-modules.yaml
  mqtt/mqtt-broker-tests-util/src/client.rs
Labels: ready-to-merge

#4613 Test dashboard: Don't report multiple nested longhaul pipelines (#4592)
  tools/IoTEdgeDevOps/DevOpsLib/BuildDefinitionId.cs
  tools/IoTEdgeDevOps/DevOpsLib/BuildExtension.cs
  tools/IoTEdgeDevOps/DevOpsLibTest/BuildExtensionTest.cs
Labels: ready-to-merge

#4615 Nested Longhaul: Upstream protocol fixes (#4572) (#4591)
  builds/e2e/isa-95-smoke-test.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
  builds/e2e/nested-longhaul.yaml
  builds/e2e/templates/nested-create-identity.yaml
  builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm32.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm64.yaml
  builds/e2e/templates/nested-longhaul-deploy.yaml
  builds/e2e/templates/nested-parent-vm-setup.yaml
Labels: ready-to-merge

#4607 Nested Longhaul: Add debug logging for non-broker case
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
Labels: ready-to-merge

#4616 Add "required" annotation to iotedge-config-mp's `--connection-string` parameter.
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4617 Prepare for Release 1.1.1 (pt2)
  CHANGELOG.md
Labels: ready-to-merge

#4507 Adding event hub long haul mode to trc tests
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/CountingReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Reports/TestResultFilter.cs
  test/modules/TestResultCoordinator/Reports/TwinCountingReportMetadata.cs
  test/modules/TestResultCoordinator/Services/PartitionReceiverHandler.cs
  test/modules/TestResultCoordinator/Settings.cs
Labels: ready-to-merge

#4608 iotedge check improvements for nested edge
  Microsoft.Azure.Devices.Edge.sln
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edgelet/iotedge/src/check/checks/container_connect_upstream.rs
  scripts/linux/buildBranch.sh
Labels: ready-to-merge

#4604 Longhaul: Make log rotation less restrictive on amd64
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  scripts/linux/trcE2ETest.sh
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#4622 Nested Tests: Default dynamic reprovisioning to false
  scripts/linux/nested-edge-deploy-agent.sh
Labels: ready-to-merge

#4629 fix: after disconnect/connect, client twins should be pulled
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxy.cs
Labels: area:edgehub, ready-to-merge

#4632 Add check up_to_date_config (#4596)
  edgelet/Cargo.lock
  edgelet/edgelet-core/src/error.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/checks/up_to_date_config.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/error.rs
  edgelet/iotedge/src/main.rs
  edgelet/support-bundle/src/support_bundle.rs
Labels: ready-to-merge

#4631 Fix RingBuffer initialization logic
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4633 Change i-i-s cargo dependency to release/1.2 branch
  edgelet/Cargo.lock
  edgelet/aziot-edged/Cargo.toml
  edgelet/cert-client/Cargo.toml
  edgelet/edgelet-docker/Cargo.toml
  edgelet/edgelet-http-mgmt/Cargo.toml
  edgelet/edgelet-http-workload/Cargo.toml
  edgelet/identity-client/Cargo.toml
  edgelet/iotedge/Cargo.toml
Labels: ready-to-merge

#4636 Simplify insert check logic in RingBuffer
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4641 Connect with trust bundle
  Microsoft.Azure.Devices.Edge.sln
  edge-modules/iotedge-diagnostics-dotnet/src/Program.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edgelet/iotedge/src/check/checks/container_connect_upstream.rs
  scripts/linux/buildBranch.sh
Labels: ready-to-merge

#4571 Add EFLOW Job to Long Haul Test Pipeline
  builds/e2e/longhaul.yaml
  scripts/linux/runE2ETest.sh
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Labels: ready-to-merge

#4640 Check agent image version
  edgelet/Makefile
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/config/linux/default.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/contrib/debian/postinst
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/iotedge/src/check/checks/check_agent_image.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/checks/pull_agent_from_upstream.rs
  edgelet/iotedge/src/config/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4649 Add test for rare RB init edge case
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4660 Add iotedge system reprovision
  edgelet/Cargo.lock
  edgelet/identity-client/src/client.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4662 Drop messages when device is not in scope and auth mode is Scope (#4540)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/CloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/ServiceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/AuthChainHelpers.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceInvalidStateException.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IConnectionManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IDeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IServiceIdentityHierarchy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/NullDeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/CloudEndpoint.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/EndpointFactory.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ClientTokenCloudConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudConnectionProviderTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/CloudProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/ServiceProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/RetryingCloudProxyTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ServiceIdentityTreeTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/CloudEndpointTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/CloudMessageProcessorTests.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/EndpointFactoryTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/EdgeHubConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokeredCloudConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionEventTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/NestedConnectionTrackingTest.cs
Labels: 1.2, ready-to-merge

#4661 Add iotedge system reprovision (#4660)
  edgelet/Cargo.lock
  edgelet/identity-client/src/client.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4642 Longhaul: Add threshold for device not found
  test/modules/DirectMethodSender/DirectMethodSenderBase.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportGenerator.cs
Labels: ready-to-merge

#4663 Change default quickstart Edge CA expiry to 90 days.
  edgelet/contrib/config/linux/template.toml
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/old_config/mod.rs
Labels: ready-to-merge

#4657 Bump serde-yaml version to 0.8
  edgelet/Cargo.lock
  edgelet/docker-rs/Cargo.toml
  edgelet/iotedge/Cargo.toml
  edgelet/management/Cargo.toml
  edgelet/workload/Cargo.toml
Labels: ready-to-merge

#4664 Fix: CloudConnection did not forward close() call to cloud proxy
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/MqttBridgeEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/BrokeredCloudConnectionTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/NestedConnectionTrackingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/PrivateAccessor.cs
Labels: ready-to-merge

#4666 Fix: throw transient error when edgeHubCore is disconnected from the broker (#4603
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/ConnectionEventTest.cs
Labels: ready-to-merge

#4665 Fix: don't unsubscribe when there is no subscription registered (#4594)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ConnectionManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
Labels: ready-to-merge

#4655 Fix RingBuffer initialization logic (#4631)
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4669 fix: after disconnect/connect, client twins should be pulled (#4629)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudConnectionProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/upstream/BrokeredCloudProxy.cs
Labels: ready-to-merge

#4643 Use unique common name for edged-ca cert when apply'ing super-config.
  edgelet/Cargo.lock
  edgelet/edgelet-http-workload/src/server/cert/mod.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/hostname_checks_common.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/test-files/config/ca-quickstart/certd.toml
  edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
  edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/certd.toml
  edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
  edgelet/iotedge/test-files/config/dps-tpm/certd.toml
  edgelet/iotedge/test-files/config/dps-x509/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
  edgelet/iotedge/test-files/config/manual-x509/certd.toml
  edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
  edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
Labels: ready-to-merge

#4670 Nested Longhaul: Add debug logging for non-broker case (#4607)
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
Labels: ready-to-merge

#4656 Simplify insert check logic in RingBuffer (#4636)
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4672 Nested Tests: Default dynamic reprovisioning to false (#4622)
  scripts/linux/nested-edge-deploy-agent.sh
Labels: ready-to-merge

#4671 Longhaul: Make log rotation less restrictive on amd64 (#4604)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_connectivity_mqtt.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  e2e_deployment_files/nestededge_isa95_smoke_test_BaseDeployment.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  scripts/linux/trcE2ETest.sh
  test/modules/TestResultCoordinator/TestReportUtil.cs
Labels: ready-to-merge

#4673 Longhaul: Add threshold for device not found (#4642)
  test/modules/DirectMethodSender/DirectMethodSenderBase.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportData.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/DirectMethod/DirectMethodLongHaulReportGeneratorTest.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReportGenerator.cs
Labels: ready-to-merge

#4605 TwinTester: Accommodate new exception indicating network failure
  test/modules/TwinTester/TwinAllOperationsInitializer.cs
Labels: ready-to-merge

#4676 Remove leftover unused lint exceptions
  edgelet/aziot-edged/src/app.rs
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/src/watchdog.rs
Labels: ready-to-merge

#4677 Bump serde-yaml version to 0.8 (#4657)
  edgelet/Cargo.lock
  edgelet/docker-rs/Cargo.toml
  edgelet/iotedge/Cargo.toml
  edgelet/management/Cargo.toml
  edgelet/workload/Cargo.toml
Labels: ready-to-merge

#4680 Remove leftover unused lint exceptions (#4676)
  edgelet/aziot-edged/src/app.rs
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/src/watchdog.rs
Labels: ready-to-merge

#4559 Merge Broker and Bridge settings
  doc/EnvironmentVariables.md
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/config/default.json
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/common.rs
  mqtt/mqtt-bridge/tests/config.json
  mqtt/mqtt-bridge/tests/config.ring_buffer.json
  mqtt/mqtt-bridge/tests/integration.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/config/default.json
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-edgehub/tests/settings/config.json
  mqtt/mqtt-edgehub/tests/settings/config.memory.json
  mqtt/mqtt-generic/config/default.json
  mqtt/mqtt-util/src/client_io.rs
  mqtt/mqttd/src/app/edgehub.rs
Labels: ready-to-merge

#4685 TwinTester: Accommodate new exception indicating network failure (#4605)
  test/modules/TwinTester/TwinAllOperationsInitializer.cs
Labels: ready-to-merge

#4341 [k8s] Fix problem with multiple Binds to the same source.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
Labels: ready-to-merge

#4623 TwinTester: Give more time for updates to come in
  test/modules/TwinTester/Settings.cs
Labels: ready-to-merge

#4683 Iotedge system stop
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4690 TwinTester: Give more time for updates to come in (#4623)
  test/modules/TwinTester/Settings.cs
Labels: ready-to-merge

#4691 LongHaul: (CherryPick) Adding event hub long haul mode to trc tests (#4507)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
  test/modules/TestResultCoordinator/Reports/CountingReportMetadata.cs
  test/modules/TestResultCoordinator/Reports/TestReportGeneratorFactory.cs
  test/modules/TestResultCoordinator/Reports/TestResultFilter.cs
  test/modules/TestResultCoordinator/Reports/TwinCountingReportMetadata.cs
  test/modules/TestResultCoordinator/Services/PartitionReceiverHandler.cs
  test/modules/TestResultCoordinator/Settings.cs
Labels: ready-to-merge

#4692 [mqtt] handle RPC sub requests (#4602)
  mqtt/mqtt-bridge/src/upstream/events/remote.rs
  mqtt/mqtt-bridge/src/upstream/rpc/mod.rs
  mqtt/mqtt-bridge/tests/common.rs
  mqtt/mqtt-bridge/tests/integration.rs
  mqtt/mqtt-bridge/tests/rpc.rs
  mqtt/mqtt-broker/benches/dispatch_messages.rs
  mqtt/mqtt-broker/benches/persist_broker_state.rs
Labels: ready-to-merge

#4693 Merge Broker and Bridge settings (#4559)
  doc/EnvironmentVariables.md
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/config/default.json
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/lib.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/common.rs
  mqtt/mqtt-bridge/tests/config.json
  mqtt/mqtt-bridge/tests/config.ring_buffer.json
  mqtt/mqtt-bridge/tests/integration.rs
  mqtt/mqtt-edgehub/Cargo.toml
  mqtt/mqtt-edgehub/config/default.json
  mqtt/mqtt-edgehub/src/settings.rs
  mqtt/mqtt-edgehub/tests/settings/config.json
  mqtt/mqtt-edgehub/tests/settings/config.memory.json
  mqtt/mqtt-generic/config/default.json
  mqtt/mqtt-util/src/client_io.rs
  mqtt/mqttd/src/app/edgehub.rs
Labels: ready-to-merge

#4679 Read `parent_hostname` configuration from aziot
  edgelet/Cargo.lock
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/src/workload.rs
  edgelet/aziot-edged/test/linux/sample_settings.nested.edge.toml
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-core/src/workload.rs
  edgelet/edgelet-docker/src/config.rs
  edgelet/edgelet-docker/src/lib.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedge/src/check/checks/aziot_edged_version.rs
  edgelet/iotedge/src/check/checks/check_agent_image.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_connect_upstream.rs
  edgelet/iotedge/src/check/checks/container_local_time.rs
  edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/checks/well_formed_config.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
Labels: ready-to-merge

#4696 Include release branches into image pipelines.
  builds/misc/images.yaml
Labels: ready-to-merge

#4688 changed sdk references to a custom built version fixing semaphore lock problems
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/Microsoft.Azure.Devices.Edge.Hub.Amqp.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/Microsoft.Azure.Devices.Edge.Hub.Http.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/IotEdgeQuickstart/IotEdgeQuickstart.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DeploymentTester/DeploymentTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TestAnalyzer/TestAnalyzer.csproj
  test/modules/TestResultCoordinator/TestResultCoordinator.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#4703 [cherry pick] Read parent_hostname configuration from aziot (#4679)
  edgelet/Cargo.lock
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/src/workload.rs
  edgelet/aziot-edged/test/linux/sample_settings.nested.edge.toml
  edgelet/edgelet-core/src/module.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-core/src/workload.rs
  edgelet/edgelet-docker/src/config.rs
  edgelet/edgelet-docker/src/lib.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedge/src/check/checks/aziot_edged_version.rs
  edgelet/iotedge/src/check/checks/check_agent_image.rs
  edgelet/iotedge/src/check/checks/connect_management_uri.rs
  edgelet/iotedge/src/check/checks/container_connect_upstream.rs
  edgelet/iotedge/src/check/checks/container_local_time.rs
  edgelet/iotedge/src/check/checks/container_resolve_parent_hostname.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/checks/well_formed_config.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
Labels: ready-to-merge

#4702 Set default agent version to 1.2.0-rc4
  edgelet/contrib/config/linux/default.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/iotedge/src/config/super_config.rs
Labels: ready-to-merge

#4704 Set default agent version to 1.2.0-rc4 (#4702)
  edgelet/contrib/config/linux/default.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/iotedge/src/config/super_config.rs
Labels: ready-to-merge

#4700 Connectivity Tests: Fix log rotation
  scripts/linux/trcE2ETest.sh
Labels: ready-to-merge

#4695 Test Dashboard: Allow longhaul / connectivity pipelines to show with new dashboard queries
  builds/e2e/templates/connectivity-deploy.yaml
  builds/e2e/templates/longhaul-deploy.yaml
Labels: ready-to-merge

#4707 Iotedge system stop (#4683)
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4706 Connectivity Tests: Fix log rotation (#4700)
  scripts/linux/trcE2ETest.sh
Labels: ready-to-merge

#4698 Fixes rare RingBuffer initialization issue (#4649)
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: ready-to-merge

#4710 Fix self-signed edge-ca cert to use its subject name as the issuer name.
  edgelet/Cargo.lock
Labels: ready-to-merge

#4705 Make E2E setup errors actionable for developers.
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4711 Cherry-pick of `iotedge check` and `iotedge config` changes from master.
  edgelet/Cargo.lock
  edgelet/contrib/config/linux/template.toml
  edgelet/edgelet-http-workload/src/server/cert/mod.rs
  edgelet/iotedge/src/check/checks/hostname.rs
  edgelet/iotedge/src/check/checks/mod.rs
  edgelet/iotedge/src/check/checks/parent_hostname.rs
  edgelet/iotedge/src/check/hostname_checks_common.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/old_config/mod.rs
  edgelet/iotedge/src/main.rs
  edgelet/iotedge/test-files/config/ca-quickstart/certd.toml
  edgelet/iotedge/test-files/config/complex-agent-spec/certd.toml
  edgelet/iotedge/test-files/config/dps-no-reprovisioning-flags/certd.toml
  edgelet/iotedge/test-files/config/dps-symmetric-key/certd.toml
  edgelet/iotedge/test-files/config/dps-tpm/certd.toml
  edgelet/iotedge/test-files/config/dps-x509/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string-2/certd.toml
  edgelet/iotedge/test-files/config/manual-connection-string/certd.toml
  edgelet/iotedge/test-files/config/manual-x509/certd.toml
  edgelet/iotedge/test-files/config/moby-runtime-content-trust/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-both-custom/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varlib/certd.toml
  edgelet/iotedge/test-files/config/not-socket-activated-varrun/certd.toml
  edgelet/iotedge/test-files/config/socket-activated-one-custom/certd.toml
Labels: ready-to-merge

#4713 Fix license type in aziot-edge.spec (#4526)
  edgelet/contrib/centos/aziot-edge.spec
Labels: ready-to-merge

#4714 Make E2E setup errors actionable for developers. (#4705)
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4715 Merge api proxy edge hub pr (#4712)
  doc/EnvironmentVariables.md
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Constants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/Extensions/HttpContextExtensions.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProxiedCertificateExtractor.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/IHttpProxiedCertificateExtractor.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/HttpRequestAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Hosting.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Startup.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/HttpModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/HttpProxiedCertificateExtractorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/HttpRequestAuthenticatorTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
  edge-modules/api-proxy-module/Cargo.toml
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/iotedge_client.rs
  edge-modules/api-proxy-module/rust-sdk/azure-iot-mqtt/src/lib.rs
  edge-modules/api-proxy-module/src/main.rs
  edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
  edge-modules/api-proxy-module/src/monitors/config_monitor.rs
  edge-modules/api-proxy-module/src/monitors/config_parser.rs
  edge-modules/api-proxy-module/src/monitors/mod.rs
  edge-modules/api-proxy-module/src/monitors/token_client.rs
  edge-modules/api-proxy-module/src/monitors/token_manager.rs
  edge-modules/api-proxy-module/templates/nginx_default_config.conf
Labels: ready-to-merge

#4716 [MQTT bridge] fix topic mapping (#4630)
  mqtt/mqtt-bridge/src/config_update.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/integration.rs
Labels: 1.2, ready-to-merge

#4538 Introduce nested edge device connection to grandparent verification test
  builds/e2e/templates/e2e-run.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4718 Fix `iotedge config apply` not picking up parent hostname because of serde bug.
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/test-files/config/nested-edge/certd.toml
  edgelet/iotedge/test-files/config/nested-edge/device-id
  edgelet/iotedge/test-files/config/nested-edge/edged.toml
  edgelet/iotedge/test-files/config/nested-edge/identityd.toml
  edgelet/iotedge/test-files/config/nested-edge/keyd.toml
  edgelet/iotedge/test-files/config/nested-edge/super-config.toml
  edgelet/iotedge/test-files/config/nested-edge/tpmd.toml
Labels: ready-to-merge

#4719 Fix `iotedge config apply` not picking up parent hostname because of serde bug. (#4718)
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/test-files/config/nested-edge/certd.toml
  edgelet/iotedge/test-files/config/nested-edge/device-id
  edgelet/iotedge/test-files/config/nested-edge/edged.toml
  edgelet/iotedge/test-files/config/nested-edge/identityd.toml
  edgelet/iotedge/test-files/config/nested-edge/keyd.toml
  edgelet/iotedge/test-files/config/nested-edge/super-config.toml
  edgelet/iotedge/test-files/config/nested-edge/tpmd.toml
Labels: ready-to-merge

#4720 Fix resolving BrokeredCloudProxyDispatcher
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
Labels: ready-to-merge

#4329 Translate hostConfig.PidMode=host into podspec.hostPID=true.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  kubernetes/doc/edge-deployment-to-k8s-translations.md
Labels: ready-to-merge

#4723 Introduce nested edge device connection to grandparent verification test
  builds/e2e/templates/e2e-run.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/EdgeDevice.cs
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/Microsoft.Azure.Devices.Edge.Test/DeviceWithCustomCertificates.cs
  test/Microsoft.Azure.Devices.Edge.Test/Provisioning.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4674 [k8s] Throw non-fatal exception if Mounts missing critical data.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/InvalidMountException.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/deployment/KubernetesDeploymentMapper.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/pvc/KubernetesPvcMapper.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesDeploymentMapperTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/pvc/KubernetesPvcMapperTest.cs
Labels: ready-to-merge

#4697 Import master encryption key in `iotedge config import`
  edgelet/Cargo.lock
  edgelet/edgelet-http-workload/src/server/decrypt.rs
  edgelet/edgelet-http-workload/src/server/encrypt.rs
  edgelet/edgelet-http-workload/src/server/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/test-files/config/README.md
  edgelet/iotedge/test-files/config/imported-master-encryption-key/certd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/device-id
  edgelet/iotedge/test-files/config/imported-master-encryption-key/edged.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/identityd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/keyd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/master-encryption-key
  edgelet/iotedge/test-files/config/imported-master-encryption-key/old-config.yaml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/super-config.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/tpmd.toml
Labels: ready-to-merge

#4728 Import master encryption key in `iotedge config import` (#4697)
  edgelet/Cargo.lock
  edgelet/edgelet-http-workload/src/server/decrypt.rs
  edgelet/edgelet-http-workload/src/server/encrypt.rs
  edgelet/edgelet-http-workload/src/server/mod.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/test-files/config/README.md
  edgelet/iotedge/test-files/config/imported-master-encryption-key/certd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/device-id
  edgelet/iotedge/test-files/config/imported-master-encryption-key/edged.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/identityd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/keyd.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/master-encryption-key
  edgelet/iotedge/test-files/config/imported-master-encryption-key/old-config.yaml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/super-config.toml
  edgelet/iotedge/test-files/config/imported-master-encryption-key/tpmd.toml
Labels: ready-to-merge

#4731 Prepend iotedge-config suggestions with sudo.
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
Labels: ready-to-merge

#4732 Prepend iotedge-config suggestions with sudo. (#4731)
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
Labels: ready-to-merge

#4730 Fix api proxy indirection (#4725)
  edge-modules/api-proxy-module/readme.md
  edge-modules/api-proxy-module/src/monitors/config_parser.rs
Labels: ready-to-merge

#4618 Shorten all k8s watch timeouts.
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/Constants.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/KubernetesEnvironmentOperator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Kubernetes/edgedeployment/EdgeDeploymentOperator.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/modules/KubernetesModule.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.IntegrationTest/KubernetesEnvironmentOperatorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/KubernetesEnvironmentOperatorTest.cs
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Kubernetes.Test/edgedeployment/EdgeDeploymentOperatorTest.cs
  kubernetes/charts/edge-kubernetes/values.yaml
Labels: ready-to-merge

#4729 Document the super-config's agent.config.createOptions value format more clearly.
  edgelet/contrib/config/linux/template.toml
Labels: ready-to-merge

#4733 Fixing broken nested pipeline
  builds/e2e/templates/nested-agent-deploy.yaml
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  scripts/linux/nested-edge-deploy-agent.sh
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4737 [k8s] Update Helm charts and version for beta14
  kubernetes/charts/edge-kubernetes-crd/Chart.yaml
  kubernetes/charts/edge-kubernetes/Chart.yaml
  kubernetes/charts/edge-kubernetes/values.yaml
  versionInfo.json
Labels: ready-to-merge

#4746 Longhaul: Increase direct method DeviceNotFound tolerance
  test/modules/TestResultCoordinator/Reports/DirectMethod/LongHaul/DirectMethodLongHaulReport.cs
Labels: ready-to-merge

#4744 Cherry pick #4733
  builds/e2e/templates/nested-agent-deploy.yaml
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
  scripts/linux/nested-edge-deploy-agent.sh
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/SasManualProvisioningFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/X509ManualProvisioningFixture.cs
Labels: ready-to-merge

#4747 Nested E2E - send message from L3 -> L4 (#4513)
  builds/e2e/templates/e2e-run.yaml
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  test/Microsoft.Azure.Devices.Edge.Test/Device.cs
  test/modules/Relayer/Program.cs
  test/modules/Relayer/Settings.cs
Labels: ready-to-merge

#4741 Remove files created by previous pipeline runs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
Labels: ready-to-merge

#4749 Remove files created by previous pipeline runs
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/ManualProvisioningFixture.cs
Labels: ready-to-merge

#4743 Document the super-config's agent.config.createOptions value format more clearly. (#4729)
  edgelet/contrib/config/linux/template.toml
Labels: ready-to-merge

#4742 Fix check-agent-image-version check for nested Edge scenarios.
  edgelet/edgelet-docker/src/config.rs
  edgelet/iotedge/src/check/checks/check_agent_image.rs
Labels: ready-to-merge

#4748 Fix pipeline deployment image
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_middleLayerBaseDeployment_mqtt.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_amqp.json
  e2e_deployment_files/nestededge_topLayerBaseDeployment_mqtt.json
Labels: ready-to-merge
