Repository Azure/iotedge, pull requests merged in 2021-04, with the labels that each got.

#4750 Fix check-agent-image-version check for nested Edge scenarios. (#4742)
  edgelet/edgelet-docker/src/config.rs
  edgelet/iotedge/src/check/checks/check_agent_image.rs
Labels: ready-to-merge

#4722 Cache device provisioning state
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
Labels: ready-to-merge

#4740 Remove references to 'iotedged' from `iotedge` help text
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4755 [cherry pick] remove 'iotedged' from help text (#4740)
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4708 change default direct method sender interval to 10s
  test/modules/DirectMethodSender/config/appsettings.json
Labels: ready-to-merge

#4726 Update iotedge check for version 1.2.0
  edgelet/iotedge/src/check/checks/aziot_edged_version.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/lib.rs
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4756 Fix ws auth with cert over ApiProxy
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpWebSocketListener.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IWebSocketListener.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProxiedCertificateExtractor.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/HttpRequestAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
Labels: ready-to-merge

#4735 Fix getDeviceAndModuleOnBehalfOf to check if target device is in scope
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Constants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/DeviceScopeController.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
Labels: 1.2, ready-to-merge

#4761 Set iothub hostname (#4758)
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
Labels: ready-to-merge

#4764 fix pipeline config (#4763)
  scripts/linux/nested-edge-deploy-agent.sh
Labels: ready-to-merge

#4766 Cache device provisioning state (#4722)
  edgelet/aziot-edged/src/error.rs
  edgelet/aziot-edged/src/lib.rs
Labels: ready-to-merge

#4739 Registry API On-behalf-of calls auth check fix
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/RegistryControllerTest.cs
Labels: 1.2, ready-to-merge

#4762 Send connection device Id information on twin change notifications
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpMessageConverter.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/SystemProperties.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/routing/RoutingEdgeHub.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/ProtocolGatewayMessageConverter.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/AmqpMessageConverterTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceMessageHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/routing/RoutingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Mqtt.Test/ProtocolGatewayMessageConverterTest.cs
Labels: 1.2, ready-to-merge

#4767 Fix ws auth with cert over ApiProxy (#4756)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpWebSocketListener.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IWebSocketListener.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/HttpProxiedCertificateExtractor.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/HttpRequestAuthenticator.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/middleware/WebSocketHandlingMiddleware.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttWebSocketListener.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/WebSocketHandlingMiddlewareTest.cs
Labels: 1.2, ready-to-merge

#4768 Fix API proxy race condition
  edge-modules/api-proxy-module/src/main.rs
  edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
Labels: ready-to-merge

#4770 Update cargo dependency for iot-identity-service
  edgelet/Cargo.lock
Labels: ready-to-merge

#4773 Add iotedge user to systemd-journal group
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/preinst
Labels: ready-to-merge

#4736 Update test pipelines to be triggered by release/1.2
  builds/checkin/api-proxy.yaml
  builds/checkin/dotnet.yaml
  builds/checkin/edgelet.yaml
  builds/checkin/mqtt.yaml
  builds/checkin/rust-test-modules.yaml
  builds/ci/dotnet.yaml
  builds/ci/edgelet.yaml
  builds/e2e/e2e.yaml
  builds/e2e/isa-95-smoke-test.yaml
  builds/e2e/nested-e2e.yaml
  builds/misc/images.yaml
Labels: ready-to-merge

#4759 `aziotctl system` improvements + `system status` formatting changes
  edgelet/Cargo.lock
  edgelet/iotedge/src/check/checks/up_to_date_config.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4775 [cherry pick] `aziotctl system` improvements + `system status` formatting changes (#4759)
  edgelet/Cargo.lock
  edgelet/iotedge/src/check/checks/up_to_date_config.rs
  edgelet/iotedge/src/system.rs
Labels: ready-to-merge

#4771 Fix links in help message
  edgelet/Cargo.lock
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4765 Turning of batching for incoming amqp messages to gain faster feedback to the sender
  doc/EnvironmentVariables.md
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/EventsLinkHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/LinkHandlerProvider.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/MethodReceivingLinkHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/ReceivingLinkHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/linkhandlers/TwinReceivingLinkHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/DependencyManager.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/AmqpModule.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/EventsLinkHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/LinkHandlerProviderTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/ReceivingLinkHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Amqp.Test/TwinReceivingLinkHandlerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.E2E.Test/DependencyManager.cs
Labels: ready-to-merge

#4769 Update iotedge check for version 1.2.0 (#4726)
  edgelet/Cargo.lock
  edgelet/iotedge/src/check/checks/aziot_edged_version.rs
  edgelet/iotedge/src/check/mod.rs
  edgelet/iotedge/src/lib.rs
  edgelet/iotedge/src/main.rs
Labels: ready-to-merge

#4760 Add edgeHub identity to the scopes cache at the startup.
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
Labels: ready-to-merge

#4778 Add edgeHub identity to the scopes cache at the startup. (#4760)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/CommonModule.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/modules/RoutingModule.cs
Labels: ready-to-merge

#4779 Update test pipelines to be triggered by release/1.2 (pt2)
  builds/misc/packages.yaml
Labels: ready-to-merge

#4774 Add iotedge user to systemd-journal group (#4773)
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/preinst
Labels: ready-to-merge

#4772 Fix API proxy race condition (#4768)
  edge-modules/api-proxy-module/src/main.rs
  edge-modules/api-proxy-module/src/monitors/certs_monitor.rs
Labels: ready-to-merge

#4776 Format error message in registry controller
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
Labels: 1.2, ready-to-merge

#4727 Test Dashboard: Update dashboards
  tools/IoTEdgeDevOps/TestDashboard/dashboards/Azure Dev Ops Build Status-1617126407442.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/Home-1617123071752.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/TRC Longhaul Report Details-1617126436590.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/[Deprecated] Azure Dev Ops Old E2E Status-1617126383074.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/[Deprecated] Old E2E Test Run Details-1617126390106.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/[Deprecated] Quarantined Tests-1617126399569.json
  tools/IoTEdgeDevOps/TestDashboard/dashboards/[release_1.1] Longhaul_Stress Report Details-1617126537852.json
Labels: ready-to-merge

#4786 Set auto_reprovisioning_mode to AlwaysOnStartup in tests
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
Labels: ready-to-merge

#4787 Set auto_reprovisioning_mode to AlwaysOnStartup in tests
  smoke/IotEdgeQuickstart/details/IotedgedLinux.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/EdgeDaemon.cs
Labels: ready-to-merge

#4745 [mqtt] filter out publication duplicates in MessageLoader
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/persist/publication_store.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/test.rs
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/test.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
Labels: area:mqtt

#4781 fix: multiple edgeHub children mismatched leaf device subscriptions
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/ClientConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/EdgeHubConnection.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/HubCoreEventIds.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/ConnectionInfo.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/DeviceMessageHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/IConnectionInfo.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/IDeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/device/NullConnectionInfo.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/DeviceProxy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/IConnectionRegistry.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/ConnectionHandler.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/handlers/SubscriptionChangeHandler.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/NestedConnectionTrackingTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/SubscriptionChangeHandlerTest.cs
Labels: ready-to-merge

#4791 Prepare for Release 1.2.0
  CHANGELOG.md
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/config/linux/default.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/contrib/debian/control
  edgelet/iotedge/src/config/super_config.rs
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#4790 [mqtt] egress pump errors out when either persist or publish error occurred
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
Labels: 1.2, area:mqtt, ready-to-merge

#4795 Updating base image
  edge-modules/api-proxy-module/docker/linux/arm32v7/Dockerfile
  edge-modules/api-proxy-module/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#4798 Fix for expired CA certificate not renewing
  edgelet/edgelet-http-workload/src/server/cert/mod.rs
Labels: ready-to-merge

#4799 Fix for expired CA certificate not renewing (#4798)
  edgelet/edgelet-http-workload/src/server/cert/mod.rs
Labels: ready-to-merge

#4801 Update i-i-s dependency
  edgelet/Cargo.lock
Labels: ready-to-merge

#4802 Update i-i-s dependency
  edgelet/Cargo.lock
Labels: ready-to-merge

#4803 [mqtt] Filter out publication duplicates in MessageLoader (#4745)
  mqtt/mqtt-bridge/src/bridge.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/persist/publication_store.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/memory/test.rs
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/test.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
Labels: area:mqtt, ready-to-merge

#4804 [mqtt] egress pump errors out when either persist or publish error occurred (#4790)
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/src/persist/loader.rs
  mqtt/mqtt-bridge/src/persist/mod.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
Labels: area:mqtt, ready-to-merge

#4788 Update bridge config validation.
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BridgeConfig.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BrokerConfigValidator.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/config/BrokerPropertiesValidatorTest.cs
  mqtt/mqtt-bridge/src/config_update.rs
  mqtt/mqtt-bridge/src/controller/bridges.rs
  mqtt/mqtt-bridge/src/controller/mod.rs
Labels: ready-to-merge

#4809 Fix usage of edgeAgent from context.json
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Labels: ready-to-merge

#4808 Update ARM Base Image Security Patch
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#4811 Update the dev version to 1.2
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/config/linux/default.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/contrib/debian/control
  edgelet/iotedge/src/config/super_config.rs
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#4805 Update ARM Base Image Security Patch
  edge-agent/docker/linux/arm32v7/Dockerfile
  edge-agent/docker/linux/arm64v8/Dockerfile
  edge-hub/docker/linux/arm32v7/Dockerfile
  edge-hub/docker/linux/arm64v8/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm32v7/Dockerfile
  edge-modules/MetricsCollector/docker/linux/arm64v8/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/linux/arm64v8/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm32v7/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/linux/arm64v8/Dockerfile
  mqtt/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/linux/arm64v8/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/linux/arm64v8/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/linux/arm64v8/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/linux/arm64v8/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/linux/arm64v8/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/linux/arm64v8/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/linux/arm64v8/Dockerfile
  test/modules/NumberLogger/docker/linux/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/linux/arm64v8/Dockerfile
  test/modules/Relayer/docker/linux/arm32v7/Dockerfile
  test/modules/Relayer/docker/linux/arm64v8/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/linux/arm64v8/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/linux/arm64v8/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/linux/arm64v8/Dockerfile
  test/modules/TwinTester/docker/linux/arm32v7/Dockerfile
  test/modules/TwinTester/docker/linux/arm64v8/Dockerfile
  test/modules/load-gen/docker/linux/arm32v7/Dockerfile
  test/modules/load-gen/docker/linux/arm64v8/Dockerfile
Labels: ready-to-merge

#4810 Fix usage of edgeAgent from context.json
  test/Microsoft.Azure.Devices.Edge.Test.Common/DaemonConfiguration.cs
  test/Microsoft.Azure.Devices.Edge.Test/SetupFixture.cs
Labels: ready-to-merge

#4817 EdgeHub: Add caching to TokenProvider
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/ClientTokenProvider.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/ClientTokenProviderTest.cs
Labels: 1.2, ready-to-merge

#4822 update http client timeout for scope sync
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs
Labels: ready-to-merge

#4820 Prepare for Release 1.2.0 (pt.2)
  CHANGELOG.md
Labels: ready-to-merge

#4806 Update rust toolchain to 1.51
  edge-hub/watchdog/rust-toolchain
  edge-modules/api-proxy-module/Cargo.lock
  edge-modules/api-proxy-module/rust-toolchain
  mqtt/edgelet-client/src/workload/models/sign_request.rs
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-bridge/src/settings.rs
  mqtt/mqtt-bridge/tests/common.rs
  mqtt/mqtt-broker-tests-util/src/lib.rs
  mqtt/mqtt-broker/src/broker.rs
  mqtt/mqtt-broker/src/tls.rs
  mqtt/mqttd/src/app/generic.rs
  mqtt/rust-toolchain
  test/modules/generic-mqtt-tester/rust-toolchain
  test/modules/generic-mqtt-tester/src/lib.rs
  test/rust-test-util/test-result-reporting-client/src/lib.rs
Labels: ready-to-merge

#4823 [mqtt] remove some stale clippy allows
  mqtt/mqtt-bridge/src/persist/waking_state/mod.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
  mqtt/mqtt-bridge/src/upstream/rpc/local.rs
Labels: area:mqtt, ready-to-merge

#4827 Update base image update script to not include `generic-mqtt-tester` base image.
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#4826 [fix] check for empty string while processing manifest trust bundle
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Service/Program.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#4682 Longhaul: Filter duplicate results in relayer
  test/modules/Relayer/MessageHandlerContext.cs
  test/modules/Relayer/Program.cs
  test/modules/Relayer/Settings.cs
Labels: ready-to-merge

#4831 Longhaul: Filter duplicate results in relayer (#4682)
  test/modules/Relayer/MessageHandlerContext.cs
  test/modules/Relayer/Program.cs
  test/modules/Relayer/Settings.cs
Labels: ready-to-merge

#4825 [mqtt] Ring buffer write succeeds when no space to fit a new insert
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/error.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
Labels: area:mqtt, ready-to-merge

#4832 Update base image update script to not include `generic-mqtt-tester`
  tools/BaseImageUpdate/baseImage.ps1
Labels: ready-to-merge

#4834 Prepare for Release 1.1.2
  CHANGELOG.md
  versionInfo.json
Labels: ready-to-merge

#4814 E2E Test for Bridge config update.
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/MqttBridgeConfig.cs
Labels: ready-to-merge

#4839 Longhaul: Run with debug logs for edge agent (#4821)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
Labels: ready-to-merge

#4838 Devguide: Fix error in docs for local edgehub build
  doc/devguide.md
Labels: ready-to-merge

#4841 Update i-i-s dependency
  edgelet/Cargo.lock
Labels: ready-to-merge

#4837 [mqtt] upgrade mockall crate
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/Cargo.toml
  mqtt/mqtt-bridge/src/client.rs
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/pump/egress.rs
  mqtt/mqtt-bridge/src/pump/ingress.rs
  mqtt/mqtt-bridge/src/pump/messages.rs
  mqtt/mqtt-bridge/src/pump/mod.rs
  mqtt/mqtt-bridge/src/upstream/events/local.rs
  mqtt/mqtt-bridge/src/upstream/events/remote.rs
Labels: area:mqtt, ready-to-merge

#4852 [mqtt] upgrade percent-encoding to v2
  mqtt/Cargo.lock
  mqtt/edgelet-client/Cargo.toml
  mqtt/edgelet-client/src/lib.rs
  mqtt/edgelet-client/src/workload/client.rs
  mqtt/mqtt-util/Cargo.toml
  mqtt/mqtt-util/src/client_io.rs
Labels: area:mqtt, ready-to-merge

#4851 [mqtt] Make tracing looks like edgehub logs again
  mqtt/Cargo.lock
  mqtt/mqttd/Cargo.toml
  mqtt/mqttd/src/tracing/edgehub.rs
  mqtt/mqttd/src/tracing/format.rs
  mqtt/mqttd/src/tracing/mod.rs
Labels: area:mqtt, ready-to-merge

#4684 TestResultCoordinator: Explicitly fail for duplicate expected results
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
Labels: ready-to-merge

#4863 TestResultCoordinator: Explicitly fail for duplicate expected results (#4684)
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/TwinCountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
Labels: ready-to-merge

#4868 Longhaul: Track misordered actual results (#4862)
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportGeneratorTest.cs
  test/modules/Modules.Test/TestResultCoordinator/Reports/CountingReportTest.cs
  test/modules/Modules.Test/TestResultCoordinator/TestReportUtilTest.cs
  test/modules/TestResultCoordinator/Reports/CountingReport.cs
  test/modules/TestResultCoordinator/Reports/CountingReportGenerator.cs
Labels: ready-to-merge

#4854 Fix Windows construction of identity cert PKCS#12 blob to not leak keys to disk.
  edgelet/edgelet-http/Cargo.toml
  edgelet/edgelet-http/src/lib.rs
  edgelet/edgelet-http/src/windows.rs
  edgelet/iotedge-proxy/src/routine.rs
  edgelet/kube-client/examples/pod-list.rs
Labels: ready-to-merge

#4453 Re-enable E2E proxy test
  builds/e2e/e2e.yaml
  builds/e2e/proxy/configure_runner.sh
  builds/e2e/templates/e2e-run.yaml
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
  test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Labels: ready-to-merge

#4857 E2E: Add regression test for custom mqtt topics
  builds/e2e/templates/e2e-setup.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/ModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/MqttBrokerUtil.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
  test/README.md
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4833 Delete all containers after reprovision
  edgelet/iotedged/src/lib.rs
Labels: ready-to-merge

#4869 [mqtt] generic-mqtt-tester tokio1 upgrade
  test/modules/generic-mqtt-tester/Cargo.lock
  test/modules/generic-mqtt-tester/Cargo.toml
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/main.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/tester.rs
  test/rust-test-util/test-result-reporting-client/Cargo.toml
Labels: ready-to-merge

#4873 Resolve security concern in logging
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Logger.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/LoggerTest.cs
Labels: ready-to-merge

#4876 Remove Debian 8 build/package logic
  builds/misc/packages.yaml
  edgelet/Makefile
  edgelet/build/linux/docker/cross-compile/Dockerfile.debian8.aarch64-unknown-linux-gnu
  edgelet/build/linux/docker/cross-compile/Dockerfile.debian8.armv7-unknown-linux-gnueabi
  edgelet/build/linux/docker/cross-compile/Dockerfile.debian8.x86_64-unknown-linux-gnu
  edgelet/build/linux/docker/cross-compile/README.md
  edgelet/build/linux/docker/cross-compile/debian8/build_amd64_container.sh
  edgelet/build/linux/docker/cross-compile/debian8/build_arm64_toolchain_container.sh
  edgelet/build/linux/docker/cross-compile/debian8/build_arm_toolchain_container.sh
  edgelet/build/linux/docker/cross-compile/debian8/curl.sh
  edgelet/build/linux/docker/cross-compile/debian8/openssl.sh
  edgelet/build/linux/package.sh
  edgelet/contrib/debian8/install
  edgelet/contrib/debian8/postinst
  edgelet/contrib/debian8/postrm
  edgelet/contrib/debian8/rules
  edgelet/doc/devguide.md
Labels: ready-to-merge

#4860 Bump serde-yaml version to 0.8
  edge-modules/edge-dashboard/Cargo.lock
  edge-modules/edgehub-proxy/Cargo.lock
  edgelet/Cargo.lock
  edgelet/docker-rs/Cargo.toml
  edgelet/external-provisioning/Cargo.toml
  edgelet/management/Cargo.toml
  edgelet/workload/Cargo.toml
  tools/snitch/Cargo.lock
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#4882 Allow release image pipeline to use a custom CR (#3507)
  builds/misc/images-release.yaml
Labels: ready-to-merge

#4877 Migrate Azure Monitor project to our repository.
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  e2e_deployment_files/connectivity_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/long_haul_deployment.template.windows.json
  e2e_deployment_files/stress_deployment.template.json
  e2e_deployment_files/stress_deployment.template.windows.json
  edge-modules/azure-monitor/docker/linux/amd64/Dockerfile
  edge-modules/azure-monitor/docker/linux/arm32v7/Dockerfile
  edge-modules/azure-monitor/docker/linux/arm64v8/Dockerfile
  edge-modules/azure-monitor/docker/manifest.yaml.template
  edge-modules/azure-monitor/docker/windows/amd64/Dockerfile
  edge-modules/azure-monitor/src/CertificateGenerator/CertGenerator.cs
  edge-modules/azure-monitor/src/Constants.cs
  edge-modules/azure-monitor/src/ExampleDeployment.json
  edge-modules/azure-monitor/src/FixedSetTableUpload/AzureFixedSetTable.cs
  edge-modules/azure-monitor/src/FixedSetTableUpload/FixedSetTableUpload.cs
  edge-modules/azure-monitor/src/IMetricsPublisher.cs
  edge-modules/azure-monitor/src/IotHubUpload/IotHubUpload.cs
  edge-modules/azure-monitor/src/LoggerUtil.cs
  edge-modules/azure-monitor/src/Metric.cs
  edge-modules/azure-monitor/src/MetricFilter.cs
  edge-modules/azure-monitor/src/MetricsScrapeAndUpload.cs
  edge-modules/azure-monitor/src/MetricsScraper.cs
  edge-modules/azure-monitor/src/Microsoft.Azure.Devices.Edge.Azure.Monitor.csproj
  edge-modules/azure-monitor/src/Program.cs
  edge-modules/azure-monitor/src/PrometheusMetricsParser.cs
  edge-modules/azure-monitor/src/README.md
  edge-modules/azure-monitor/src/Settings.cs
  edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/MetricFilterTests.cs
  edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/MetricTest.cs
  edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test.csproj
  edge-modules/azure-monitor/tests/Microsoft.Azure.Devices.Edge.Azure.Monitor.Test/PrometheusMetricParserTest.cs
  scripts/linux/buildBranch.sh
  scripts/windows/build/Publish-Branch.ps1
Labels: ready-to-merge

#4875 Nested E2E: Add filters for broker-specific tests
  builds/e2e/templates/e2e-run.yaml
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
  test/Microsoft.Azure.Devices.Edge.Test/MqttBridgeConfig.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
Labels: ready-to-merge

#4890 E2E: Port recent changes
  builds/e2e/e2e.yaml
  builds/e2e/proxy/configure_runner.sh
  builds/e2e/templates/e2e-run.yaml
  builds/e2e/templates/e2e-setup.yaml
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Edgelet/version_2020_07_07/ModuleManagementHttpClient.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/EdgeConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/HubModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test.Common/config/ModuleConfigBuilder.cs
  test/Microsoft.Azure.Devices.Edge.Test/AuthorizationPolicy.cs
  test/Microsoft.Azure.Devices.Edge.Test/EdgeAgentDirectMethods.cs
  test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
  test/Microsoft.Azure.Devices.Edge.Test/IoTEdgeCheck.cs
  test/Microsoft.Azure.Devices.Edge.Test/MqttBridgeConfig.cs
  test/Microsoft.Azure.Devices.Edge.Test/PlugAndPlay.cs
  test/Microsoft.Azure.Devices.Edge.Test/PriorityQueues.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/Context.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/MqttBrokerUtil.cs
  test/Microsoft.Azure.Devices.Edge.Test/helpers/TestResultCoordinatorUtil.cs
  test/README.md
  test/modules/generic-mqtt-tester/src/lib.rs
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/message_initiator.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4881 [E2E]: Enable aziot-edge install from Microsoft prod
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#4856 Update functions to 3.0
  CodeCoverage.runsettings
  builds/checkin/dotnet.yaml
  builds/ci/dotnet.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/templates/install-dotnet2.yaml
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-modules/functions/samples/README.md
  edge-modules/functions/samples/docker/linux/amd64/Dockerfile
  edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
  edge-modules/functions/samples/docker/windows/amd64/Dockerfile
  scripts/linux/buildBranch.sh
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge

#4883 Custom Mqtt Test Module: Add Initiate and Receive modes
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4898 Revert "Update functions to 3.0"
  CodeCoverage.runsettings
  builds/checkin/dotnet.yaml
  builds/ci/dotnet.yaml
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/templates/install-dotnet2.yaml
  edge-modules/functions/samples/EdgeHubTrigger-Csharp/EdgeHubTriggerCSharp.csproj
  edge-modules/functions/samples/README.md
  edge-modules/functions/samples/docker/linux/amd64/Dockerfile
  edge-modules/functions/samples/docker/linux/arm32v7/Dockerfile
  edge-modules/functions/samples/docker/windows/amd64/Dockerfile
  scripts/linux/buildBranch.sh
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge

#4894 Custom Mqtt Test Module: Add Initiate and Receive modes (#4883)
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  test/modules/generic-mqtt-tester/src/message_channel.rs
  test/modules/generic-mqtt-tester/src/settings.rs
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4904 Fix Edge CA and module cert CSRs to use version 0 (v1) instead of non-existent version 2 (v3).
  edgelet/Cargo.lock
  edgelet/edgelet-http-workload/src/server/cert/mod.rs
Labels: ready-to-merge

#4887 Registry API On-behalf-of calls auth check fix #4739
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/controllers/RegistryController.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/RegistryControllerTest.cs
Labels: ready-to-merge

#4906 iotedge config apply: fix auth certs for EST-issued Edge CA
  edgelet/Cargo.lock
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/test-files/config/ca-certs-est/certd.toml
  edgelet/iotedge/test-files/config/ca-certs-est/keyd.toml
Labels: ready-to-merge

#4900 Update the KeyVault for Test pipelines
  builds/e2e/connectivity.yaml
  builds/e2e/isa-95-smoke-test.yaml
  builds/e2e/longhaul.yaml
  builds/e2e/nested-connectivity.yaml
  builds/e2e/nested-e2e.yaml
  builds/e2e/templates/nested-create-identity.yaml
  builds/e2e/templates/nested-deploy-config.yaml
  builds/e2e/templates/nested-get-secrets.yaml
  builds/e2e/templates/nested-longhaul-deploy-amd64.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm32.yaml
  builds/e2e/templates/nested-longhaul-deploy-arm64.yaml
Labels: ready-to-merge

#4893 Metrics transform option
  edge-agent/test/Microsoft.Azure.Devices.Edge.Agent.Edgelet.Docker.Test/CombinedEdgeletConfigProviderTest.cs
  edge-modules/azure-monitor/src/ExampleDeployment.json
  edge-modules/azure-monitor/src/IotHubUpload/IotHubUpload.cs
  edge-modules/azure-monitor/src/README.md
  edge-modules/azure-monitor/src/Settings.cs
Labels: ready-to-merge

#4915 Update bridge config validation. (#4788)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BridgeConfig.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/config/BrokerConfigValidator.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/config/BrokerPropertiesValidatorTest.cs
  mqtt/mqtt-bridge/src/config_update.rs
  mqtt/mqtt-bridge/src/controller/bridges.rs
  mqtt/mqtt-bridge/src/controller/mod.rs
Labels: ready-to-merge

#4913 Custom Mqtt Test Module: Restore E2E tests
  test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
  test/modules/generic-mqtt-tester/README.md
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4908 Device scope cache refresh (#4840)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/DeviceScopeIdentitiesCache.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/IServiceIdentityHierarchy.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityDictionary.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/ServiceIdentityTree.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/identity/service/ServiceIdentity.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ConnectionManagerTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/DeviceScopeIdentitiesCacheTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Core.Test/ServiceIdentityTreeTest.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.Http.Test/DeviceScopeControllerTest.cs
Labels: 1.2, ready-to-merge

#4901 Longhaul: Remove connectivity specific `VerificationDelay` from TRC env
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  scripts/linux/trcE2ETest.sh
Labels: ready-to-merge

#4919 Custom Mqtt Test Module: Restore E2E tests (#4913)
  test/Microsoft.Azure.Devices.Edge.Test/GenericMqtt.cs
  test/modules/generic-mqtt-tester/README.md
  test/modules/generic-mqtt-tester/src/tester.rs
Labels: ready-to-merge

#4920 Added consistent grammar to notes section
  doc/devguide.md
Labels: ready-to-merge

#4846 Adding manifest trust bundle in settings & super config
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/Constants.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Constants.cs
  edgelet/aziot-edged/src/lib.rs
  edgelet/aziot-edged/test/linux/sample_settings.edge.ca.id.toml
  edgelet/contrib/config/linux/template.toml
  edgelet/edgelet-core/src/lib.rs
  edgelet/edgelet-core/src/settings.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-docker/src/settings.rs
  edgelet/edgelet-http/src/version.rs
  edgelet/edgelet-test-utils/src/module.rs
  edgelet/iotedge/src/config/apply.rs
  edgelet/iotedge/src/config/import/mod.rs
  edgelet/iotedge/src/config/mp.rs
  edgelet/iotedge/src/config/super_config.rs
  edgelet/iotedge/test-files/config/manifest-trust-bundle/certd.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/device-id
  edgelet/iotedge/test-files/config/manifest-trust-bundle/edged.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/identityd.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/keyd.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/super-config.toml
  edgelet/iotedge/test-files/config/manifest-trust-bundle/tpmd.toml
Labels: ready-to-merge

#4907 update http client timeout for scope sync (#4822)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.CloudProxy/NestedDeviceScopeApiClient.cs
Labels: ready-to-merge

#4927 Longhaul: Remove connectivity specific `VerificationDelay` from TRC (#4901)
  e2e_deployment_files/long_haul_deployment.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_amqp.template.json
  e2e_deployment_files/nestededge_bottomLayerBaseDeployment_long_haul_mqtt.template.json
  scripts/linux/trcE2ETest.sh
Labels: ready-to-merge

#4928 Build Images Pipeline: Additional job for rust test modules (#4916)
  builds/misc/images-release.yaml
  builds/misc/images.yaml
  builds/misc/templates/build-broker-watchdog.yaml
  builds/misc/templates/consolidate-build-artifacts.yaml
  builds/misc/templates/rust-test-module-build.yaml
  builds/misc/templates/rust-test-module-images.yaml
  scripts/linux/consolidate-build-artifacts.sh
Labels: ready-to-merge
