Repository Azure/iotedge, pull requests merged in 2022-02, with the labels that each got.

#6019 remove bouncy castle dependency from edgeHub
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/EdgeHubScopeResultHelpers.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeCertificateAuthenticatorTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/certificate/CertificateHelperTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/edged/WorkloadClientTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/workloadtestserver/WorkloadTestImplementation.cs
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/Program.cs
Labels: ready-to-merge

#6062 cherrypick: remove bouncy castle dependency from edgeHub #6019
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Http/EdgeHubScopeResultHelpers.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeCertificateAuthenticatorTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/certificate/CertificateHelperTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/edged/WorkloadClientTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/workloadtestserver/WorkloadTestImplementation.cs
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/Program.cs
Labels: ready-to-merge

#6074 Clean up comments
  builds/e2e/e2e-release.yaml
  test/Microsoft.Azure.Devices.Edge.Test.Common/linux/PackageManagement.cs
Labels: ready-to-merge

#6075 Prepare for release 1.1.10
  CHANGELOG.md
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#6065 cherry pick: removing bouncy castle #6019
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Core/planners/HealthRestartPlanner.cs
  edge-hub/test/Microsoft.Azure.Devices.Edge.Hub.CloudProxy.Test/DeviceScopeCertificateAuthenticatorTest.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/Microsoft.Azure.Devices.Edge.Util.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/CertificateHelper.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test.Common/Microsoft.Azure.Devices.Edge.Util.Test.Common.csproj
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/certificate/CertificateHelperTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/edged/WorkloadClientTest.cs
  edge-util/test/Microsoft.Azure.Devices.Edge.Util.Test/workloadtestserver/WorkloadTestImplementation.cs
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/Program.cs
Labels: ready-to-merge

#6080 Merge OS patch into LTS
  CHANGELOG.md
  edge-agent/docker/windows/amd64/Dockerfile
  edge-agent/docker/windows/arm32v7/Dockerfile
  edge-agent/docker/windows/arm32v7/base/Dockerfile
  edge-hub/docker/windows/amd64/Dockerfile
  edge-hub/docker/windows/arm32v7/Dockerfile
  edge-hub/docker/windows/arm32v7/base/Dockerfile
  edge-modules/MetricsCollector/docker/windows/amd64/Dockerfile
  edge-modules/MetricsCollector/docker/windows/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/windows/amd64/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/Dockerfile
  edge-modules/SimulatedTemperatureSensor/docker/windows/arm32v7/base/Dockerfile
  edge-modules/azure-monitor/docker/windows/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/amd64/Dockerfile
  edge-modules/iotedge-diagnostics-dotnet/docker/windows/arm32v7/Dockerfile
  test/connectivity/modules/NetworkController/docker/windows/amd64/Dockerfile
  test/connectivity/modules/NetworkController/docker/windows/arm32v7/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/windows/amd64/Dockerfile
  test/modules/CloudToDeviceMessageTester/docker/windows/arm32v7/Dockerfile
  test/modules/DeploymentTester/docker/windows/amd64/Dockerfile
  test/modules/DeploymentTester/docker/windows/arm32v7/Dockerfile
  test/modules/DirectMethodReceiver/docker/windows/amd64/Dockerfile
  test/modules/DirectMethodReceiver/docker/windows/arm32v7/Dockerfile
  test/modules/DirectMethodSender/docker/windows/amd64/Dockerfile
  test/modules/DirectMethodSender/docker/windows/arm32v7/Dockerfile
  test/modules/EdgeHubRestartTester/docker/windows/amd64/Dockerfile
  test/modules/EdgeHubRestartTester/docker/windows/arm32v7/Dockerfile
  test/modules/MetricsValidator/docker/windows/amd64/Dockerfile
  test/modules/MetricsValidator/docker/windows/arm32v7/Dockerfile
  test/modules/ModuleRestarter/docker/windows/amd64/Dockerfile
  test/modules/ModuleRestarter/docker/windows/arm32v7/Dockerfile
  test/modules/NumberLogger/docker/windows/amd64/Dockerfile
  test/modules/NumberLogger/docker/windows/arm32v7/Dockerfile
  test/modules/Relayer/docker/windows/amd64/Dockerfile
  test/modules/Relayer/docker/windows/arm32v7/Dockerfile
  test/modules/TemperatureFilter/docker/windows/amd64/Dockerfile
  test/modules/TemperatureFilter/docker/windows/arm32v7/Dockerfile
  test/modules/TestAnalyzer/docker/windows/amd64/Dockerfile
  test/modules/TestAnalyzer/docker/windows/arm32v7/Dockerfile
  test/modules/TestResultCoordinator/docker/windows/amd64/Dockerfile
  test/modules/TestResultCoordinator/docker/windows/arm32v7/Dockerfile
  test/modules/TwinTester/docker/windows/amd64/Dockerfile
  test/modules/TwinTester/docker/windows/arm32v7/Dockerfile
  test/modules/load-gen/docker/windows/amd64/Dockerfile
  test/modules/load-gen/docker/windows/arm32v7/Dockerfile
  versionInfo.json
Labels: do-not-merge

#6069 Update Metrics Collector Release pipeline: RocksDb, E2E tests
  builds/e2e/templates/e2e-run-metrics-collector.yaml
  builds/misc/metrics-collector-images-release.yaml
Labels: ready-to-merge

#6071 [release/1.2] Update vulnerable regex package
  edgelet/Cargo.lock
  edgelet/edgelet-core/Cargo.toml
  edgelet/edgelet-http/Cargo.toml
  edgelet/iotedge/Cargo.toml
  edgelet/support-bundle/Cargo.toml
Labels: ready-to-merge

#6070 [master] Update vulnerable regex package
  edgelet/Cargo.lock
  edgelet/iotedge/Cargo.toml
Labels: ready-to-merge

#6083 [release/1.1] Update vulnerable regex versions and fix compilation errors
  edge-modules/edgehub-proxy/Cargo.lock
  edgelet/Cargo.lock
  edgelet/edgelet-core/Cargo.toml
  edgelet/edgelet-docker/src/error.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-http-mgmt/src/error.rs
  edgelet/edgelet-http-workload/Cargo.toml
  edgelet/edgelet-http-workload/src/server/cert/server.rs
  edgelet/edgelet-http-workload/tests/dns-san.rs
  edgelet/edgelet-http/Cargo.toml
  edgelet/edgelet-utils/src/lib.rs
  edgelet/iotedge-proxy/Cargo.toml
  edgelet/iotedge-proxy/src/logging.rs
  edgelet/iotedge/Cargo.toml
  edgelet/iotedged/Cargo.toml
  edgelet/iotedged/docker/linux/amd64/Dockerfile
  edgelet/iotedged/src/logging.rs
  edgelet/kube-client/Cargo.toml
  edgelet/support-bundle/Cargo.toml
  edgelet/support-bundle/src/support_bundle.rs
  tools/check_submodules/Cargo.lock
  tools/check_submodules/Cargo.toml
  tools/check_submodules/src/logging.rs
  tools/snitch/Cargo.lock
  tools/snitch/prep-mail/Cargo.toml
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#6063 Don't stop the broker if unable to restore persisted state.
  mqtt/mqttd/src/app/edgehub.rs
  mqtt/mqttd/src/app/generic.rs
Labels: ready-to-merge, area:mqtt

#6077 Devguide: Fix and enhance local EdgeHub build
  builds/misc/templates/build-rocksdb.yaml
  doc/devguide.md
  scripts/linux/buildLocalEdgeHub.sh
  scripts/linux/buildRocksDb.sh
Labels: ready-to-merge

#6085 added more logging to certificate import
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6087 added workaround for windows-certificate import problem
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6092 [release/1.2] Remove thread_local for non-edgelet projects
  edge-hub/watchdog/Cargo.lock
  edge-modules/api-proxy-module/Cargo.lock
  edge-modules/api-proxy-module/Cargo.toml
  edge-modules/edgehub-proxy/Cargo.lock
  edge-modules/edgehub-proxy/Cargo.toml
  edge-modules/edgehub-proxy/src/logging.rs
  edge-modules/edgehub-proxy/src/main.rs
  edgelet/edgelet-docker/src/error.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/edgelet-http-mgmt/src/error.rs
  mqtt/Cargo.lock
  test/modules/generic-mqtt-tester/Cargo.lock
  tools/check_submodules/Cargo.lock
  tools/check_submodules/Cargo.toml
  tools/check_submodules/src/logging.rs
  tools/snitch/Cargo.lock
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#6094 [master] Remove thread_local for non-edgelet projects
  edge-hub/watchdog/Cargo.lock
  mqtt/Cargo.lock
  test/modules/generic-mqtt-tester/Cargo.lock
  test/modules/obsagent-client/Cargo.lock
  tools/check_submodules/Cargo.lock
  tools/check_submodules/Cargo.toml
  tools/check_submodules/src/logging.rs
Labels: ready-to-merge

#6099 [release/1.1] Unconditionally publish logs
  builds/e2e/templates/e2e-run-base-image-update.yaml
  builds/e2e/templates/e2e-run-metrics-collector.yaml
  builds/e2e/templates/e2e-run.yaml
Labels: ready-to-merge

#6097 [master] Unconditionally publish logs
  builds/e2e/templates/e2e-run.yaml
Labels: ready-to-merge

#6098 [release/1.2] Unconditionally publish logs
  builds/e2e/templates/e2e-run-base-image-update.yaml
  builds/e2e/templates/e2e-run.yaml
Labels: ready-to-merge

#6090 Devguide: Fix and enhance local EdgeHub build (#6077)
  builds/misc/templates/build-rocksdb.yaml
  doc/devguide.md
  scripts/linux/buildLocalEdgeHub.sh
  scripts/linux/buildRocksDb.sh
Labels: ready-to-merge

#6102 added workaround for windows-certificate import problem
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6091 Fix edgeHub shutdown for renew certificate (#6037)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/authentication/AuthAgentProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter/brokerConnection/MqttBrokerProtocolHead.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/CertificateRenewal.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-hub/core/test/Microsoft.Azure.Devices.Edge.Hub.MqttBrokerAdapter.Test/AuthAgentListenerTest.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge, 1.2

#6104 Add Instructions to Run Azure IoT Edge Daemon Locally
  edgelet/doc/devguide.md
Labels: ready-to-merge

#6095 Fix edgeHub shutdown for renew certificate (#6037)
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/AmqpProtocolHead.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Mqtt/MqttProtocolHead.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/CertificateRenewal.cs
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge, 1.1

#6111 Update cargo dependency
  edgelet/Cargo.lock
  edgelet/docker-rs/src/apis/client.rs
  edgelet/edgelet-docker/src/runtime.rs
  edgelet/iotedge/src/client.rs
Labels: ready-to-merge

#6116 Move test clients and functions to iot-identity-service
  edgelet/Cargo.lock
  edgelet/edgelet-http-mgmt/Cargo.toml
  edgelet/edgelet-http-mgmt/src/identity/create_or_list.rs
  edgelet/edgelet-http-mgmt/src/identity/delete_or_update.rs
  edgelet/edgelet-http-mgmt/src/lib.rs
  edgelet/edgelet-http-workload/Cargo.toml
  edgelet/edgelet-http-workload/src/lib.rs
  edgelet/edgelet-http-workload/src/module/cert/mod.rs
  edgelet/edgelet-http-workload/src/module/data/decrypt.rs
  edgelet/edgelet-http-workload/src/module/data/encrypt.rs
  edgelet/edgelet-http-workload/src/module/data/mod.rs
  edgelet/edgelet-http-workload/src/module/data/sign.rs
  edgelet/edgelet-http-workload/src/trust_bundle.rs
  edgelet/edgelet-test-utils/src/clients/cert.rs
  edgelet/edgelet-test-utils/src/clients/identity.rs
  edgelet/edgelet-test-utils/src/clients/key.rs
  edgelet/edgelet-test-utils/src/clients/mod.rs
  edgelet/edgelet-test-utils/src/lib.rs
Labels: ready-to-merge

#6115 Update Microsoft.Azure.Devices.Client from 1.36.3 to 1.36.4
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge

#6120 Update Microsoft.Azure.Devices.Client from 1.36.3 to 1.36.4 (#6115)
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  edge-modules/MetricsCollector/MetricsCollector.csproj
  edge-modules/SimulatedTemperatureSensor/SimulatedTemperatureSensor.csproj
  edge-modules/functions/binding/src/Microsoft.Azure.WebJobs.Extensions.EdgeHub/Microsoft.Azure.WebJobs.Extensions.EdgeHub.csproj
  samples/dotnet/EdgeDownstreamDevice/EdgeDownstreamDevice.csproj
  samples/dotnet/EdgeX509AuthDownstreamDevice/EdgeX509AuthDownstreamDevice.csproj
  smoke/LeafDevice/LeafDevice.csproj
  test/Microsoft.Azure.Devices.Edge.Test.Common/Microsoft.Azure.Devices.Edge.Test.Common.csproj
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
  test/modules/CloudToDeviceMessageTester/CloudToDeviceMessageTester.csproj
  test/modules/DirectMethodReceiver/DirectMethodReceiver.csproj
  test/modules/DirectMethodSender/DirectMethodSender.csproj
  test/modules/EdgeHubRestartTester/EdgeHubRestartTester.csproj
  test/modules/MetricsValidator/MetricsValidator.csproj
  test/modules/ModuleLib/Microsoft.Azure.Devices.Edge.ModuleUtil.csproj
  test/modules/ModuleRestarter/ModuleRestarter.csproj
  test/modules/Relayer/Relayer.csproj
  test/modules/TemperatureFilter/TemperatureFilter.csproj
  test/modules/TwinTester/TwinTester.csproj
  test/modules/load-gen/load-gen.csproj
Labels: ready-to-merge, 1.2

#6121 Fix ValidateMetrics e2e test by increasing timeout
  builds/e2e/templates/e2e-setup.yaml
Labels: ready-to-merge

#6093 [Platform Compatibility] Added CGROUP HEIRACHY and Systemd Checks
  platform-validation/scripts/compatibility.sh
Labels: ready-to-merge

#6123 Increase test timeout for Windows
  builds/e2e/e2e.yaml
  builds/e2e/templates/e2e-setup.yaml
Labels: ready-to-merge

#6126 [master] Upgrade Rust toolchain
  edge-hub/watchdog/rust-toolchain
  edge-modules/api-proxy-module/Cargo.lock
  edge-modules/api-proxy-module/rust-toolchain
  edgelet/Cargo.lock
  edgelet/rust-toolchain
  mqtt/Cargo.lock
  mqtt/mqtt-bridge/src/messages.rs
  mqtt/mqtt-bridge/src/persist/waking_state/ring_buffer/mod.rs
  mqtt/mqtt-broker/src/state_change.rs
  mqtt/mqtt-edgehub/src/auth/authentication/edgehub.rs
  mqtt/mqtt3/src/client/mod.rs
  mqtt/mqtt3/src/proto/mod.rs
  mqtt/policy/src/validator.rs
  mqtt/rust-toolchain
  rust-toolchain.toml
  scripts/linux/generic-rust/install.sh
  test/modules/generic-mqtt-tester/Cargo.lock
  test/modules/generic-mqtt-tester/rust-toolchain
  test/modules/obsagent-client/Cargo.lock
Labels: ready-to-merge

#6082 added description for sending m2m messages on a specific output
  doc/edgehub-api.md
Labels: ready-to-merge

#6105 retry importing certificate when windows fails to use assigned private key
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6122 add dotnetty.common reference to 0.7.1
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.Diagnostics/Microsoft.Azure.Devices.Edge.Agent.Diagnostics.csproj
  edge-agent/src/Microsoft.Azure.Devices.Edge.Agent.IoTHub/Microsoft.Azure.Devices.Edge.Agent.IoTHub.csproj
  edge-hub/src/Microsoft.Azure.Devices.Edge.Hub.Core/Microsoft.Azure.Devices.Edge.Hub.Core.csproj
  test/Microsoft.Azure.Devices.Edge.Test/Module.cs
Labels: ready-to-merge, 1.1

#6101 added more logging to certificate import (cherry pick #6085)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/EdgeHubCertificates.cs
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Service/Program.cs
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6103 added workaround for windows-certificate import problem
  edge-util/src/Microsoft.Azure.Devices.Edge.Util/CertificateHelper.cs
Labels: ready-to-merge

#6137 Update tokio, rayon, and crossbeam to latest compatible versions
  edgelet/Cargo.lock
  mqtt/Cargo.lock
  test/modules/obsagent-client/Cargo.lock
Labels: ready-to-merge

#6152 Upgrade IIS to branch with crossbeam patch
  edgelet/Cargo.lock
Labels: ready-to-merge

#6107 AMQP CBS token message dispose (#6057)
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
Labels: ready-to-merge, 1.2

#6135 [release/1.1] Update tokio, rayon, and crossbeam to latest compatible versions
  edgelet/Cargo.lock
  tools/snitch/Cargo.lock
Labels: ready-to-merge

#6151 Replace rand() for serial numbers of new certificates with openssl's RAND_bytes.
  edgelet/hsm-sys/azure-iot-hsm-c/src/edge_hsm_client_store.c
  edgelet/hsm-sys/azure-iot-hsm-c/src/edge_pki_openssl.c
  edgelet/hsm-sys/azure-iot-hsm-c/src/hsm_key.h
  edgelet/hsm-sys/azure-iot-hsm-c/tests/edge_hsm_crypto_int/edge_hsm_crypto_int.c
  edgelet/hsm-sys/azure-iot-hsm-c/tests/edge_openssl_int/edge_openssl_int.c
  edgelet/hsm-sys/azure-iot-hsm-c/tests/edge_openssl_pki_ut/edge_openssl_pki_ut.c
Labels: ready-to-merge

#6156 Revert "AMQP CBS token message dispose (#6057) (#6107)"
  edge-hub/core/src/Microsoft.Azure.Devices.Edge.Hub.Amqp/CbsNode.cs
Labels: ready-to-merge

#6155 Update Windows crate dependencies following branch rename
  edgelet/Cargo.lock
  edgelet/edgelet-http/Cargo.toml
  edgelet/edgelet-test-utils/Cargo.toml
  tools/snitch/snitcher/Cargo.toml
Labels: ready-to-merge

#6160 [release/1.2] Revert crossbeam-utils upgrade
  edge-modules/edgehub-proxy/Cargo.lock
  edgelet/Cargo.lock
  edgelet/edgelet-docker/Cargo.toml
  edgelet/edgelet-docker/src/notary.rs
  mqtt/Cargo.lock
  tools/snitch/Cargo.lock
Labels: ready-to-merge

#6125 Update scripts for removing keys and certificates on edge device
  edgelet/doc/est.md
Labels: ready-to-merge

#6154 Add Check for Architecture and Minimum Docker API Version
  platform-validation/scripts/compatibility.sh
Labels: ready-to-merge

#6161 [Tools] Shellcheck addition for platform compatibility script tool.
  builds/checkin/compatibility-tool-checkin.yaml
Labels: ready-to-merge

#6159 Prepare for Release 1.2.8
  CHANGELOG.md
  edgelet/Cargo.lock
  edgelet/contrib/centos/aziot-edge.spec
  edgelet/contrib/debian/control
  edgelet/version.txt
  versionInfo.json
Labels: ready-to-merge

#6162 [Tools] Check for shared library dependency in Platform validation tool
  platform-validation/scripts/compatibility.sh
Labels: ready-to-merge

#6146 Add Kernel Config Checks Platform Compatibility Tool
  builds/checkin/compatibility-tool-checkin.yaml
  platform-validation/scripts/compatibility.sh
Labels: ready-to-merge

#6166 Workaround for `docker buildx` using in correct ARM arch for image build
  scripts/linux/buildImage.sh
Labels: ready-to-merge
